### ISSUE TITLE
[Bug]: x-errors showing up with "0 validation errors:" when using the only attribute

### ISSUE THREAD

**Issue by ChrisRiddell** [tasteui/tasteui#105]
### What Happened

Having an error component  using ` <x-errors only="session('status')" />` when a form has anther error trigger example incorrect username it triggers the box to show up when it does not need to.

<img width="464" alt="Screenshot 2023-12-04 at 4 04 06 pm" src="https://github.com/tallstackui/tallstackui/assets/109709314/4ce36d73-3c8b-4c70-89ac-1e2f17a8a540">

### How to Reproduce

create a new Laravel app, use breeze with any of the Livewire option replace the session error component on the login page with ` <x-errors only="session('status')" />` then login with an incorrect username 

### Livewire Version

3.2.3

### TallStackUi Version

1.2.0

### PHP Version

8.3

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey! @ChrisRiddell ! Thanks for your report.

I'm not sure if this is an error of the TallStackUI. From the description in the photo, you passed something incorrectly for the component. The correct thing is that you do it like this:

```blade
<x-errors only="status" />
```

Review the examples of the docs: https://tallstackui.com/docs/ui/error#filtering-properties

**Comment by ChrisRiddell** [comment]
> Hey! @ChrisRiddell ! Thanks for your report.
> 
> I'm not sure if this is an error of the TallStackUI. From the description in the photo, you passed something incorrectly for the component. The correct thing is that you do it like this:
> 
> ```
> <x-errors only="status" />
> ```
> 
> Review the examples of the docs: https://tallstackui.com/docs/ui/error#filtering-properties

You are sort of right I should have looked into the breeze's auth-session-status.blade turns out it's not an "error" response just a session token for rate limiting. I'll pick a different component to use. 😃
