### ISSUE TITLE
[Bug]: Textarea Resize Auto not resizing on load

### ISSUE THREAD

**Issue by pboese** [tasteui/tasteui#125]
### What Happened

Heya! Thanks for the great package!

Not sure wether this is a bug or wanted behaviour: I'm using e.g. `<x-textarea wire:model="address" label="Address" resize-auto />` and it does not resize the textarea when the page is loaded. As soon as I type anything in there, it resizes to the right size.

### How to Reproduce

Add the following code somewhere, only lines 1-3 are shown on load. 

```html
<x-textarea resize-auto>Test 1
Test 2
Test 3
Test 4
Test 5
Test 6</x-textarea>
```

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUi Version

1.3.4

### PHP Version

8.1.21

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @pboese ! Thanks for your report.

This was expected behavior, but I'll try to fix that this afternoon. If it works, I'll release a small version as a correction.

**Comment by devajmeireles** [comment]
@pboese , 

We've fixed this in the https://github.com/tallstackui/tallstackui/pull/127. Today I'll release a new version with this enhancement.

Thanks!

**Comment by pboese** [comment]
WOW! Thank you so much @devajmeireles! Works like a charm!
