### ISSUE TITLE
[Feature Request]: Datepicker Input

### ISSUE THREAD

**Issue by pboese** [tasteui/tasteui#133]
### Suggestion Theme

A styled input for type `date` with a nice datepicker would be awesome. The built-in browser thing is not really good. Thanks for considering :-)

### Main Benefits

A pretty and solid datepicker unlike the browser stuff.

### Source of the Suggestion

https://flowbite.com/docs/plugins/datepicker/

**Comment by vogelor** [comment]
Maybe you can add a "wrapper" around https://github.com/flatpickr/flatpickr.
i think this is a win win situation, because YOU can do what you can do best (programming a GUI) and the community of Flatpickr can do what they do best (handling all the issues with datetime picking).

and NO - i am NOT one of the programmers...

Maybe you can have a look here...

https://mary-ui.com/docs/components/datepicker

**Comment by devajmeireles** [comment]
Hey, @pboese ! Thanks for your request.

My position on this remains the same: we are working out what to do exactly, whether we create a component from scratch or make a wrapper on top of something like Flatpicker.

Positive points:
- We avoid dependencies (!)
- If we create a component from scratch, we can have a visual layout of our choice. Flatpicker doesn't seem to allow editing the layout beyond the basic variations.

Negative points:
- As much as we do a good job on a date picker component from scratch, there may still be a lack of support for everything that a library like Flatpicker covers: selecting specific dates, date range, disabling dates, date range, I don't know if we could achieve everything.

We will have a solution soon, we are just working out which is best. Feel free to help us with this decision.

**Comment by vogelor** [comment]
i think it is better to create a wrapper and let "them" fix all the problems with date picking. Maybe you take a look at myry ui how they handled the styling problem.

But please don't understand me wrong - it is up to you to make this decision. i only wanted to help - i am not the maintainer or owner...

**Comment by devajmeireles** [comment]
> i think it is better to create a wrapper and let "them" fix all the problems with date picking. Maybe you take a look at myry ui how they handled the styling problem.
> 
> But please don't understand me wrong - it is up to you to make this decision. i only wanted to help - i am not the maintainer or owner...

Don't worry. Feel free to suggest to us the best decision from your point of view. I agree with you, but the Flatpicker layout is a problem for me.

**Comment by pboese** [comment]
Thanks a lot for considering my suggestion!

I agree that flatpickr isn‘t the most beautiful picker out of the box but https://mary-ui.com/docs/components/datepicker really looks amazing. Great discussion here, thanks everyone so far!

I‘m always more for using existing stuff that already does things well instead of reinventing the wheel. Seens flatpickr can be styled nicely so it seems like a great option. 

I really wish I was better with JS and styles but I‘m just a backend dude 🤪

P.S. Can I support this project somehow? Buy coffee or beers? :-)

**Comment by devajmeireles** [comment]
> Thanks a lot for considering my suggestion!
> 
> I agree that flatpickr isn‘t the most beautiful picker out of the box but https://mary-ui.com/docs/components/datepicker really looks amazing. Great discussion here, thanks everyone so far!
> 
> I‘m always more for using existing stuff that already does things well instead of reinventing the wheel. Seens flatpickr can be styled nicely so it seems like a great option.
> 
> I really wish I was better with JS and styles but I‘m just a backend dude 🤪
> 
> P.S. Can I support this project somehow? Buy coffee or beers? :-)

The main problem with using Flatpicker is above all creating an extreme dependency, if it ceases to exist, our component would be harmed, as well as bugs. We wouldn't be able to fix it.

Feel free to always bring ideas to us, that's what drives us.

Yes! You can support the project by sponsoring my GitHub. Here is the link: https://github.com/sponsors/devajmeireles

Thanks a lot! ❤️

**Comment by devajmeireles** [comment]
👀 

![CleanShot 2024-01-26 at 13 46 05](https://github.com/tallstackui/tallstackui/assets/60591772/44bd07f0-6930-482b-bf72-ac5ef6533217)

Almost done...

**Comment by devajmeireles** [comment]
@pboese , thanks for your feature request. We just released a new version with this component, v1.20. Please, take a look into this: https://tallstackui.com/summer-release
