### ISSUE TITLE
[Feature Request]: Ghost Version of buttons

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#135]
### Suggestion Theme

At the moment you have a light Version of (rounded) buttons. But ahat i like is a "transparent Version" of the button. i mean a transparent Background and a "normal" Icon (or label)

### Main Benefits

It looks better in top-Navigations
![Screenshot 2023-12-08 110557](https://github.com/tallstackui/tallstackui/assets/1830557/597e9be9-06a3-4a7b-8a43-3de9262b0a37)

**Comment by devajmeireles** [comment]
Hey, @vogelor . Thanks for your request.

Do you mean something like this?

![CleanShot 2023-12-08 at 07 22 19](https://github.com/tallstackui/tallstackui/assets/60591772/2ed90669-4916-4117-a729-fc6662ffe003)

**Comment by vogelor** [comment]
No not 100% if you only have a icon you don't see, that this is a button.
so i think it is nicer to see a "light" Background to "realize" this is a button
your example has NO background if not hovered
![08-12-2023_11-34-54](https://github.com/tallstackui/tallstackui/assets/1830557/d8660ad9-eb88-447b-ba13-4e11da913908)

**Comment by devajmeireles** [comment]
Got it. Button without any background to be used especially with icons. Sounds very good.

**Comment by devajmeireles** [comment]
> Got it. Button without any background to be used especially with icons. Sounds very good.

That's correct, @vogelor ?

**Comment by vogelor** [comment]
Not 100%.
The background of the button has transparency, so that the background of the html pages is visible. So the button is not 100% separate from the page, it is part of the page.
For example:
There is a button with white text (icon) and no transparency.
The background of the button is black but with 80% transparency - so that (for example) the blue background of the page shines trough the button (but you can see that it is a button). If you hover over the button the background is 70% transparency.

With this effect you can have a better integration of the buttons inside the html page. I looks better at top-Navigation menus.

A „normal“ button has a harder separation and is not part of the page. It is a separate button, not a action inside the page.

Hope my English is good enough to understand.

It is about design…

**Comment by devajmeireles** [comment]
> Not 100%. The background of the button has transparency, so that the background of the html pages is visible. So the button is not 100% separate from the page, it is part of the page. For example: There is a button with white text (icon) and no transparency. The background of the button is black but with 80% transparency - so that (for example) the blue background of the page shines trough the button (but you can see that it is a button). If you hover over the button the background is 70% transparency. With this effect you can have a better integration of the buttons inside the html page. I looks better at top-Navigation menus. A „normal“ button has a harder separation and is not part of the page. It is a separate button, not a action inside the page. Hope my English is good enough to understand. It is about design…

Could you create a TailwindCSS version and send me, please? Feel free to use the [TailwindCSS playground](https://play.tailwindcss.com/), and share the direct link with me in this issue. You can copy one of our buttons and make the changes using the playground. After that, just "share" the content and send us the link.

**Comment by vogelor** [comment]
i wait until you release the config change release. Then i add this as custom color config (ghost - buttons only needs a dark and a light background).
After this is done i will post my code here.
feel free to add this code to your components...
i think this is the best way...

**Comment by devajmeireles** [comment]
Hey, @vogelor !

Our new version is live now. Try to create the ghost variation and tell us if you have any issues. Please, review the docs here: https://tallstackui.com/docs/personalization/deep#create-custom-colors

Thanks.

**Comment by vogelor** [comment]
did it...
First of all - thank you for this GREAT Update!
i published tallstackui.php and changed it to:
```php
   'components' => [
        'alert' => Components\Alert::class,
        'avatar' => Components\Avatar::class,
        'badge' => Components\Badge::class,
        'banner' => Components\Banner::class,
        'button' => Components\Button\Button::class,
        //'button.circle' => Components\Button\Circle::class,
        'button.circle' => App\View\Components\ButtonCircle::class,
```
then i created a new `ButtonCircle.php` with this content:

```php
<?php

namespace App\View\Components;

use TallStackUi\View\Components\Button\Circle;

class ButtonCircle extends Circle
{
    public function backgroundColor(): array
    {
        return [
            'solid' => [
                'ghost-dark' => 'bg-black/20 hover:bg-black/30 border-0 focus:!ring-0',
                'ghost-light' => 'bg-white/25 hover:bg-white/40 border-0 focus:!ring-0',
            ],
        ];
    }

    public function iconColor(): array
    {
        return [
            'solid' => [
                'ghost-dark' => 'text-white',
                'ghost-light' => 'text-dark',
            ],
        ];
    }
}
```

now i can use it like this:
```blade
<x-button.circle color="ghost-dark" icon="users" ... />
```
THANK YOU!!!!
