### ISSUE TITLE
[Feature Request]: tertiary color

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#136]
### Suggestion Theme

At the moment you have "two" main colors:
primary
secondary
But the problem is, the secondary color is the color of the headings and the text.
i have a logo with TWO color and i like to have these colors in my design (for example focus = primary and button = secondary
if i change now secondary color to my color, the text becomes colored. this is not what i want.

so maybe it is cool to have a additional third color (tertiary) to realize this.

So if you have a logo with 2 colors you can use all colors inside your design.

### Main Benefits

one more color to have two "real" colors to use (for example for the buttons or icons)

### Source of the Suggestion

https://getbootstrap.com/docs/5.3/customize/color/#colors

**Comment by devajmeireles** [comment]
That sounds great to me. @hitaloramon thoughts?

**Comment by devajmeireles** [comment]
According to the explanation [here](https://github.com/tallstackui/tallstackui/issues/154) you will be able to create custom colors easily after #153 is merged.
