### ISSUE TITLE
[Feature Request]: Text color in (primary) button

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#137]
### Suggestion Theme

Maybe i am wrong, but at the moment i have the following problem:
my primary color is very bright (for example use white). i can change the Background color of the button by defining the primary color as white (only for example to see it better). Now the button is white Background an white text.
You can't read the text.
But i didn't find a way to change the color of the button text to (in this example) black...

### Main Benefits

To read the text inside a button if you change primary color to a very bright colot.

**Comment by devajmeireles** [comment]
After #153 you will be able to easily customize the colors through deep personalization without the need for touch in all colors, but only in the specific colors you want to personalize. Check the examples at #154
