### ISSUE TITLE
[Bug]: Wrong position of Eye in Password Input

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#138]
### What Happened

If you have a password input then the eye is outside the input.
![Screenshot 2023-12-08 112135](https://github.com/tallstackui/tallstackui/assets/1830557/9200d21e-e852-4953-936f-519823557e36)

### How to Reproduce

us a password input

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUi Version

1.4.0

### PHP Version

8.1

### Operation System

Linux

### Notes

if you add a "position:relative" css style to the first div inside the wrapper then the icon is at the right position.

**Comment by devajmeireles** [comment]
Could you provide us with the full HTML of this login screen, please? Without any removals.

**Comment by devajmeireles** [comment]
We found the reason for the error. I'll release a new version with the fix right now.

Thanks ❤️
