### ISSUE TITLE
[Bug]: Wrong Position of smal labels in checkbox

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#139]
### What Happened

if you have a short label, then the position is wrong - it is to high
![Screenshot 2023-12-08 112618](https://github.com/tallstackui/tallstackui/assets/1830557/57e17e1d-8691-4c3f-8179-b99cbf070fb4)

### How to Reproduce

use a short label inside a checkbox

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUi Version

1.4.0

### PHP Version

8.1

### Operation System

Windows

**Comment by devajmeireles** [comment]
We've fixed this by adding alignment options when using the label as a slot. Please, review the docs:
https://tallstackui.com/docs/form/checkbox#alignment
