### ISSUE TITLE
For your documentation (if you like it)

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#140]
maybe someone likes to use tabler-icons instead of the internal icons (because tabler icons have 4850 icons (https://tabler.io/icons)
to do this follow these instuctions:

1) Install tabler icons with 
`composer require secondnetwork/blade-tabler-icons`
2) Publish the config with `php artisan vendor:publish --tag=tallstackui.config`
3) Inside the tailstackui.php Config File change the following line
```php
  'icon' => null,
``` 
to disable the internal icons

4) create a `resources/views/components/icon.blade.php`with the following content:
```blade
@props(['icon', 'name', 'left' => false, 'right' => false, 'error' => false, 'strokeWidth' => 2])

@php
    $name = match ($icon ?? $name) {
        'eye-slash' => 'eye-off',
        'cog' => 'settings',
        // 'not-existing-tabler-icon-name' => 'existing-tabler-icon-name',
        default => $icon ?? $name
    };
@endphp

@php($span = $left || $right)

@if ($span)
    <span class="inline-flex items-center gap-x-1">
@endif
    @if ($left)
        {!! $left !!}
    @endif
    <x-dynamic-component component="tabler-{{ $name ?? '' }}" {{ $attributes->merge(['stroke-width' => $strokeWidth])->class(['text-red-500' => $error]) }} />
    @if ($right)
        {!! $right !!}
    @endif
@if ($span)
    </span>
@endif
```

5) enjoy it...

**Comment by ChrisRiddell** [comment]
Just found this useful as I prefer tabler icons for it’s huge range. Thank you.

**Comment by devajmeireles** [comment]
Hey, guys. Thanks for the suggestions.

We can't do something like this (as suggested by @vogelor) because it induces people to install a package that is not under our control, it wouldn't be interesting to document that.

We are planning to add https://phosphoricons.com/ which contains 7000+ icons. I'll mark this issue as a suggestion so we can continue our plans and add this icon soon.

**Comment by ChrisRiddell** [comment]
> Hey, guys. Thanks for the suggestions.
> 
> We can't do something like this (as suggested by @vogelor) because it induces people to install a package that is not under our control, it wouldn't be interesting to document that.
> 
> We are planning to add https://phosphoricons.com/ which contains 7000+ icons. I'll mark this issue as a suggestion so we can continue our plans and add this icon soon.

I had no idea about phosphoricons they are really good, look forward to seeing support for that set.
