### ISSUE TITLE
[Feature Request]: Input mask

### ISSUE THREAD

**Issue by pablomadariagai4** [tasteui/tasteui#146]
### Suggestion Theme

Inputs

### Main Benefits

Maskable input helps us when we need an input pattern such as phone, ID, email and whatever. It is possible to make any pattern.

**Comment by ChrisRiddell** [comment]
In the meantime using AlpineJS's mask plugin should work on the input component.

https://alpinejs.dev/plugins/mask

Might be worth using that plugin for the component @devajmeireles as it works really well and alpine is already included with Livewire.

**Comment by pablomadariagai4** [comment]
I totally agree and am actually using it, we should just add a **mask** property in the tallstackui input component with some default masks like phone or money or something and load the alpine plugin by default in tallstackui:script or allow add it manually in the documentation

**Comment by devajmeireles** [comment]
The [AlpineJS mask plugin](https://alpinejs.dev/plugins/mask) will work with our inputs, so we haven't created a masking component, at least for now.

Do you believe this would be necessary? 🤔 

Likely:
- `x-maskable`

Uncertain, but perhaps useful:
- `x-currency`

**Comment by devajmeireles** [comment]
Thanks, @pablomadariagai4 !

While we don't have a native mask feature, the AlpineJS mask plugin is enough. I've introduced a basic explanation about it in our docs. Please, review it: https://tallstackui.com/docs/integrations/alpine
