### ISSUE TITLE
[Feature Request]: Way to prevent an input from automatically rendering an error message

### ISSUE THREAD

**Issue by julio-cavallari** [tasteui/tasteui#149]
### Suggestion Theme

Inputs

### Main Benefits

Creating a form with a `checkbox` or `radio` field with a validation `array|max:3` using `wire:model.live="field"` causes the error message when the user selects more than 3 items to appear in all inputs, as in image below:
<img width="949" alt="CleanShot 2023-12-09 at 16 16 33@2x" src="https://github.com/tallstackui/tallstackui/assets/53496995/f1270034-8114-43b3-bd98-0f662d25cd61">

With a way to avoid the input from rendering the error, we can only show an error message like the example below:
<img width="940" alt="CleanShot 2023-12-09 at 16 18 17@2x" src="https://github.com/tallstackui/tallstackui/assets/53496995/261fd869-dfce-4d70-a12c-0f414a06e1ee">

**Comment by devajmeireles** [comment]
Hey, @julio-cavallari ! Thanks for your request.

Sounds like an excellent idea. I'll mark this as a `suggestion` to work on this in the future. Feel free to send us a pull request so I can review and merge it. For me, it should be a per-component configuration:

```blade
<x-input ... invalidated />
```

**Comment by julio-cavallari** [comment]
It seems to me that all components that use the `x-wrapper.input` component as a wrapper already have this functionality through the `$validate` attribute, only select (styled or native), radio and checkbox components do not have this property

**Comment by devajmeireles** [comment]
> It seems to me that all components that use the `x-wrapper.input` component as a wrapper already have this functionality through the `$validate` attribute, only select (styled or native), radio and checkbox components do not have this property

You are right. We just need to add any attribute like `invalidate` in the input components and pass it through the wrapper, that's why I said it's easy to get this result. 

If we do not receive any pull requests helping us with that, I will do that on Monday aimed for our next release which will contain at least one new component (#150 )

**Comment by devajmeireles** [comment]
Hey, @julio-cavallari ! Thanks for your feature request.

I've introduced the parameter `invalidate` for all input-related components in our new version released today. Please, review the docs.

Thanks.
