### ISSUE TITLE
[Bug]: Dependent styled select don't render new options when parent property change

### ISSUE THREAD

**Issue by julio-cavallari** [tasteui/tasteui#152]
### What Happened

I have a component with 2 `styled selects`, the 2nd one is dependent on the first one, and in the component's initial render it does not have any options. As soon as I select an option in the 1st, I populate the options in the 2nd, but it does not render the new options

```php
public function mount(Projeto $projeto)
{
    $this->projeto = $projeto;
    $this->areas = $this->projeto->areas;
    $this->dispositivos = collect();
}
public function updated($property, $value)
{
    if($property === 'form.area_id'){
        $this->area = $this->areas->firstWhere('id', $value)?->load(['dispositivos']);
        $this->dispositivos = $this->area?->dispositivos ?? collect();
        return;
    }
}
```

```blade
<x-select.styled :options="$areas->toArray()" wire:model.live="form.area_id" select="label:nome|value:id" searchable />
<x-select.styled id="dispositivos" :options="$dispositivos->toArray()" select="label:nome|value:id" wire:model.live="form.dispositivo" searchable />
@php
    if($dispositivos->count()){
        dd($dispositivos); // returns the correct data
    }
@endphp
```

<img width="712" alt="CleanShot 2023-12-10 at 15 34 12@2x" src="https://github.com/tallstackui/tallstackui/assets/53496995/75daf4ed-2bc6-4875-a5de-734ddf704e52">

![CleanShot 2023-12-10 at 15 35 05@2x](https://github.com/tallstackui/tallstackui/assets/53496995/284a03d7-a67b-4ea5-bd96-f13bd0fcd64b)

### How to Reproduce

Install a fresh Laravel app, install TallStackUl, add 2 `<x-select.styled />` to a Livewire component where the 2nd one depends on options filtered by the 1st one value, visit the page, select a value in the first `<x-select.styled/ >`

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUI Version

1.4.5

### PHP Version

8.1.23

### Operation System

macOS

**Comment by devajmeireles** [comment]
I think this is a good opportunity for us to refactor the javascript of the select component. I will test this throughout the week. Thanks for the report! You make the difference. 🚀

**Comment by devajmeireles** [comment]
Hey, @julio-cavallari ! Thanks for your report.

I was able to fix the issue in the https://github.com/tallstackui/tallstackui/pull/157 which will be released with a big refactor soon. Stay tuned for our next release. Thanks!
