### ISSUE TITLE
[Feature Request]: New component Progressbar

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#155]
### Suggestion Theme

i would like a new component called progressbar.

### Main Benefits

to have a percent-indicator..

### Notes

i know this is not YOUR programming style, but i don't have the time to help you more (fork and so on). i hope if i contribute my code, YOU can faster itegrate this into YOUR coding...

resources/views/components/brogressbar.blade.php

```blade
@props(['value' => 0, 'max' => 100, 'color' => 'primary'])

@php
    $max = max([0, $max]);
    $value = max([0, $value]);
    $value = min([$value, $max]);
    $width = ($value / $max) * 100
@endphp

<div class="relative pt-1">
    <div class="overflow-hidden h-2 flex rounded bg-secondary-200 dark:bg-dark-600">
        <div style="width:{{$width}}%" class="bg-{{$color}}-500"></div>
    </div>
</div>```

**Comment by devajmeireles** [comment]
Sounds good. Maybe we can go further and add some Livewire integration based on `wire:loading`.

I'll keep this as a feature request so we can address it soon. 

For now, I'm focused on fixing the issue related to #152 to address this to the pull request #153  and continue to work on the next release that will contain maybe two new components (1 confirmed: input color, check [here](https://github.com/tallstackui/tallstackui/pull/150), 1 wip)

**Comment by devajmeireles** [comment]
Hey, @vogelor ! Are you ok?

We just released v1.21 with the addition of the new progress component. Please, take a look into this: https://tallstackui.com/docs/ui/progress

Please, feel free to submit us new feature request whenever you need to.

**Comment by vogelor** [comment]
yes i am fine - thank you for asking.
I am sorry, i am no longer using tallstackui.
you (and the community) are doing a great job - keep going!
if i come back in the future, you will definitely hear from me...

**Comment by devajmeireles** [comment]
No problem! We always notify issues after they are completed. Em 23 de mar. de 2024 13:58, Oliver Vogel ***@***.***> escreveu:
yes i am fine - thank you for asking.
I am sorry, i am no longer using tallstackui.
you (and the community) are doing a great job - keep going!
