### ISSUE TITLE
[Feature Request]: Link

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#156]
### Suggestion Theme

the "normal" link (a href=xxx) is styled like normal text. Sometimes you may like to style it more than a link.
So i started creating my own link component.

### Main Benefits

i know it is a very "silly" component.
but with this component it is easy to change the design globally if you want to change something (for example make all links bold)

### Notes

here is my resources/views/components/link.blade.php if you like it feel free to use it (if not feel free to close the issue ;-)

```blade
<a {{$attributes->class(['underline'])}} >{{ $slot }}</a>
```

**Comment by devajmeireles** [comment]
I definitely will do that, with a lot of options:

- HTML slot
- Underscore
- Target blank
- Icons
- Colors
- Size

Let me just finish up the refactors related to #153 . Please, write all your suggestions about it here. 👍🏻

**Comment by devajmeireles** [comment]
Hey, @vogelor ! Thanks for your feature request.

The link component has been released right now with the version 1.5. Learn more about the component: https://tallstackui.com/docs/ui/link
