### ISSUE TITLE
[Feature Request]: Native support for Dialog <dialog /> tag and search input tag <search />

### ISSUE THREAD

**Issue by bendo01** [tasteui/tasteui#158]
### Suggestion Theme

Components -> Form -> Inputs for ```html <search /> ```
Components -> UI -> for Modal ```html <dialog /> ```

### Main Benefits

fully support of html native syntax

### Source of the Suggestion

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by devajmeireles** [comment]
Hey, @bendo01 . Thanks for your feedback.

Let me understand, related with input do you are requesting us a new search component, right?

And with modal, we just need to use the dialog html tag, that's right?

**Comment by bendo01** [comment]
hi @devajmeireles 
thank you for your reply, and yes that is
i'm trying to make one ( or modify to be exactly), although i'm still at learning level
nb: thank you for this great UI Library

**Comment by devajmeireles** [comment]
> hi @devajmeireles thank you for your reply, and yes that is i'm trying to make one ( or modify to be exactly), although i'm still at learning level nb: thank you for this great UI Library

Could you send us a pull request with this? I'm not sure if I understand that. Sorry!

**Comment by hitaloramon** [comment]
Hey, @bendo01

Analyzing your suggestion, our modal already contains aria tags for better accessibility, which makes it very similar to the native dialog. Wrapping the modal with the dialog tag would not work, as the native tag uses the (open) property and in the TALL Stack ecosystem, alpinejs is used to control the opening of the modal. For this reason I will be closing this issue, but feel free to suggest other improvements!
