### ISSUE TITLE
[Bug]: Color component triggers submit method when wrapped in a form

### ISSUE THREAD

**Issue by smartnathan** [tasteui/tasteui#169]
### What Happened

When I click on the button to select color, it not meant to trigger a submit request when the <x-color /> component is wrapped in a form.

### How to Reproduce

Add <x-color /> component inside a form tag, ensure a method is added to the wire:submit action, then click on the botton to display color.

### Laravel Version

10.37.3

### Livewire Version

3.3.0

### TallStackUI Version

1.5.0

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @smartnathan ! Very thanks for your report.

I've just tagged a v1.5.1 to fix this issue. 👍🏻
