### ISSUE TITLE
[Feature Request]: Add Top and Bottom Side to Slide Component

### ISSUE THREAD

**Issue by Nanochan217** [tasteui/tasteui#172]
### Suggestion Theme

Extension of Slide component

### Main Benefits

Sometimes you need to have complete control of how to show content, slides or drawers opens from left or right in most of cases, but having top or bottom it's useful, specially in mobile devices where slides hide everything behind even if you aren't using the all the space that the slide brings. So, from top or bottom, the slide height may be flex and able to continue to use the size variations (md, lg, xl, etc).

### Source of the Suggestion

https://flowbite.com/docs/components/drawer/#top-drawer

**Comment by devajmeireles** [comment]
Thanks, @Nanochan217 .

I'll check it out what would be the effort for this. Please, feel free to suggest other things like that.

Also, feel free to send us a pull request if you want to help us with this.

**Comment by devajmeireles** [comment]
Hey, @Nanochan217 ! 

After a delicate review, I don't plan on doing this for now.

I appreciate your feature request. I'll tag it as a suggestion so we can analyze whether we do this or not in the future.
