### ISSUE TITLE
[Bug]: Alert - Close Button is not at the top of the component

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#175]
### What Happened

When i add a alert like this:
```blade
            <x-alert color="green" icon="check" close>
                {{ __('Wir haben dir eine neue Bestätigungs-Mail zugesendet. Bitte schaue auch mal in deinem SPAM-Ordner nach, falls sie nicht bei dir ankommt.') }}
            </x-alert>
```
the close button at the right side is vertically centered. i think it should be at the right top position...

![Screenshot 2023-12-19 172117](https://github.com/tallstackui/tallstackui/assets/1830557/3fea6d76-36ac-44f9-bb5c-67539729906f)

### How to Reproduce

copy the code into your blade.php template

### Laravel Version

10.35.0

### Livewire Version

3.2.1

### TallStackUI Version

1.5.1

### PHP Version

8.1

### Operation System

Linux

**Comment by devajmeireles** [comment]
Thanks! 

I fixed this at https://github.com/tallstackui/tallstackui/pull/177. As it is not an error that puts the use of the component at risk, I will wait for the next tag to publish it.

**Comment by devajmeireles** [comment]
v1.5.2 launched. Issue closed. Thank you!
