### ISSUE TITLE
[Feature Request]: Confirm buttons colors

### ISSUE THREAD

**Issue by pablomadariaga** [tasteui/tasteui#178]
### Suggestion Theme

The confirm dialog set buttons colors

### Main Benefits

More customization

**Comment by devajmeireles** [comment]
Hey, @pablomadariaga ! Thank you for your feature request.

Could you explain exactly what this is? Feel free to send an image, gif, or video. It will be a pleasure for us to understand this feature and see if it is useful to add it to the library.

**Comment by pablomadariaga** [comment]
![image](https://github.com/tallstackui/tallstackui/assets/69119357/d60acb37-69c8-4d30-9bd3-15fa462ecc39)
In te livewire component with Interactions trait

**Comment by devajmeireles** [comment]
> ![image](https://private-user-images.githubusercontent.com/69119357/291690945-d60acb37-69c8-4d30-9bd3-15fa462ecc39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQxNjgsIm5iZiI6MTcwMzAxMzg2OCwicGF0aCI6Ii82OTExOTM1Ny8yOTE2OTA5NDUtZDYwYWNiMzctNjljOC00ZDMwLTliZDMtMTVmYTQ2MmVjYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYjUwNGFmNjRhOWFiOTcxYmQ1ZDQ5N2NjMGYwNjc2MmYyNGM2N2E1MWJmNTljN2JlMjc5ZTYyODQ3ZmQxNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8UJceV3YT5T7PybD27AMjbUVKtqTaa69YDxg68Uo_vs) In te livewire component with Interactions trait

Thanks to @andradewall I was able to understand it after I asked you 😂 I'll work on something related with that.

**Comment by pablomadariaga** [comment]
> > ![imagen](https://private-user-images.githubusercontent.com/69119357/291690945-d60acb37-69c8-4d30-9bd3-15fa462ecc39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTQxNjgsIm5iZiI6MTcwMzAxMzg2OCwicGF0aCI6Ii82OTExOTM1Ny8yOTE2OTA5NDUtZDYwYWNiMzctNjljOC00ZDMwLTliZDMtMTVmYTQ2MmVjYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE5MjQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYjUwNGFmNjRhOWFiOTcxYmQ1ZDQ5N2NjMGYwNjc2MmYyNGM2N2E1MWJmNTljN2JlMjc5ZTYyODQ3ZmQxNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8UJceV3YT5T7PybD27AMjbUVKtqTaa69YDxg68Uo_vs)En el componente livewire con rasgo de Interacciones
> 
> Gracias a@andradewallPude entenderlo después de que te pregunté 😂 Trabajaré en algo relacionado con eso.

Excelent work i love it.

**Comment by devajmeireles** [comment]
Thanks for your feature request. I provided this possibility in #181 which will be available soon and we will document how to personalize this thing.

**Comment by devajmeireles** [comment]
Thank you for your feature request, @pablomadariaga .

I just released the 1.5.3 adding this feature. Please, take a look at the docs: https://tallstackui.com/docs/personalization/deep#override-component-colors
