### ISSUE TITLE
[Feature Request]: NavBar and Navigation/Menu

### ISSUE THREAD

**Issue by ChrisRiddell** [tasteui/tasteui#183]
### Suggestion Theme

Most UI's come with a Navbar and some menu navigations.

### Main Benefits

Easier to get started using the whole UI stack and allowing to keep the site style consistent. and Navigation is a pretty important part of that.

Working on a TallStackUI Starter/Demo application and while sorting out the Navbar it felt something like this should be more part of the UI library.

### Source of the Suggestion

https://mary-ui.com/docs/components/menu , https://daisyui.com/components/navbar/ , TailwindUI for some examples

**Comment by vogelor** [comment]
At the moment i am working at a github-like navbar.
it is a very early state - so i am not sure if i can finish it.
but if i can finish it - and it works well - i will contribute it here...

**Comment by devajmeireles** [comment]
Hey, @ChrisRiddell !

My focus at this moment is to create as many components as possible that have a direct connection with Livewire or AlpineJS. I will leave the UI components for the near future, when I will offer ready-made layouts for applications, with a navbar, sidebar, container, etc.
