### ISSUE TITLE
[Bug]: x-select.styled Error

### ISSUE THREAD

**Issue by eblount** [tasteui/tasteui#185]
### What Happened

When I use <x-select.styled wire:model='selectedSites' :options="$sites" select="label:label|value:value" searchable multiple />, I get the error:

TallStackUi\View\Components\Wrapper\Input::__construct(): Argument #3 ($id) must be of type ?string, Closure given

### How to Reproduce

Livewire properties:
 - public $selectedSites = [];
 - public $sites = [];
 - <x-select.styled wire:model='selectedSites' :options="$sites" select="label:label|value:value" searchable multiple />

Works in 1.5.1, error in 1.5.2

### Laravel Version

10.38.1

### Livewire Version

3.3.3

### TallStackUI Version

1.5.2

### PHP Version

8.2.13

### Operation System

Linux

**Comment by devajmeireles** [comment]
Working on it. The next release is tomorrow morning, correcting this problem and bringing new features.

**Comment by devajmeireles** [comment]
Thank you for your report, @eblount !

[This was fixed with version 1.5.3 released a few hours ago](https://github.com/tallstackui/tallstackui/releases/tag/v1.5.3). It's a pleasure to have you with us at TallStackUI. Feel free to report any other bugs you find.

**Comment by eblount** [comment]
Thanks, @devajmeireles . I can confirm that the issue is resolved in 1.5.3 - thanks for your work on that!
