### ISSUE TITLE
[Feature Request]:  siide up modal

### ISSUE THREAD

**Issue by hai-shift** [tasteui/tasteui#187]
### Suggestion Theme

hi
please make a modal from mobile is slide from bottom to up (until the middle screen)
and in desktop its open like a regular modal popup at the middle  

### Main Benefits

like aliexpress

**Comment by devajmeireles** [comment]
Modal mobile, 👍🏻 (2024 only).
Modal desktop-centered, this is not enough? https://tallstackui.com/docs/ui/modal#centered

**Comment by devajmeireles** [comment]
After almost two years, it will be included as standard in version 3. In the previous version, this was possible through software customization.
