### ISSUE TITLE
[Bug]: :value set on Select/Select Styled add extra quotes

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#192]
### What Happened

I have noticed when I use, the style.styled outside livewire when I set the :value tag on an element it adds extra "" quotes on the value itself. which makes validation fail on the frontend.

<img width="1057" alt="image" src="https://github.com/tallstackui/tallstackui/assets/41024720/0c87b1ba-0974-4c15-ab66-77269d6dd195">

![Screenshot 2023-12-28 at 11 51 42](https://github.com/tallstackui/tallstackui/assets/41024720/78bbc393-2fda-4945-8d43-eed3eda8c1a5)

![image](https://github.com/tallstackui/tallstackui/assets/41024720/64e66657-b02f-4046-a3c1-b73d8cbdb82d)

### How to Reproduce

Create a <x-select.styled> element  outside livewire

with a preselected/predetermined value that is a string coming from the database.

`<x-select.styled select="label:label|value:value" :options="\App\Models\User::availableLocales()" placeholder="Locale" :value="$user->locale"
                    name="locale" label="Locale" />`

### Laravel Version

10.38.2

### Livewire Version

3

### TallStackUI Version

1.5

### PHP Version

8.2.8

### Operation System

macOS

**Comment by devajmeireles** [comment]
Good catch, @AndreKendeck ! I will tag a new release today fixing this issue and other things as well. Additionally, I will document how to interact with the values when submitted through the form using `select.styled`, because when you are using multiples then you need `json_decode`

**Comment by devajmeireles** [comment]
The new tag `v1.6.7` fixes this issue. Please, upgrade the tallstackui in your project using the below command:

```bash
composer update
```
