### ISSUE TITLE
[Feature Request]: Clipboard Icon

### ISSUE THREAD

**Issue by eblount** [tasteui/tasteui#193]
### Suggestion Theme

I would love a Clipboard component that would display a clipboard icon (by default, could be changed). On mouseover, a configurable tooltip would say "Copy to Clipboard". On click, it would copy the contents of a property into the user's clipboard.

Suggested:
`<x-clipboard icon="clipboard-document-check" tooltip="Copy to Clipboard" content="This will be in the clipboard on click." />`

### Main Benefits

When displaying content to a user, sometimes it would be helpful to allow a user to easily copy certain text from a page. For example, we have a block that contains multiple key/value pairs. They are displayed one way, but when copied/pasted from the page, for example to paste into an email, the formatting is off. It would be great if I could easily add a clipboard component that would allow me to format the text and allow my users to easily copy it.

### Notes

Thanks for your consideration!

**Comment by devajmeireles** [comment]
I had already thought about it, but I didn't want to go through with it. Suggestion accepted 👍🏻 I will produce this.

**Comment by eblount** [comment]
Thanks, @devajmeireles, looking forward to it! I appreciate all your work on this library - it's made building out my project much simpler. I'm glad to see such active development.

**Comment by devajmeireles** [comment]
@eblount 

![CleanShot 2023-12-29 at 00 11 24](https://github.com/tallstackui/tallstackui/assets/60591772/4c46d269-17f7-4f57-863c-eedb315d2cf9)

Almost done...

Thoughts:

- Input style can move the button to the left
- Input and textarea style receives the `readonly` as default and not-managed
- Icon style can receive different icons
- All placeholders are translation messages

**Comment by eblount** [comment]
@devajmeireles This is looking good! Would I be able to have only an icon and specify the string to copy-to-clipboard, instead of using form elements? My use-case is mostly with displayed text, not forms (customer service needs to copy/paste info to emails). Thanks again for your work on this!

**Comment by devajmeireles** [comment]
> @devajmeireles This is looking good! Would I be able to have only an icon and specify the string to copy-to-clipboard, instead of using form elements? My use-case is mostly with displayed text, not forms (customer service needs to copy/paste info to emails). Thanks again for your work on this!

```blade
<x-clipboard label="Input" text="The text to be copied" />

<x-clipboard label="Textarea" text="The text to be copied" textarea />

<x-clipboard label="Icon" text="The text to be copied" icon />
```

The icon will be only a simple icon, and when pressed the copy effect will happen, as demonstrated in the gif.

**Comment by eblount** [comment]
Sounds good, can't wait!

**Comment by ChrisRiddell** [comment]
> @eblount
> 
> ![CleanShot 2023-12-29 at 00 11 24](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY) [ ![CleanShot 2023-12-29 at 00 11 24](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY) ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY) [ ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> 
> Almost done...
> 
> Thoughts:
> 
> * Input style can move the button to the left
> * Input and textarea style receives the `readonly` as default and not-managed
> * Icon style can receive different icons
> * All placeholders are translation messages

Will the "copied to clipboard" method be configurable in some situations you might want a little messages under the text field to say copied and some situations the toast is fine.

**Comment by devajmeireles** [comment]
> > @eblount
> > ![CleanShot 2023-12-29 at 00 11 24](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >       
> >         [
> >           
> >             ![CleanShot 2023-12-29 at 00 11 24](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >           
> >         ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >         
> >        [ ![CleanShot 2023-12-29 at 00 11 24](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY) ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >       
> >         [
> >           
> >             ![CleanShot 2023-12-29 at 00 11 24](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >           
> >         ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/60591772/293303805-4c46d269-17f7-4f57-863c-eedb315d2cf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTUwMjgsIm5iZiI6MTcwMzg1NDcyOCwicGF0aCI6Ii82MDU5MTc3Mi8yOTMzMDM4MDUtNGM0NmQyNjktMTdmNy00ZjU3LTg2M2MtZWVkYjMxNWQyY2Y5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzQwMzlhMGFjYWRiMzcyODgzNzJjYzQ1ZDMxOWM3OGYwZDA5ZGY0MTk1OWQ3YTQxZDk2OWQ1NmE5ZmM5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nsAp6BQAjXmT2MCesWIk5OwK1_OXfAQpIsYRkNzbblY)
> > Almost done...
> > Thoughts:
> > 
> > * Input style can move the button to the left
> > * Input and textarea style receives the `readonly` as default and not-managed
> > * Icon style can receive different icons
> > * All placeholders are translation messages
> 
> Will the "copied to clipboard" method be configurable in some situations you might want a little messages under the text field to say copied and some situations the toast is fine.

I've removed the toast. This is the current visual:

![CleanShot 2023-12-29 at 11 10 50](https://github.com/tallstackui/tallstackui/assets/60591772/9c7f89fa-c52c-4536-9dda-e5f773455ec1)

And yes, the texts are personalized.

**Comment by devajmeireles** [comment]
Thanks, guys.

Version 1.7.0 released now with the new Clipboard component 🚀 

Check it out: https://tallstackui.com/docs/ui/clipboard

**Comment by eblount** [comment]
@devajmeireles Thanks, AJ! It works great! I was pleasantly surprised to see that `outline` even worked for the icon. I just pushed it live for my use-case, now I'm looking around for more places to use it! Thanks for the quick turnaround, too!
