### ISSUE TITLE
[Bug]:  wire:change does not work with <x-number> <x-color> <x-select.styled>

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#194]
### What Happened

<img width="654" alt="image" src="https://github.com/tallstackui/tallstackui/assets/41024720/c0b2f259-15e7-491c-ba91-902679fe9927">
When I am want to run a saveHandler on the element value change nothing happens

### How to Reproduce

add a wire:change to any of the following elements

- x-color
- x-select.styled
- x-number

### Laravel Version

10

### Livewire Version

3

### TallStackUI Version

1.6

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @AndreKendeck ! Thanks for your report.

`wire:change` applies its associated effect with the `change` event, so in `x-color` and `x-number` it will work when you enter a value in the input and press out of the input, like the `blur` event. In `select.styled` we need to adapt if possible, because `select.styled` is a button, and not a normal HTML select.

**Comment by AndreKendeck** [comment]
https://github.com/tallstackui/tallstackui/assets/41024720/af7998fa-8ef0-4e95-8cf7-b169ecfac2fa

Maybe I am missing something? It works when I move the action to a button, but it does not fire the event when the value have been change.

**Comment by devajmeireles** [comment]
I was able to understand the issue now. I will perform some tests today.

**Comment by AndreKendeck** [comment]
@devajmeireles do model properties work with the components with the dot syntax? or do I have to make a public property on the component and assign it?

<img width="702" alt="image" src="https://github.com/tallstackui/tallstackui/assets/41024720/648cde52-2940-40ac-a289-2a797bb5b8e5">

**Comment by devajmeireles** [comment]
Done: https://github.com/tallstackui/tallstackui/releases/tag/v1.6.8

Please, upgrade your project.
