### ISSUE TITLE
[Feature Request]: Allow html tags in textarea

### ISSUE THREAD

**Issue by pablomadariagai4** [tasteui/tasteui#198]
### Suggestion Theme

Inputs

### Main Benefits

More customization

### Notes

I need to add a header pixel script in my app, but the textarea escapes all html tags, there should be an attribute that disables this feature in the inputs

**Comment by devajmeireles** [comment]
Could you provide me an example of your case of use?

**Comment by devajmeireles** [comment]
I will close this issue due to your inactivity. Feel free to open a new issue with more details. 👍🏻
