### ISSUE TITLE
[Feature Request]: Tooltip - Be able to wrap anything for a tooltip

### ISSUE THREAD

**Issue by eblount** [tasteui/tasteui#199]
### Suggestion Theme

I'm not sure how possible this will be, but I wish I could use the tooltip component for... basically anything, and have the tooltip appear on mouseover. The best example is the new clipboard icon, where I'd love to be able to have a tooltip, but I could also see using it on buttons, etc.

### Main Benefits

The tooltip component is great and easy to use! Unfortunately, it can currently only be used as an icon. If possible, it would be great to allow putting a tooltip on any component or even other non-TallStackUI page elements!

### Notes

Thanks for your consideration!

**Comment by devajmeireles** [comment]
We have no plans to enable the tooltip for all components, as there is no logic in supporting the tooltip in certain components. I don't see how this would fit into, for example, the `selec.styled` component, you know?

For all components that can receive attributes, you should be able to do something like this, see:

```blade
<x-button x-data x-tooltip="Test">
    Hover Me
</x-button>
```

**Comment by eblount** [comment]
@devajmeireles Oh, okay, thanks. I had no idea I could do that with the attribute on some components. I'll try that out, thanks

**Comment by abdul-alhasany** [comment]
@devajmeireles Thanks for  this. In this case, how would tooltip position be set?
