### ISSUE TITLE
[Bug]: Table Pagination Exception

### ISSUE THREAD

**Issue by eblount** [tasteui/tasteui#200]
### What Happened

When I use `User::all()` for the `$rows`, the table component works. When I use `User::paginate(20)`, it fails with the error:

```Property type not supported in Livewire for property [{"current_page":1,"data":...```

I can provide the full exception if needed, but it's very long and I'm not sure it's informative.

### How to Reproduce

```php
<?php

namespace App\Livewire\Admin\Pages;

use App\Models\User;
use Livewire\Component;

class Table extends Component
{
    public $headers = [
        ['index' => 'id', 'label' => '#'],
        ['index' => 'name', 'label' => 'Member'],
    ];

    public $rows = [];

    public function mount()
    {
        $this->rows = User::paginate();
    }

    public function render()
    {
        return view('livewire.admin.pages.table');
    }
}
```

```php
<div>
    <x-table :$headers :$rows />
</div>
```

### Laravel Version

10.39

### Livewire Version

3.3.3

### TallStackUI Version

1.7.0

### PHP Version

8.2.14

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @eblount . Thanks for your report.

This issue is not related to TallStackUI. You are trying to bind an unsupported type to a Livewire property. Check supported types here: https://livewire.laravel.com/docs/properties#supported-property-types

This error occurs even if you try a simple `@foreach` without the table component:

```blade
<div>
    @foreach ($rows as $key => $value)
        {{ $value->name }}
    @endforeach
</div>
```

An excellent solution to this is to use a computed property:

```php
// remove the $rows property...

#[Computed]
public function rows()
{
    return User::paginate();
}
```

```blade
<x-table :$headers :rows="$this->rows" />
```

**Comment by eblount** [comment]
@devajmeireles Thank you so much for taking the time to teach me. I am fairly new to Livewire and obviously didn't know this. I appreciate it. I tried your suggestion and it worked perfectly.

Great job on the table! I have one wishlist item for it now: would it be possible to add responsive classes to the column configuration to hide certain columns at different screen widths? I can create a Feature Request if needed. Thanks again!

**Comment by devajmeireles** [comment]
No plans for this now. Only next year.

**Comment by rgazeredo** [comment]
Another solution that worked for me was to pass the $rows variable as a parameter to the view via render()

```
<?php

namespace App\Livewire;

use App\Models\Customer;
use Illuminate\Database\Eloquent\Builder;
use Livewire\Component;
use Livewire\WithPagination;

class AppCustomerLivewire extends Component
{
    use WithPagination;

    public ?int $quantity = 10;
    public ?string $search = null;
    public $headers = [
        ['index' => 'id', 'label' => '#'],
        ['index' => 'name', 'label' => 'Member'],
    ];

    public function render()
    {
        $rows = Customer::query()
            ->when($this->search, function (Builder $query) {
                return $query->where('name', 'like', "%{$this->search}%");
            })
            ->paginate($this->quantity)
            ->withQueryString();

        return view('livewire.app-customer-livewire', compact('rows'));
    }
}
```
