### ISSUE TITLE
[Bug]: Installing tallstack ui breaks default Laravel breeze

### ISSUE THREAD

**Issue by rabol** [tasteui/tasteui#204]
### What Happened

Installing Tallstack UI breaks standard app installation e.g the dropdown for the settings menu does not show up

### How to Reproduce

using the laravel installer:

1) laravel new my-app
2) cd my-app
3) modify .env
4) composer require laravel/breeze
5) php artisan breeze:install, select Livewire(Volt Class API) with Alpine, dark mode, pest
6) php artisan migrate

open site in browser and register a user, then observe that there is a profile dropdown in the upper right corner

Now in stall tallstack ui

following the instructions

Open the site and observe that the 'dropdown' does not appear anymore

removing the tallstack ui package
```
composer remove tallstackui/tallstackui
```

and cleaning up the tailwind.config, one will get an error
```
Class "TallStackUi\View\Components\Dropdown\Dropdown" not found
```

when accessing the dashboard

(Note: the error from removing tallstack ui is not in the repository)

### Sample Repository

https://github.com/rabol/tallstack

### Laravel Version

10.39.0

### Livewire Version

3.3.3

### TallStackUI Version

1.7.1

### PHP Version

8.3.1

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @rabol ! Thanks for your report. 

I'm preparing a next version that will provide us the ability to set a custom prefix to avoid conflict with other components, such as components of Laravel Breeze and Jetstream.

**Comment by devajmeireles** [comment]
Thanks, @rabol !

With our latest release, this is not a problem anymore. You can set a prefix for the TallStackUI components. Make sure to upgrade your composer dependencies, and after that sync your TallStackUI configuration file with this new content 👇🏻 

```php
<?php

use TallStackUi\View\Components;

return [
    /*
    |--------------------------------------------------------------------------
    | Prefix
    |--------------------------------------------------------------------------
    |
    | Control the prefix for TallStackUI components. This prefix will be used
    | to prefix all components registered by TallStackUI. You can change
    | this prefix to avoid conflicts with other components.
    |
    | Example: prefix as 'ts-', usage: '<x-ts-alert />'
    */
    'prefix' => null,

    // ...
```
