### ISSUE TITLE
[Feature Request]: Dynamic type in confirmation toast

### ISSUE THREAD

**Issue by julio-cavallari** [tasteui/tasteui#207]
### Suggestion Theme

It would be interesting if it were possible to change the icon type in the confirm toast component.

### Main Benefits

I tried to create an undo action and it would be interesting to provide the undo option with feedback that everything went well and not with a question icon, but it seems to me that when the type is not question it does not render the options sent.

```php
$this->toast()->timeout(10)->confirm([
    'type' => 'success',
    'title' => 'Arquivo enviado com sucesso!',
    'description' => '',
    'options' => [
        'confirm' => [
            'text' => 'Desfazer',
            'method' => 'dispatch',
            'params' => ['analytics_3d:undo-upload'],
        ],
    ],
]);
```

**Comment by devajmeireles** [comment]
Thanks, @julio-cavallari .

No plans for that! At first, I would say it is impossible to define the icon through the event because what comes from the backend is JavaScript and the icons are PHP. Maybe it's possible to make it so that, regardless of the type (success, error...), there would be confirmation buttons, but I'm not sure if that's something interesting. 

I suggest using the `x-alert` with text and a href that leads to the desired effect when clicked, displaying the alert conditionally after successfully uploading a file, for example.

**Comment by julio-cavallari** [comment]
`x-alert` would not work in this case, because every action is performed through an `x-modal`, and the **UX** would not be good with this component.

But I believe it would be interesting for any type of `x-toast` to have actions, like [filamentphp notfications](https://filamentphp.com/docs/3.x/notifications/sending-notifications#adding-actions-to-notifications) for example,  it doesn't seem complex to me, since it would just be removing the lock that currently limits the rendering of actions to the _**question**_ type

But anyway, thanks for the feedback, have a nice day :)

**Comment by devajmeireles** [comment]
> `x-alert` would not work in this case, because every action is performed through an `x-modal`, and the **UX** would not be good with this component.
> 
> But I believe it would be interesting for any type of `x-toast` to have actions, like [filamentphp notfications](https://filamentphp.com/docs/3.x/notifications/sending-notifications#adding-actions-to-notifications) for example, it doesn't seem complex to me, since it would just be removing the lock that currently limits the rendering of actions to the _**question**_ type
> 
> But anyway, thanks for the feedback, have a nice day :)

Yeah! It seems like a very good idea. I will plan that for this year.
