### ISSUE TITLE
[Feature Request]: File Uploader 

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#212]
### Suggestion Theme

Maybe a Fileuploader that works well with livewire to store files on a server

### Main Benefits

A fitting theme for uploading files to the server using a drag and drop theme or a much sleeker design

### Source of the Suggestion

https://bladewindui.com/component/filepicker

**Comment by devajmeireles** [comment]
Hey, @AndreKendeck ! Thanks for your suggestion. We introduced the `upload` component in the release 1.13.0 we released today.
