### ISSUE TITLE
[Bug]: Styled Dropdown Multi-Select doesnt not work with existing values on multi-arrays

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#217]
### What Happened

the <x-select.style> does not work with multi array, or maybe I am doing it wrong?

<img width="254" alt="image" src="https://github.com/tallstackui/tallstackui/assets/41024720/ff42cb9d-ff87-4578-af78-078924fe55de">

<img width="662" alt="image" src="https://github.com/tallstackui/tallstackui/assets/41024720/025fb17c-49c7-4684-9a82-ff603697f312">

### How to Reproduce

Have a multi select.native component and have a multi dimensional array of options with selected values

### Laravel Version

10

### Livewire Version

3

### TallStackUI Version

1.6

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
The `select.styled` works with multi-dimensional array. Please, check the docs again: https://tallstackui.com/docs/ui/select#styled-multi-dimensional-array

```blade
<x-select.styled wire:model="editor" :options="[
    ['id' => 53, 'name' => 'Andre'],
    ['id' => 54, 'name' => 'Thulani'],
]" select="label:name|value:id" />
```

In this above example, when selecting some user, the `wire:model` `editor` will be `53` or `54`.

Feel free to reply to this issue by ping me using @ if you think this is a bug according to the docs.
