### ISSUE TITLE
[Bug]: x-radio add "id" attribute to use it in the label with the attribute "for"

### ISSUE THREAD

**Issue by DavidCide** [tasteui/tasteui#219]
### Suggestion Theme

I'm migrating from other UI library and I had this simple filter:

```
  <div>
      <div class="flex">
          <div class="flex items-center me-4">
              <x-radio id="1day" label="1 Días" wire:click="filter" value="1" wire:model="daysFilter" />
          </div>
          <div class="flex items-center me-4">
              <x-radio id="7day" label="7 Días" wire:click="filter" value="7" wire:model="daysFilter" />
          </div>
          <div class="flex items-center me-4">
              <x-radio id="30day" label="30 Días" wire:click="filter" value="30" wire:model="daysFilter" />
          </div>
          <div class="flex items-center me-4">
              <x-radio id="all" label="Todo" wire:click="filter" value="all" wire:model="daysFilter" />
          </div>
      </div>
  </div>
```
The component put the attribute "for" in the label with the value of wire:model and every time I click in a label of that radios the focus goes to the first one.
Maybe it will be better if I could put the "id" attribute and that value goes to the "for" of the label

### Main Benefits

- Fix the focus of the inputs
- Don't need to make 4 variables to fix the focus

**Comment by devajmeireles** [comment]
Thanks. Fixed in v1.9.2. Please, upgrade your dependencies: `composer update`
