### ISSUE TITLE
[Bug]: Cancel button not showing by default on confirm dialog

### ISSUE THREAD

**Issue by Ryuuji159** [tasteui/tasteui#223]
### What Happened

I noticed a change with the confirm dialog component, where the cancel button is hidden if there isn't a method defined, that change was made on the commit 68623f4 so it was a deliverate change.

I want to argue that maybe that isn't the best idea, if I'm asking an user for confirmation about an action, he needs to be able to decline it, and having to close the dialog isn't as intuitive as a button, with this change I would need to add more overhead to my code, having to add the text and the method the dialog will call when canceled, that 90% of the time will do nothing.

Maybe a middleground is just needing to have to call confirm with the cancel text like so:
```php
$this->dialog()->confirm('Warning!', 'Are you sure?', [
    'confirm' => [ ... ],
    'cancel' => [
        'text' => 'Cancel',
    ]
]);
```

Or maybe make it backwards, where we set null to the cancel option to not show the cancel button on the dialog

```php
$this->dialog()->confirm('Warning!', 'Are you sure?', [
    'confirm' => [ ... ],
    'cancel' => null
]);
```

### How to Reproduce

Call a confirm dialog with the just the confirm option
```php
$this->dialog()->confirm('Warning!', 'Are you sure?', [
    'confirm' => [ ... ]
]);
```

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUI Version

1.9.2

### PHP Version

^8.1

### Operation System

Linux

**Comment by devajmeireles** [comment]
I got it. I will work on that.

**Comment by devajmeireles** [comment]
Release 1.10.0 released today introduces new concepts in the Dialog & Toast. Please, update your TallStackUI and check the docs.
