### ISSUE TITLE
[Feature Request]: Styled-Select: need dropdown version without X to de-select

### ISSUE THREAD

**Issue by bartotto** [tasteui/tasteui#224]
### What Happened

When I use <x-ts-select.styled label="{{ __('info.language') }} *" wire:model.blur="language" :options="[
      ['label' => trans('info.dutch'), 'value' => 'nl'],
      ['label' => trans('info.english'), 'value' => 'en'],
]" select="label:label|value:value" />

My form shows a X in the dropdown to delete the selected option (see attached screen print)

![Scherm­afbeelding 2024-01-06 om 17 37 30](https://github.com/tallstackui/tallstackui/assets/33985339/a7ec139f-c227-40a2-b1f2-815d662f7d63)

Can you please provide an x-select-styled without the X?

I also got confused by the docs as the second version does not have the X (and I do not understand why), see attached screen print.

![Scherm­afbeelding 2024-01-06 om 17 40 08](https://github.com/tallstackui/tallstackui/assets/33985339/eda4ebc4-ab41-432e-9132-e17aeb2f77a4)

### How to Reproduce

see above

### Laravel Version

10.39.0

### Livewire Version

3.3.5

### TallStackUI Version

1.9.2

### PHP Version

8.2.14

### Operation System

Linux

### Notes

Many thanks for your excellent work and greetings from The Netherlands!
Bart

**Comment by devajmeireles** [comment]
We had the possibility of hiding the X, but it was removed because even without the X the user could open the select and click to deselect a selected value, you know? 

I'm going to try a new format to completely disable the select as empty: without X, and without the possibility of deselecting the selected values.

**Comment by devajmeireles** [comment]
Issue blocked till next release. PR #225 introduces this.

**Comment by devajmeireles** [comment]
Release 1.10.0 released today introduces the `required` attribute. Please, update your TallStackUI and check the docs.
