### ISSUE TITLE
[Feature Request]: Tag input

### ISSUE THREAD

**Issue by gregmsanderson** [tasteui/tasteui#227]
### Suggestion Theme

It would be great to have a form input that allows editing tags. So you could type in a tag like _example_, press Enter/Return, and it would be added as a removable "chip" in the input.

_Kind_ of like this: [https://tallstackui.com/docs/ui/select#styled-api-multiple](https://tallstackui.com/docs/ui/select#styled-api-multiple) however _without_ the select/dropdown to choose an existing value.

### Main Benefits

Many items (blog posts, assets etc) benefit from tagging.

### Source of the Suggestion

https://www.radix-vue.com/components/tags-input.html

### Notes

A Vue example https://www.radix-vue.com/components/tags-input.html

A React example https://mantine.dev/core/tags-input/

**Comment by devajmeireles** [comment]
This was in our backlog, and now with your feature request I see that it is really interesting.

**Comment by devajmeireles** [comment]
Release 1.10.0 released today introduces the new `tag` component. Please, update your TallStackUI and check the docs.
