### ISSUE TITLE
[Feature Request]: Aria attributes, for accessibility

### ISSUE THREAD

**Issue by gregmsanderson** [tasteui/tasteui#228]
### Suggestion Theme

I'm not sure if this is already possible but it would be good if the elements had additional attributes to help with accessibility (keyboard controls and screen readers). For example _aria_ attributes like _aria-required_ on form inputs.

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics

### Main Benefits

All sites should be accessible :)

### Source of the Suggestion

https://react-spectrum.adobe.com/react-aria/accessibility.html

**Comment by devajmeireles** [comment]
@gregmsanderson , I appreciate your interest in this. Unfortunately, we don't have plans for that right now. Regardless, feel free to send us a pull request adapting the components to support this. If you send it, I will analyze it and if everything is ok, we will accept it.
