### ISSUE TITLE
[Bug]: Console errors when scrolling on page with dropdown

### ISSUE THREAD

**Issue by Ryuuji159** [tasteui/tasteui#235]
### What Happened

My layout has a header with an user options dropdown implemented like this inside a Volt Livewire Component
```blade
<div class="hidden lg:flex lg:items-end pb-4 lg:ml-6">
    <x-dropdown text="{{ auth()->user()->name }}" position="bottom-end">
        <x-dropdown.items text="{{ __('Salir') }}" wire:click="logout"/>
    </x-dropdown>
</div>
```

This apparently is causing thousands of errors on the console whenever I scroll the page 
![image](https://github.com/tallstackui/tallstackui/assets/17039188/f2f0a793-0e4e-4ae7-91a6-769d0d42381c)

Given the debug on the browser, the code its failing to get the dropdown reference to hide it if its outside view.
![image](https://github.com/tallstackui/tallstackui/assets/17039188/bd5468fb-ce77-4122-86d6-1d178d359109)

### How to Reproduce

I could'nt make a fresh project, but in my case, I have the following base layout
```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <!-- Scripts -->
    <tallstackui:script/>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="font-sans antialiased">
<div class="min-h-screen bg-gray-100 dark:bg-gray-900">
    <livewire:layout.navigation/>

    <!-- Page Heading -->
    @if (isset($header))
        <header class="bg-heading bg-cover shadow">
            <div class="max-w-screen-2xl mx-auto py-10 px-4 sm:px-6 lg:px-8 ">
                {{ $header }}
            </div>
        </header>
    @endif

    <!-- Page Content -->
    <main>
        <div class="py-12">
            <div class="max-w-screen-2xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white dark:bg-gray-800  shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900 dark:text-gray-100">
                        {{ $slot }}
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@livewireScriptConfig
</body>
</html>
```

Where the navigation component is a simple Livewire Volt Component that has something like this 
```php
<?php

use Livewire\Volt\Component;

new class extends Component {
    public function logout(): void
    {
        auth()->guard('web')->logout();

        session()->invalidate();
        session()->regenerateToken();

        $this->redirect('/', navigate: true);
    }
}; ?>
<nav x-data="{ open: false }" class="bg-white">
    <!-- Primary Navigation Menu -->
    <div class="max-w-screen-2xl mx-auto px-4 lg:px-6 lg:px-8">
        <div class="flex justify-between h-24">
            <a href="{{ route('projects.index') }}" wire:navigate>
                <x-application-logo class="block object-contain h-[90px]"/>
            </a>
            <div class="hidden lg:flex lg:items-end pb-4 lg:ml-6">
                <x-dropdown text="{{ auth()->user()->name }}" position="bottom-end">
                    <x-dropdown.items text="{{ __('Salir') }}" wire:click="logout"/>
                </x-dropdown>
            </div>
       </div>
   </div>
</nav>
```

And this is called from full page livewire components using the Layout Attribute
```php
<?php

namespace App\Livewire\Projects;

use Livewire\Attributes\Layout;
use Livewire\Component;

#[Layout('layouts.app')]
class Create extends Component
{
    public function render()
    {
        return view('livewire.projects.create');
    }
}
```

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUI Version

1.9.2

### PHP Version

^8.1

### Operation System

Linux

**Comment by devajmeireles** [comment]
@Ryuuji159 , I've noticed you're using `@livewireScriptConfig` instead of `@livewireScripts` in your base layout. Do you have any reason for this? Otherwise, the correct to be used is `@livewireScripts`.

**Comment by Ryuuji159** [comment]
I'm using to load some plugins and data directives to AlpineJS that `@livewireScripts` wouln't load

My `app.js` is the following if it helps debuging the problem
```js
import './bootstrap';
import 'iconify-icon';

//https://laravel.com/docs/10.x/vite#blade-processing-static-assets
import.meta.glob([
    '../images/**',
]);

//https://livewire.laravel.com/docs/upgrading#accessing-alpine-via-js-bundle
import {Livewire, Alpine} from '../../vendor/livewire/livewire/dist/livewire.esm';
import templateEditor from "./templateEditor.js";
import collapse from '@alpinejs/collapse'

import Chart from 'chart.js/auto';
import {TreemapController, TreemapElement} from 'chartjs-chart-treemap';
import tippy, {followCursor} from "tippy.js";

Alpine.plugin(collapse)
Alpine.data('templateEditor', templateEditor)

Chart.register(TreemapController, TreemapElement);
window.Chart = Chart;

Livewire.start()
```

**Comment by devajmeireles** [comment]
> I'm using to load some plugins and data directives to AlpineJS that `@livewireScripts` wouln't load
> 
> My `app.js` is the following if it helps debuging the problem
> 
> ```js
> import './bootstrap';
> import 'iconify-icon';
> 
> //https://laravel.com/docs/10.x/vite#blade-processing-static-assets
> import.meta.glob([
>     '../images/**',
> ]);
> 
> //https://livewire.laravel.com/docs/upgrading#accessing-alpine-via-js-bundle
> import {Livewire, Alpine} from '../../vendor/livewire/livewire/dist/livewire.esm';
> import templateEditor from "./templateEditor.js";
> import collapse from '@alpinejs/collapse'
> 
> import Chart from 'chart.js/auto';
> import {TreemapController, TreemapElement} from 'chartjs-chart-treemap';
> import tippy, {followCursor} from "tippy.js";
> 
> Alpine.plugin(collapse)
> Alpine.data('templateEditor', templateEditor)
> 
> Chart.register(TreemapController, TreemapElement);
> window.Chart = Chart;
> 
> Livewire.start()
> ```

1. Have you noticed issues with other components?
2. Could you share the repository with us?

**Comment by Ryuuji159** [comment]
I haven't really noticed issues with other components, and can't really share the repository, as is a project for a private client, but I will try to create an example repository tonight

**Comment by devajmeireles** [comment]
> I haven't really noticed issues with other components, and can't really share the repository, as is a project for a private client, but I will try to create an example repository tonight

Sounds good. Thanks!

**Comment by Ryuuji159** [comment]
I just created a minimal project with the minimal code that reproduces the code [here](https://github.com/Ryuuji159/tallstackui-error-reproduction) 
Something I noticed is that the error starts to happen only when I navigate to another page, not on initial page.

**Comment by devajmeireles** [comment]
Hey, @Ryuuji159 !

I was unable to reproduce the same problem you described. In this repository everything works fine, but there is one thing that needs to be noted: this repository is using Livewire in SPA mode, so [as our documentation describes](https://tallstackui.com/docs/installation#livewire-spa-mode), you need to load TallStackUI from the `welcome` file

Using the `welcome` like this:

```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
```

I get the errors:
![CleanShot 2024-01-11 at 23 13 59](https://github.com/tallstackui/tallstackui/assets/60591772/5164d7bd-d729-4aed-893b-5deeb66e1d44)

⬆️  This happens when I access the `welcome` and navigate to `dashboard`

---

**To solve this** I just need to load TallStackUI scripts in the `welcome`:

```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        <tallstackui:script/>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
```

I suspect this happens because Livewire just evaluates what a script is and `<tallstackui:scripts />` actually generates a route that points to the TallStackUI JavaScript. Could you test, please? Just persist the TallStackUI script between the first page rendered and the others too.

**Comment by Ryuuji159** [comment]
I didn't tested the welcome/login page, I was testing between /dashboard and clicking again on dashboard, that generates the error on my side 

https://github.com/tallstackui/tallstackui/assets/17039188/376d12d5-016f-4ba1-b1aa-e89f94eb58b7

**Comment by devajmeireles** [comment]
Thansk so much, @Ryuuji159 ! I was able to reproduce the issue and release a new tag to fix the problem. I think the reason for that is the usage of `window` in Livewire SPA mode. If you notice we have the same problem for other components, please open new issues.
