### ISSUE TITLE
Multi select input visibility

### ISSUE THREAD

**Issue by anu-wkd** [tasteui/tasteui#256]
### What Happened

When I use <x-select.styled multiple />, input field doesn't grow with its content size. I can see that its due to the truncate class in one of the divs. Looking into personalization blocks of Select Styled there aren't any that can be used to remove or replace this class.
`<div wire:ignore class="truncate" x-show="multiple && quantity > 0"> ... </div>`

### How to Reproduce

Use a <x-select.styled multiple /> with options containing long labels.

### Laravel Version

10.34

### Livewire Version

3.0

### TallStackUI Version

1.9

### PHP Version

8.1

### Operation System

macOS

**Comment by devajmeireles** [comment]
I think I couldn't understand. As per my tests, I was unable to see an issue with input.

![CleanShot 2024-01-17 at 13 02 24](https://github.com/tallstackui/tallstackui/assets/60591772/bde138bb-60da-4975-8522-840e85aff8f9)

I just noticed a small issue when hover the items containing long labels. Are you talking about it?

**Comment by anu-wkd** [comment]
In your example, you can only see one item even though you have selected three. The input field should grow vertically showing all three values.

**Comment by devajmeireles** [comment]
I understand now. Thanks! We will create a personalizable block for this and also fix the hover issue.

**Comment by devajmeireles** [comment]
Thanks, @anu-wkd ! It was solved in the 1.13.0 released now. We've added new blocks for soft personalization.
