### ISSUE TITLE
[Feature Request]: Upload component - Preview File and delete for edit forms

### ISSUE THREAD

**Issue by pablomadariagai4** [tasteui/tasteui#263]
### Suggestion Theme

I need to edit a form that already has a file loaded, I need this preview to be preloaded and be able to delete it or replace it with a new one

### Main Benefits

It will help us edit forms with existing files in the models

**Comment by devajmeireles** [comment]
Sounds pretty good. Working on it.

**Comment by devajmeireles** [comment]
Issue locked till next release. Issue resolved. Feature added on #264

**Comment by devajmeireles** [comment]
Hey, @pablomadariagai4 ! Thanks for your suggestion. We just released the 1.13.1 adding this possibility. Please, review the docs: https://tallstackui.com/docs/form/upload#static-concept
