### ISSUE TITLE
[Bug]: File Upload component doesnt work when binding wire:model to an object

### ISSUE THREAD

**Issue by Ryuuji159** [tasteui/tasteui#265]
### What Happened

If I use `<x-upload wire:model="form.document"/>` I get the error `Property [$form.document] not found on component` with form being a Livewire Form object

![image](https://github.com/tallstackui/tallstackui/assets/17039188/336a4c02-4b8d-49e2-9982-454bde967bca)

### How to Reproduce

Try to bind x-upload to a nested object, in this case a Livewire Form object
`<x-upload wire:model="form.document"/>` 

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUI Version

1.13.0

### PHP Version

^8.1

### Operation System

Linux

**Comment by devajmeireles** [comment]
Thanks. Working on that.

**Comment by devajmeireles** [comment]
Issue locked till next release. Issue resolved.

**Comment by devajmeireles** [comment]
Please, upgrade your project to fix that issue: `composer update`
