### ISSUE TITLE
[Feature Request]: possibility to change component colors

### ISSUE THREAD

**Issue by compaoreh338** [tasteui/tasteui#268]
### Suggestion Theme

for example the spinner color for  component `<x-loading />  `nd his  transition can't be changed

### Main Benefits

it allows users to personalize the component by styling it themselves

### Source of the Suggestion

https://alpinejs.dev/directives/

**Comment by hitaloramon** [comment]
Hi, @compaoreh338 

You can customize using the concept of soft personalization or deep personalization

[Link documentation](https://tallstackui.com/docs/personalization/concept)
