### ISSUE TITLE
[Feature Request]: Timepicker Component

### ISSUE THREAD

**Issue by nkvatadze** [tasteui/tasteui#273]
### Suggestion Theme

A styled with  input for time component would be great. If you consider this thanks a lot ! 

### Main Benefits

A time component would be nice to have in this package.

### Source of the Suggestion

https://hilla.dev/docs/react/components/time-picker https://v1.wireui.dev/docs/time-picker

**Comment by hitaloramon** [comment]
We are already working on it.

**Comment by devajmeireles** [comment]
Yeah! This is a work in progress for one of our next components. 🔥

**Comment by nkvatadze** [comment]
Thanks A lot !

**Comment by devajmeireles** [comment]
👀 

![CleanShot 2024-01-30 at 15 36 02](https://github.com/tallstackui/tallstackui/assets/60591772/73ad5733-ef78-46cf-97bc-6a8b7cd52cf8)

**Comment by nkvatadze** [comment]
Can't wait ! Looks great

**Comment by devajmeireles** [comment]
@nkvatadze , thanks for your feature request. We just released a new version with this component, v1.20. Please, take a look into this: https://tallstackui.com/summer-release
