### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [input]

### ISSUE THREAD

**Issue by joelhmetz** [tasteui/tasteui#279]
### What Happened

When I use `<x-ts-upload />` I get an error:

Unable to locate a class or view for component [input].

### How to Reproduce

Install a fresh Laravel app, add a <x-ts-upload /> to a Livewire component

### Laravel Version

10.43.0

### Livewire Version

3.4

### TallStackUI Version

1.14

### PHP Version

8.2.12

### Operation System

Windows

**Comment by joelhmetz** [comment]
Sorry, I was calling Alpine duplicate.

**Comment by devajmeireles** [comment]
I appreciate your report. I just released a new tag right now fixing this issue. 

Please, upgrade your TallStackui:

```shell
composer update && npm run build && php artisan optimize:clear
```
