### ISSUE TITLE
[Feature Request]: Select Searchable with the content of the description

### ISSUE THREAD

**Issue by joelhmetz** [tasteui/tasteui#287]
### Suggestion Theme

Search within the description when there is one in Select.

### Main Benefits

There are cases where a company has the name reason and fancy, for example; I put the name, the ledger and the description, the costume and the cnpj.

### Notes

If there is already a way, could you please let me know.

**Comment by devajmeireles** [comment]
This makes total sense. I addressed this in the pull request: https://github.com/tallstackui/tallstackui/pull/288. 

The PR was directed to the next big release that we will do soon: `summer release`. Until then, I will keep this issue locked.

**Comment by devajmeireles** [comment]
Hey, @joelhmetz !

We released this feature in v1.15.0, which is out now. Please make sure to update your TallStackUI and test the feature:

```shell
composer update && npm run build && php artisan optimize:clear
```

Feel free to open a new issue whenever necessary.

**Comment by joelhmetz** [comment]
It worked beautifully here, thank you very much.

**Comment by joelhmetz** [comment]
Search by description stopped working in the most current version.

Tallstackui 1.35.10
Laravel Framework 11.30.0

https://www.loom.com/share/ccb628fb4f98410cb0bf75664d858836?sid=9263e214-3aab-4a96-9e92-f4f7ee144e16
