### ISSUE TITLE
[Feature Request]: Allow to customize the style of the wrapper around the responsive select on the Tab component

### ISSUE THREAD

**Issue by Ryuuji159** [tasteui/tasteui#309]
### Suggestion Theme

Hi, I'm using the tab component that has like 6  items and I wanted to change the breakpoint where it transforms to a select, but I cant change the breakpoint used here

https://github.com/tallstackui/tallstackui/blob/fa91987a6f6469deb6e9d58c0fb75871e592ee3b/src/resources/views/components/tab/tab.blade.php#L8-L13

That means that there is a moment where it shows as a select but doesnt have a padding around it.
![image](https://github.com/tallstackui/tallstackui/assets/17039188/d22c2887-61de-4a16-8780-36194713cabd)

As oposed to 
![image](https://github.com/tallstackui/tallstackui/assets/17039188/51b132ef-f599-41d4-858f-c627b292ddb0)

### Main Benefits

We will be able to change the breakpoint where the tab changes to a breakpoint

**Comment by devajmeireles** [comment]
Hey, @Ryuuji159 ! Thanks for your feature request. 

Couldn't you change the breaking point by using the `body` and `select` soft personalization blocks?

**Comment by Ryuuji159** [comment]
I did that + a few other things given the design im following, but the only one I'm missing is the one mentioned before

```php
 TallStackUi::personalize()
            ->tab()
            ->block('wrapper', 'dark:bg-dark-700 w-full bg-white')
            ->block('body', 'soft-scrollbar hidden px-4 pt-2 flex-nowrap overflow-auto lg:flex gap-2 bg-gray-950')
            ->block('item', ' text-secondary-700 dark:text-dark-300 p-4')
            ->block('divider', 'hidden')
            ->block('select', 'focus:border-primary-500 focus:ring-primary-500 dark:bg-dark-700 dark:border-dark-500 w-full border-gray-200 px-4 py-3 dark:text-gray-400 lg:hidden');

        TallStackUi::personalize()
            ->tab('items')
            ->block('wrapper', 'inline-flex items-center gap-4 whitespace-nowrap  px-4 py-1 transition-all xl:min-w-32')
            ->block('select', 'text-gray-950 bg-white group inline-flex cursor-pointer items-center font-medium ')
            ->block('unselect', 'bg-primary-500 text-white hidden cursor-pointer font-medium lg:flex');
```

I tried adding a padding on the wrapper between sm and lg but that adds it to the whole tab, not just the header

**Comment by devajmeireles** [comment]
> I did that + a few other things given the design im following, but the only one I'm missing is the one mentioned before
> 
> ```
>  TallStackUi::personalize()
>             ->tab()
>             ->block('wrapper', 'dark:bg-dark-700 w-full bg-white')
>             ->block('body', 'soft-scrollbar hidden px-4 pt-2 flex-nowrap overflow-auto lg:flex gap-2 bg-gray-950')
>             ->block('item', ' text-secondary-700 dark:text-dark-300 p-4')
>             ->block('divider', 'hidden')
>             ->block('select', 'focus:border-primary-500 focus:ring-primary-500 dark:bg-dark-700 dark:border-dark-500 w-full border-gray-200 px-4 py-3 dark:text-gray-400 lg:hidden');
> 
>         TallStackUi::personalize()
>             ->tab('items')
>             ->block('wrapper', 'inline-flex items-center gap-4 whitespace-nowrap  px-4 py-1 transition-all xl:min-w-32')
>             ->block('select', 'text-gray-950 bg-white group inline-flex cursor-pointer items-center font-medium ')
>             ->block('unselect', 'bg-primary-500 text-white hidden cursor-pointer font-medium lg:flex');
> ```
> 
> I tried adding a padding on the wrapper between sm and lg but that adds it to the whole tab, not just the header

So the solution is to create new personalizable blocks, is that correct?

**Comment by Ryuuji159** [comment]
That is correct! something like `select.wrapper` that has by default `p-2 sm:p-0` that then I can change for `p-2 lg:p-0` to comply with my design

**Comment by devajmeireles** [comment]
@Ryuuji159 ,

We won't do this now because, in the next big version, which is the summer release, we will bring a radical change to the tab that will make you need to adapt things. I will wait and only then will I analyze the status of this.
