### ISSUE TITLE
[Bug]: Uploading another other than an image results in an error

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#317]
### What Happened

using the <x-upload> component, if you try to uploading another other than an image it results in an error.

My code.
`<x-upload wire:model="fontForm.file" :preview="false"></x-upload>`

https://github.com/tallstackui/tallstackui/assets/41024720/19081019-2da1-40b8-a408-94d3059e8dfd

### How to Reproduce

Uploading anything that is not a image type on the <x-upload> component

### Laravel Version

10.33.0

### Livewire Version

3

### TallStackUI Version

1.15.2

### PHP Version

8.2.8

### Operation System

macOS

**Comment by devajmeireles** [comment]
Thanks for your report, @AndreKendeck !

I could reproduce the same issue and fix it successfully in the [v1.15.6](https://github.com/tallstackui/tallstackui/releases/tag/v1.15.6). Please, upgrade your composer dependencies and try again.

Please feel free to submit new issues whenever you need to.
