### ISSUE TITLE
[Feature Request]: Add Export to PDF, EXCEL and CSV for Table Component

### ISSUE THREAD

**Issue by focuslegon** [tasteui/tasteui#319]
### Suggestion Theme

I would like to request the addition of export functionality to the Table component in the TallStackUI project. This feature would enable users to export table data into PDF, Excel, and CSV formats, enhancing the component's utility in data presentation and reporting tasks.

### Main Benefits

The ability to export table data is crucial for users who need to share or analyze data offline or within different software environments. Adding this functionality would significantly improve data accessibility and usability, catering to a wider range of use cases such as reporting, data analysis, and record-keeping. This enhancement would make the Table component more versatile and valuable to developers building data-driven applications with the TallStackUI.

### Source of the Suggestion

Filament PHP and Amicrud

### Notes

While we are able to pass the headers with the value and labels, we can also specify if the field should be part of the export or not.

**Comment by devajmeireles** [comment]
Hey, @focuslegon ! Thanks for your feature request.

The goal of TallStackUI is not to offer such a functional table component, but I understand that we can offer a UI like a dropdown containing buttons that lead to click actions, in addition to having a way to select several records with a checkbox on the left.

I will add this to our private backlog for us to do at some point. Our current focus is the Summer Release, which will bring several new features. Until then, I'll keep this waiting.
