### ISSUE TITLE
[Feature Request]: Add thousands separator by default - Form Number

### ISSUE THREAD

**Issue by joelhmetz** [tasteui/tasteui#324]
### Suggestion Theme

Add thousands separator to input number by default.

Example: 10.000

https://tallstackui.com/docs/form/number

### Main Benefits

Today I can use Alpine JS to apply the mask, but I think that coming by default would be interesting.
Visually, it is easier to understand the displayed number.

**Comment by devajmeireles** [comment]
No plans for this, sorry. I'm planning to introduce a currency input soon.
