### ISSUE TITLE
[Bug]: pre-selected values of styled select, not possible to unselect them

### ISSUE THREAD

**Issue by fjeansson** [tasteui/tasteui#347]
### What Happened

When using a styled select outside of livewire, i use the :value attribute to pre-select some options. If I unselect one or all of the preselected options, they are still sent in the POST request as selected. The values is unselected in the GUI, but still sent to to the controller, making the component unusable outside of a livewire context.

### How to Reproduce

Standard usage

### Laravel Version

10.47.0

### Livewire Version

3.4.8

### TallStackUI Version

1.15.7

### PHP Version

8.3

### Operation System

Linux

### Notes

If there are an attribute outside of :value to select an option, this would not be an issue. But I cant find any in the source code or manual.

**Comment by devajmeireles** [comment]
Hey, @fjeansson ! Thanks for your report.

I was unable to reproduce this issue. This was my testcase:

1. Controller:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ManualController extends Controller
{
    public function index()
    {
        return view('manual', [
            'select_options' => [],
        ]);
    }

    public function update(Request $request)
    {
        $request->validate([
            'select_options' => ['required'],
        ]);

        return redirect()->back()->withInput();
    }
}

```

2. Blade:

```blade
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-white leading-tight">
            {{ __('Manual') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <x-card>
                <form action="{{ route('manual.update') }}" method="post">
                    @csrf
                    @method('patch')

                    <x-select.styled :options="['TALL', 'LIVT']"
                                        label="Select One Option"
                                        name="select_options"
                                        searchable
                                        multiple
                                        :value="old('select_options', $select_options)" />

                    <br>
        
                    <x-button type="submit">
                        Save
                    </x-button>
                </form>
            </x-card>
        </div>
    </div>
</x-app-layout>
```

With that, I was able to select or unselect values of the `select.styled` and this was submitted to the controller as expected. Please, try to upgrade your project to the latest version released now, v1.20, and try again using my code as an example. Let me know if you continue with the same issue.

**Comment by fjeansson** [comment]
Thank you for your help!

Did you have any values preselected? (e.g. anything in $select_options). The component works as expected when nothing is pre-selected. But if anything is in the value attribute when the page first loads, its not possible to deselect it (it works in the GUI but the post request still holds the value).

I can try this again with a new version and will write the results here.

**Comment by fjeansson** [comment]
It works with version 1.20, thanks!

**Comment by devajmeireles** [comment]
> It works with version 1.20, thanks!

Awesome! Feel free to open a new issue whenever necessary!
