### ISSUE TITLE
[Bug]: New upload not allowed when deleting in static mode

### ISSUE THREAD

**Issue by thiagoalgo** [tasteui/tasteui#350]
### What Happened

When I use the upload component in static mode and upload an image in the page's mount method, when I delete this image, the option to re-upload does not appear. I'm using the component outside of multiple uploads mode.

![image](https://github.com/tallstackui/tallstackui/assets/488512/9636e8ea-6df9-461a-8a38-110e85b1a4e3)

```html
<x-upload
                    label="{{ __('Logo') }}"
                    wire:model="fileLogo"
                    static
                    delete
                    delete-method="deleteLogo"
                    accept="image/png, image/jpeg, image/gif"/>
```

```php
    public function mount(): void
    {
        $this->title = __('Company');

        $fileInfo = new SplFileInfo($this->form->logo);

        $this->fileLogo = [
            [
                'name' => $fileInfo->getFilename(),
                'extension' => $fileInfo->getExtension(),
                'size' => Storage::disk('s3')->size($this->form->logo),
                'path' => $fileInfo->getPath(),
                'url' => Storage::disk('s3')->temporaryUrl($this->form->logo, now()->addMinutes(30)),
            ]
        ];

    }

    public function deleteLogo(array $content): void
    {
        $file = new TemporaryUploadedFile($this->form->logo, 's3');
        $file->delete();
        $this->fileLogo = [];
    }
```

### How to Reproduce

1. Carregar a página com um componente de upload já preenchido com uma imagem;
2. Excluir a imagem usando botão de lixeira;

### Laravel Version

10.48.2

### Livewire Version

v3.4.8

### TallStackUI Version

v1.20.0

### PHP Version

8.3.3

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @thiagoalgo !

When we opt to use the `upload` as static mode, we can't receive file upload. In this case, I suggest you wrap this into an if condition and when empty after deleting static files, show the upload without static mode instead. Something like this:

```blade
@if (count($hasUploadedFiles) > 0)
     <x-upload static .... />
@else
     <x-upload wire:model="file" ...  />
@endif
```

I think this will work successfully.

**Comment by thiagoalgo** [comment]
It worked. I just had to maintain two properties in the class $staticFileLog which is an array and is linked to the upload field when it is static and $fileLogo which receives the single uploaded file and consequently cannot be an array.

Tks, @devajmeireles
