### ISSUE TITLE
[Feature Request]:  An event to prevent decide whether to allow next step or not

### ISSUE THREAD

**Issue by focuslegon** [tasteui/tasteui#357]
### Suggestion Theme

The steps component has on-change event and on finish . We need either x-on:beforeChange or a way to stop the next step until something is true , so something like x-on:beforechange event can be added so that the step is not changes unless something is true , if the user reqiured something done in the first step 

### Main Benefits

This will help to prevent the next step if something  needs to be done in the current step

**Comment by devajmeireles** [comment]
I don't understand why we left this out. It makes perfect sense to offer before and after events like hooks. I'll handle this.

**Comment by devajmeireles** [comment]
@focuslegon ,

I kept it open for a while until we could figure out what to do about it. At first, I deduced that it was logical to have events that block navigation, but I realized that it was not necessary. You just need to use a button to perform the validation and navigate to the next step, linked to the `wireable` way of using the component. See an example:

```blade
<x-card>
    <x-step wire:model.live="step" circles>
        <x-step.items step="1" title="Dados da Conta">
            <livewire:auth.register.basic />
        </x-step.items>
        <x-step.items step="2" title="Dados de Endereço">
            <livewire:auth.register.address />
        </x-step.items>
        <x-step.items step="3" title="Termos do Serviço">
            <form id="form-submit-3" wire:submit="create">
                <x-checkbox wire:model="terms">
                    <x-slot:label>
                        Estou ciente e de acordo com os <a href="#" class="underline" x-on:click.prevent="$modalOpen('terms')">termos de uso.</a>
                    </x-slot:label>
                </x-checkbox>
            </form>
        </x-step.items>
    </x-step>
    <div>
        <x-button form="form-submit-{{ $step }}"
                  type="submit"
                  class="w-full"
                  loading="submit">
            @if ($step === 3) Criar Conta @else Avançar @endif
        </x-button>
    </div>
</x-card>
```

In this example, the child components: `register.basic` and `register.address` have validation rules that can fail, and only after validation passes an event emitted to the parent component, which receives the information and advances the step:

```php
#[On('register::basic')]
public function basic(array $basic): void
{
    $this->basic = collect($basic);

    $this->step = 2;
}

#[On('register::address')]
public function address(array $address): void
{
    $this->address = collect($address);

    $this->step = 3;
}
```

This way, each component has its validation, and only when it passes the parent component - main, does the `step` go up. It is more linked to logic than to the component itself. I'll doc this example as soon as possible.
