### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [ts-slot:header].

### ISSUE THREAD

**Issue by Cooltriks** [tasteui/tasteui#358]
### What Happened

Unable to locate a class or view for component [ts-slot:header].
 ```
<x-ts-card header="Brands">
                <x-ts-slot name="header">
                    Text 
                    <x-button wire:click="addBrand">Add</x-button>
                </x-ts-slot>
                <x-ts-table :$headers :$rows filter loading />
            </x-ts-card> 
```

### How to Reproduce

add card 

### Laravel Version

11

### Livewire Version

3

### TallStackUI Version

1.20.1

### PHP Version

8.3

### Operation System

macOS

### Notes

not working and i want to button in right side

**Comment by devajmeireles** [comment]
The slot couldn't receive the prefix because this is not part of TallStackUI features, and yes part of Blade. This is your code fixed:

```blade
<x-ts-card>
     <x-slot name="header">
         Text 
         <x-ts-button wire:click="addBrand">Add</x-button>
     </x-slot>
     <x-ts-table :$headers :$rows filter loading />
 </x-ts-card> 
```

Alternatively, you can omit the `name` of the slot:

```blade
<x-ts-card>
     <x-slot:header>
         Text 
         <x-ts-button wire:click="addBrand">Add</x-button>
     </x-slot:header>
     <x-ts-table :$headers :$rows filter loading />
 </x-ts-card> 
```

**Comment by Cooltriks** [comment]
thankyou
