### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [ts-floating].

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#359]
### What Happened

When I am using following code
        <x-ts-select.styled  name="example" class="w-full">
            <option value="1" data-icon="heroicon-s-check" selected>Option 1</option>
            <option value="2" data-icon="heroicon-s-x-circle">Option 2</option>
            <option value="3" data-icon="heroicon-s-information-circle">Option 3</option>
        </x-ts-select.styled >
        
        I am getting Unable to locate a class or view for component [ts-floating].

### How to Reproduce

after installation set prefix as ts-

### Laravel Version

PHP 8.1.6

### Livewire Version

3.4.9

### TallStackUI Version

1.20.1 

### PHP Version

8.1.6

### Operation System

macOS, Linux

**Comment by devajmeireles** [comment]
Check your `config/tallstackui.php` to verify that `floating` has not been removed or that the file is not out of date. Also, you can't set select options this way, we don't support that. The correct way is to interact with `options` to define the select options: https://tallstackui.com/docs/form/select#styled-basic-usage

**Comment by trocado** [comment]
I had this same problem. The solution was to delete the config/tallstackui.php file and run the command again:
php artisan vendor:publish --tag=tallstackui.config

**Comment by felipeschmitz** [comment]
Hi, I have the same problem, I did the procedure above and the error persists.
