### ISSUE TITLE
[Bug]: I'm not able to generate form like this

### ISSUE THREAD

**Issue by Cooltriks** [tasteui/tasteui#360]
### What Happened

<img width="657" alt="Screenshot 2024-03-17 at 9 35 36 PM" src="https://github.com/tallstackui/tallstackui/assets/48170385/8dd05a7e-42fc-4c7a-9611-1a4764988450">

### How to Reproduce

i wnat to genrate ui same this

### Laravel Version

11

### Livewire Version

3

### TallStackUI Version

1.20.1

### PHP Version

8.3

### Operation System

macOS

**Comment by Cooltriks** [comment]
i,m not geting example code

**Comment by devajmeireles** [comment]
Use the example of our docs: https://github.com/tallstackui/website/blob/1.x/resources/views/livewire/welcome/form.blade.php
