### ISSUE TITLE
[Bug]: x-date not working with wire:change

### ISSUE THREAD

**Issue by CPrimbee** [tasteui/tasteui#372]
### What Happened

x-date component doesn't work appropriately with wire:change. After I've tried use x-on:select but not called function.

### How to Reproduce

In a blade page add x-date component.
`
<x-date label="{{__('Begin')}}" wire:model.live="form.start_at" wire:change="changeEndsAt" />
`
or
`
<x-date label="{{__('Begin')}}" wire:model.live="form.start_at" x-on:select="$wire.changeEndsAt()" />
`

In component's controller 
`
public function changeEndsAt(): void
{
    $this->form->fill([
        'ends_at' => date_add(
            $this->form->start_at,
            date_interval_create_from_date_string(
                $this->form->contracted_period . ' months'
            )
        )
    ]);
}
`

### Laravel Version

11.0.5

### Livewire Version

3.4.8

### TallStackUI Version

1.20.2

### PHP Version

8.2.13

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @CPrimbee !

We just released v1.21 with `wire:change` support for `date` and `time` components. Please, upgrade your project dependencies and try it again. 

Please feel free to open a new issue whenever you need to.
