### ISSUE TITLE
[Bug]:  runtime icon rendering not working

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#383]
### What Happened

<?php $icontext =  '<x-phosphor-'. $vertical->icon . ' class="w-12 h-12 text-sky-500" />' ?>
 icontext {{  $icontext }}
  {!!  $icontext !!} 

### How to Reproduce

open any blade file put up above code  replace $vertical->icon  with any icon such as user

### Laravel Version

10.48.3 

### Livewire Version

3.4.9

### TallStackUI Version

1.20.1

### PHP Version

8.1.6

### Operation System

macOS

**Comment by abhideshpande** [comment]
You need to chec "<?php $icontext =  '<x-phosphor-'. $vertical->icon . ' class="w-12 h-12 text-sky-500" />' ?>"

**Comment by abhideshpande** [comment]
`<?php $icontext =  '<x-phosphor-'. $vertical->icon . ' class="w-12 h-12 text-sky-500" />' ?>`. this is code in blade

**Comment by devajmeireles** [comment]
Hey, @abhideshpande ! 

I think you're making the wrong way to use dynamic icons in your project. The correct approach is:

```blade
<x-icon :icon="$vertical->icon" class="w-12 h-12 text-sky-500" />
```

---

If you're passing the `$icon` as a component "prop", then you can do that:

```blade
@props(['icon'])

<x-icon :$icon class="w-12 h-12 text-sky-500" />
```
