### ISSUE TITLE
[Bug]:  Error when using x-seletc.styled with API

### ISSUE THREAD

**Issue by jeffersongrassine** [tasteui/tasteui#388]
### What Happened

I'm getting: "Only arrays and Traversables can be unpacked"

Blade:
 <x-select.styled :request="[url' => route('api.especialistas'),
                        'method' => 'get',
                    ]" select="label:name|value:id" />
                        
Here is my call on the route:
Route::get('/specialistas', function (Request $request) {
    // getting initial selected values
    $selected = json_decode($request->get('selected', ''), true);
 
    return Expert::query()
        // searching when type in the select input
        ->when(
            $search = $request->get('search'),
            fn ($query) => $query->where('name', 'like', "%{$search}%")
        )
        ->when(!$search && $selected, function ($query) use ($selected) {
            // selecting the initial selected values
            $query->whereIn('id', $selected)
                // or selecting the other users ordered by creation date
                ->orWhere(function ($query) use ($selected) {
                    $query->whereNotIn('id', $selected)
                        ->orderBy('created_at');
                });
        })
        ->limit(10)
        ->get()
        // mapping to the expected format
        ->map(fn (Expert $user) => $user->only('id', 'name'));
})->name('api.especialistas');

In laravel 10.x it worked fine, what can I do wrong?

Help!

### How to Reproduce

This error occurs using Laravel 11
![erro_tallStackUI](https://github.com/tallstackui/tallstackui/assets/76718247/c8a2a312-3f94-411c-b7d8-6b82e594bc14)

### Laravel Version

11.1.1

### Livewire Version

^3.4

### TallStackUI Version

1.21

### PHP Version

8.2

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @jeffersongrassine ! I have no idea what would cause this issue. I was unable to reproduce this issue. If the same code works in Laravel 10 and not 11, it could be a Laravel bug. Could you share the repository with me so I can check if it is a TallStackUI error?

**Comment by devajmeireles** [comment]
Closed by inactivity. If you are interested in moving forward, send the link to a repository where the problem occurs.
