### ISSUE TITLE
[Feature Request]: Phosphor Icons : Support Fill icon style

### ISSUE THREAD

**Issue by MGeurts** [tasteui/tasteui#395]
### Suggestion Theme

The icons stack [Phosphor Icons](https://phosphoricons.com/?q=%22%22&weight=%22fill%22) now supports a **Fill** style.

Please adapt this style in TallStackUI Icons.
Or if already done, then adjust the documentation at [https://tallstackui.com/docs/ui/icon](https://tallstackui.com/docs/ui/icon).

Thanks.

### Main Benefits

TallStackUI Icons 100% compatible with Phospor Icons.

### Source of the Suggestion

https://phosphoricons.com/?q=%22%22&weight=%22fill%22

**Comment by devajmeireles** [comment]
The "fill" style of Phosphoricon does not support the color properties of TailwindCSS through the "class" attribute, so we leave it aside. I will analyze whether it is worth adding or not. The colors in this style are applied with the "fill" property, as well as the size, which does not accept `w-4 h-4`, but rather the "width" and "height" attributes.
