### ISSUE TITLE
[Bug]: No working prefix

### ISSUE THREAD

**Issue by pablomadariaga** [tasteui/tasteui#396]
### What Happened

![image](https://github.com/tallstackui/tallstackui/assets/69119357/f95b4c3a-7bc4-4da6-80cc-cec3b893ba94)
![image](https://github.com/tallstackui/tallstackui/assets/69119357/fa54ae9d-84d9-42d1-9d4b-22e89743a364)
![image](https://github.com/tallstackui/tallstackui/assets/69119357/f2f4e7b4-6705-41da-a97a-1467a0530bd1)
![image](https://github.com/tallstackui/tallstackui/assets/69119357/8ec0a698-6461-4acc-868d-2bee073a1843)

### How to Reproduce

![image](https://github.com/tallstackui/tallstackui/assets/69119357/8fa07eaa-c754-4b8a-a175-4e727cdf76fb)

### Laravel Version

11.2

### Livewire Version

3.4.10

### TallStackUI Version

1.22.1

### PHP Version

8.2.15

### Operation System

macOS, Windows, Linux

**Comment by pablomadariaga** [comment]
Oh sorry, I missed the script hahaha, thanks for tallstackui <3

**Comment by devajmeireles** [comment]
You're welcome. Closed.
