### ISSUE TITLE
[Bug]: The x-select.styled breaks

### ISSUE THREAD

**Issue by pablomadariaga** [tasteui/tasteui#400]
### What Happened

The x-select.styled breaks when we use a modal with a livewire action after reopening it.

### How to Reproduce

livewire-component

![image](https://github.com/tallstackui/tallstackui/assets/69119357/c9ea7c9f-c87a-496e-85fb-32b2864ecb35)

### Laravel Version

11.2

### Livewire Version

3.4.10

### TallStackUI Version

1.22.1

### PHP Version

8.2.15

### Operation System

Windows

### Notes

https://github.com/tallstackui/tallstackui/assets/69119357/8eecc7a6-ffa6-4485-bb82-8e9c2b7982ae

**Comment by devajmeireles** [comment]
Working on it.

**Comment by pablomadariaga** [comment]
> Working on it.

Excellent

**Comment by devajmeireles** [comment]
> Also in the component loading the blur property in the config file is not being taken, in the video you can see, I think it should be the same as the backdrop of the modal. ![Captura de pantalla 2024-04-05 102329](https://private-user-images.githubusercontent.com/69119357/320053473-943924d6-1c2c-4268-920d-de507211adae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjg1NTQsIm5iZiI6MTcxMjM2ODI1NCwicGF0aCI6Ii82OTExOTM1Ny8zMjAwNTM0NzMtOTQzOTI0ZDYtMWMyYy00MjY4LTkyMGQtZGU1MDcyMTFhZGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxNTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMWE3NWJlNTViZWZiOTI3YTQ4ZGE3NmYyZWViYzEwMTU5MDViNTZjZTliNTI3ZTk4NThiMDg2ZTgxZDA5YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AkFbUMPjapmhJjk2K7vwzPDRnCgXy0ooQvnM7C5Ez-k)
> 
> Modal: ![image](https://private-user-images.githubusercontent.com/69119357/320054739-ae0c08b0-b222-4be2-aea6-538333bd5a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjg1NTQsIm5iZiI6MTcxMjM2ODI1NCwicGF0aCI6Ii82OTExOTM1Ny8zMjAwNTQ3MzktYWUwYzA4YjAtYjIyMi00YmUyLWFlYTYtNTM4MzMzYmQ1YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxNTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZDcyODY1ZjhhMGQ0ZmNlMmNhMDEyZDA4YTVlMWE4MTA1ZjU1YTQ5MmEzY2IzZTRmN2U0MWU3NDQ2NDU2NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df3xsFB26xQyLn4tn1wlIOXhZKARMKSQ1w6K2js6lIk)
> 
> Loading: ![image](https://private-user-images.githubusercontent.com/69119357/320054924-a2559193-bdb7-4cc4-b7c7-7cdf936c3fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNjg1NTQsIm5iZiI6MTcxMjM2ODI1NCwicGF0aCI6Ii82OTExOTM1Ny8zMjAwNTQ5MjQtYTI1NTkxOTMtYmRiNy00Y2M0LWI3YzctN2NkZjkzNmMzZmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAxNTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYjRkYjBhYzYwZWE1NjZkMjIzZTBlZTJjNDVjZDU4ZDFiNDQ5ZjEyMzRjYTMyODMwMjI0YTg2MjAyZjMzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oZqr9eudvTT-PgHyrSKbNygGKPls3PAIySo_DqU3aA)

Could you separate this into a new issue, please? Thanks.

**Comment by pablomadariaga** [comment]
> Could you separate this into a new issue, please? Thanks.

That's it, it's already separated... How are you going with the select issue? Do you need help?

**Comment by devajmeireles** [comment]
Hey, @pablomadariaga ! 

I was unable to reproduce this issue. Could you check the browser console log for errors when the problem occurs, please? Also, I noticed that you are using an `x-on:click` at the same time as `wire:click` happens. This is not the reason for the problem, but you can give up `x-on:click` to interact with the modal with Wireable mode: https://tallstackui.com/docs/ui/modal#wireable

**Comment by devajmeireles** [comment]
> Hey, @pablomadariaga !
> 
> I was unable to reproduce this issue. Could you check the browser console log for errors when the problem occurs, please? Also, I noticed that you are using an `x-on:click` at the same time as `wire:click` happens. This is not the reason for the problem, but you can give up `x-on:click` to interact with the modal with Wireable mode: https://tallstackui.com/docs/ui/modal#wireable

Another way to help us solve this problem is to provide a demo repository where the problem is happening so that we can reproduce the issue and fix it.

**Comment by pablomadariaga** [comment]
> > Hey, @pablomadariaga !
> > I was unable to reproduce this issue. Could you check the browser console log for errors when the problem occurs, please? Also, I noticed that you are using an `x-on:click` at the same time as `wire:click` happens. This is not the reason for the problem, but you can give up `x-on:click` to interact with the modal with Wireable mode: https://tallstackui.com/docs/ui/modal#wireable
> 
> Another way to help us solve this problem is to provide a demo repository where the problem is happening so that we can reproduce the issue and fix it.

Ok, @devajmeireles  I immediately provide the repository with the demo that replicates it, I just realized that the modal has nothing to do with it

**Comment by devajmeireles** [comment]
Any updates, @pablomadariaga ?

**Comment by devajmeireles** [comment]
Closed due inactivity. Please, reply with a repository  where the issue is reproducible, if you want to help us to reproduce the issue to solve this.
