### ISSUE TITLE
[Feature Request]: Vertical scroll for Modal Dialog

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#401]
### What Happened

<x-ts-modal title="TallStackUi" size="2xl">
    TallStackUi
</x-ts-modal>

Want to specify height of the modal so that contents can be scrolled thru.
Also can set the co-ordinates such as below a button of navbar

### How to Reproduce

Use an existing modal popup

### Laravel Version

10.48.3

### Livewire Version

3.4.9

### TallStackUI Version

1.20.1

### PHP Version

8.1.6

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @abhideshpande ! First of all, this is not a bug, but rather a feature request. We don't have any plans for this at the moment, but I'll mark this as a suggestion so I can check it out as soon as I have free time.

**Comment by abhideshpande** [comment]
Thanks a lkot @devajmeireles  !!  
your work is really amazing and inspiring !!!!
