### ISSUE TITLE
[Bug]: Loading the blur property in the config file is not being taken

### ISSUE THREAD

**Issue by pablomadariaga** [tasteui/tasteui#402]
### What Happened

In the component loading the blur property in the config file is not being taken, in the video you can see, I think it should be the same as the backdrop of the modal.

### How to Reproduce

![image](https://github.com/tallstackui/tallstackui/assets/69119357/69a6ba8c-87e3-4430-9f0b-c2cb92eaa03f)

### Laravel Version

11.2

### Livewire Version

3.4.10

### TallStackUI Version

1.22.1

### PHP Version

8.2.15

### Operation System

Windows

### Notes

Modal:
![image](https://github.com/tallstackui/tallstackui/assets/69119357/3c9b722c-be5f-48c2-b3af-b44767bb48e8)
Loading:
![image](https://github.com/tallstackui/tallstackui/assets/69119357/11ef4d27-d13d-40b8-a04a-802cf82fec51)

**Comment by devajmeireles** [comment]
Thanks for reporting. Fixed on our new release: https://github.com/tallstackui/tallstackui/releases/tag/v1.22.2
