### ISSUE TITLE
[Bug]: Undefined array key 0

### ISSUE THREAD

**Issue by kamilkozak** [tasteui/tasteui#414]
### What Happened

When I use the` <x-select.native />` component I get the error "_Undefined array key 0_". The error occurs when the ":options" attribute is an empty array. In my case, it breaks the tests when the database is empty.
### How to Reproduce

Install a fresh Laravel app, install TallStackUI, add a<x-select.native /> to a Livewire component, pass empty "options" attribute, visit the page

### Laravel Version

10.48.5

### Livewire Version

3.4.10

### TallStackUI Version

1.22.3

### PHP Version

8.3.3

### Operation System

macOS, Linux

**Comment by devajmeireles** [comment]
Fixed. Waiting for the next release. Thanks for reporting, @kamilkozak !

**Comment by devajmeireles** [comment]
The fix was published in the latest release: v1.23.0. Please, upgrade your project.
