### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [ts-floating].

### ISSUE THREAD

**Issue by davidbenn** [tasteui/tasteui#415]
### What Happened

When I use the <x-ts-password :rules="['min:8', 'symbols', 'numbers', 'mixed']" /> component, I receive the exception "Unable to locate a class or view for component [ts-floating]." The error occurs when the ":rules" attribute is added to the input. It only works when the attribute is removed.

### How to Reproduce

Install a fresh Laravel app, install TallStackUI, and add a <x-ts-password :rules="['min:8', 'symbols', 'numbers', 'mixed']" to a Livewire component, visit the page

### Laravel Version

11.3.1

### Livewire Version

3.4.10

### TallStackUI Version

1.22.3

### PHP Version

8.3.4

### Operation System

Linux

**Comment by devajmeireles** [comment]
The reason for this issue is related to the fact you've published the `config/tallstackui.php` and we've introduced new components that are not listed in your current config file. You must upgrade your config file to solve this issue.
