### ISSUE TITLE
[Bug]: Undefined array key 0

### ISSUE THREAD

**Issue by kamilkozak** [tasteui/tasteui#426]
### What Happened

When I use the <x-select.native /> component I get the error "Undefined array key 0". The error occurs when the ":options" attribute is an empty array. In my case, it breaks the tests when the database is empty.

I reported the bug earlier in issue #414. In v1.24.0 the problem still exists.

### How to Reproduce

Install a fresh Laravel app, install TallStackUI, add a<x-select.native /> to a Livewire component, pass empty "options" attribute, visit the page

### Laravel Version

10.48.7

### Livewire Version

3.4.10

### TallStackUI Version

1.24.0

### PHP Version

8.3.3

### Operation System

macOS, Linux

**Comment by devajmeireles** [comment]
@kamilkozak , fresh Laravel 11 app with Laravel Breeze results in no errors:

![CleanShot 2024-04-16 at 10 22 50](https://github.com/tallstackui/tallstackui/assets/60591772/8752325b-d941-4d15-88b5-b9aa7a9cd104)

**Comment by kamilkozak** [comment]
@devajmeireles Thank you for the quick reply. I will investigate and come back with an answer.

**Comment by kamilkozak** [comment]
@devajmeireles Instead of an array, my options were a Laravel collection. Everything worked fine when the collection was not empty. However, when it was empty, an error occurred.

**Comment by devajmeireles** [comment]
Solved, please upgrade your project dependencies by running `composer update` to get our latest tag, v1.24.1
