### ISSUE TITLE
[Feature Request]: Layout and Menu Components

### ISSUE THREAD

**Issue by cord** [tasteui/tasteui#429]
### Suggestion Theme

Add components for App-Layout and Menu

### Main Benefits

Would be a quickstart for any app and easier to migrate from mary-ui

### Notes

compare with:

https://mary-ui.com/docs/layout
https://mary-ui.com/docs/components/menu

**Comment by devajmeireles** [comment]
Thanks for your suggestion, @cord .

After thinking about this for a long time, we are not going to move forward with this now. For now, TallStackUI will not offer a ready-made layout, perhaps only in V2, our next major version.
