### ISSUE TITLE
[Bug]: Only arrays and Traversables can be unpacked

### ISSUE THREAD

**Issue by sektonic** [tasteui/tasteui#431]
### What Happened

When I use  <x-select.styled :options="[1, 2, 3]" /> I get an error "Only arrays and Traversables can be unpacked", but if I use <x-select.native :options="[1, 2, 3]" /> no error found

### How to Reproduce

Install a fresh laravel with breeze then install TallStackUI

### Laravel Version

11.2.0

### Livewire Version

3.4.9

### TallStackUI Version

1.24.1

### PHP Version

8.2.8

### Operation System

Windows

**Comment by devajmeireles** [comment]
Thanks for reporting, @sektonic .

Are you sure about it? I was unable to reproduce this issue. 

![CleanShot 2024-04-18 at 21 47 54](https://github.com/tallstackui/tallstackui/assets/60591772/766bf1a2-1720-40c4-922f-26d59f2623b7)

**Comment by sektonic** [comment]
yes Iam sure

![Screenshot 2024-04-19 094129](https://github.com/tallstackui/tallstackui/assets/10237096/b029d615-1197-4164-8262-2f6de8380eb3)

![Screenshot 2024-04-19 094451](https://github.com/tallstackui/tallstackui/assets/10237096/8a22a8a7-364f-4915-91b4-e517f8d376b5)

**Comment by devajmeireles** [comment]
I suspect you're running an old version of TallStackUI. 

Could you please, run `composer update && php artisan optimize:clear` and try again?

**Comment by sektonic** [comment]
I've solved this problem because my local language is "id", so I run 
`php artisan vendor:publish --tag=tallstackui.lang`
then add new folder lang/vendor/tallstack-ui/id
@devajmeireles thanks for your response
