### ISSUE TITLE
[Feature Request]: can we have text editor in textarea (Quill, CKEditor, TinyMCE, etc)

### ISSUE THREAD

**Issue by wellyrm** [tasteui/tasteui#433]
### Suggestion Theme

textarea input

### Main Benefits

If possible, i want to request a text editor in textarea for TallstackUI. This feature will be very useful for users who need to write or edit long text in forms or web applications.

Especially if we can determine the toolbar mode, ex:compact, normal, or full

No preferred plugins, just accept anything TallstackUI team decision.

Thank you in advance guys...

**Comment by wilianmaique** [comment]
It's really good, maybe add a markdown editor and also add the function to transform into html to be saved in the database etc. There are several good editors to use, but one from tallstackui itself would be interesting

**Comment by devajmeireles** [comment]
Planned for v2 only. Closing for now.

**Comment by devajmeireles** [comment]
@wellyrm https://tallstackui.com/docs/ui/editor

**Comment by wellyrm** [comment]
Superb... Awesome update. So, we have Tailwindcss 4, Livewire 4, and now, TallstackUI 4.

**Comment by MacLiroy** [comment]
Thank you for the great editor! Do you think it would be possible to add text and background color options to the toolbar? Just a few basic colors would be awesome.
