### ISSUE TITLE
[Bug]: Property [$] not found on component when clicking on the "x" of select

### ISSUE THREAD

**Issue by kachkolasa** [tasteui/tasteui#434]
### What Happened

I'm using the select.styled with the wire:model.live and when I select something it works perfectly but when I click on the "x" icon to remove the selection, it throws the "Property [$] not found on component". Please guide

### How to Reproduce

Create a component with any property and then use that property in a query then select an option from the select menu that is connected to the property, then click on the "x" icon on the select. You should be getting that error after that.

### Laravel Version

11.4.0

### Livewire Version

3.4.10

### TallStackUI Version

1.24.1

### PHP Version

8.2

### Operation System

Windows

**Comment by kachkolasa** [comment]
Actually this only happens if you use the new data type. 

For example,
public $brand = ''; // This will work
public string $brand = ''; // The issue is only with this.

**Comment by devajmeireles** [comment]
Unreproducible or not related to TSUI:
![CleanShot 2024-04-22 at 00 19 11](https://github.com/tallstackui/tallstackui/assets/60591772/5443af5c-ffc3-43de-9a0d-9aa438fb7f78)

Can you provide a repository with the code that reproduces this issue? We can do an in-depth investigation.

**Comment by kachkolasa** [comment]
Sure man, I see why you are not getting the error. Let me create a repo in a few hours.

**Comment by kachkolasa** [comment]
You can try to use it in a query with the ->when() method. 

Something like:
MyModel::query()->when($this->brand, fn);

I will create the Repo in a few hours anyway but it's worth a try.

**Comment by devajmeireles** [comment]
> You can try to use it in a query with the ->when() method.
> 
> Something like: MyModel::query()->when($this->brand, fn);
> 
> I will create the Repo in a few hours anyway but it's worth a try.

If you want to use the `$brand` in a query, like a filter, the correct to do is:

1. Adapt the `$brand` property to deal with null values: `public ?string $brand = null`;
2. Use `when`, as in your example, to only apply the filter when `$brand` is defined.
3. Use `unless` in the query, to deal with the inverse (null state of `$brand`).

**Comment by devajmeireles** [comment]
In the end, I don't think this is an issue with `select.styled`.

**Comment by kachkolasa** [comment]
In that case, the error log is very misleading. I will test it, but I think you are right

**Comment by kachkolasa** [comment]
Okay it worked! 
So TallStackUI changes it to null when clicked on the "x"? Should not it consider the data type?

**Comment by devajmeireles** [comment]
> Okay it worked! So TallStackUI changes it to null when clicked on the "x"? Should not it consider the data type?

No, the clean-up effect nullifies the value. 

I'll close this issue and in the next doc update, I'll insert this as a note.
