### ISSUE TITLE
[Bug]: The error component uses an x-circle icon that is not available in all icon stacks.

### ISSUE THREAD

**Issue by MGeurts** [tasteui/tasteui#447]
### What Happened

While using the **Tabler Icon** stack, whenever the use of the error component is triggered by validation errors, the following error is shown:

`Unable to locate a class or view for component [tallstack-ui::icon.tablericons.default.x-circle].`

### How to Reproduce

Install a fresh Lavarel App
Install TallStackUI
Publish TallStackUI config and configure Tabler Icons
Trigger validation error in a form

### Sample Repository

https://genealogy.kreaweb.be/

### Laravel Version

11.x

### Livewire Version

3.x

### TallStackUI Version

1.24.2

### PHP Version

8.3.6

### Operation System

Windows

**Comment by MGeurts** [comment]
There is no possibility to workaround this by personalization.

**Comment by MGeurts** [comment]
There seems to be no way to workaround this by using personalisation.

**Comment by MGeurts** [comment]
Aha. We can solve the problem by using the icon attribute on the error component.

`<x-ts-errors icon="user-plus" class="mb-2" close />`

Maybe this should be mentioned in the documentation.

**Comment by MGeurts** [comment]
Above solution solved the problem on local server but caused presentation (tailwind css) problems on the production server.
I guess, overriding the icon property is not the way to go.

Maybe the developer(s) can look into this?

**Comment by devajmeireles** [comment]
Fixed. Thanks. Waiting for the next release.

**Comment by devajmeireles** [comment]
@MGeurts , the fix for this was published on our today's release: v1.25.0.

Closed.
