### ISSUE TITLE
[Bug]: Tab title should allow an identifier instead of full text

### ISSUE THREAD

**Issue by mydnic** [tasteui/tasteui#453]
### What Happened

I'm using the tab component and I need to have this text as the tab title : "Données d'identification".

But as of now, you can't use quotes in the text as there's an error : 

```
Alpine Expression Error: Unexpected identifier 'identification'

Expression: "selected === 'Données d'identification'"
```

### How to Reproduce

```
<x-tab selected="Données d'identification">
        <x-tab.items tab="Données d'identification">
            Tab 1
        </x-tab.items>
        <x-tab.items tab="Tab 2">
            Tab 2
        </x-tab.items>
        <x-tab.items tab="Tab 3">
            Tab 3
        </x-tab.items>
    </x-tab>
```

### Laravel Version

10.48

### Livewire Version

3.4

### TallStackUI Version

1.25

### PHP Version

8.1

### Operation System

macOS

### Notes

It should be possible to either use a slot or pass the tab title in another parameter. 

One solution : 

```
<x-tab selected="identification_tab">
        <x-tab.items tab="identification_tab">
            <x-slot:title>Données d'identification</x-slot>
            
            Tab 3
        </x-tab.items>
        <x-tab.items tab="Tab 2">
            Tab 2
        </x-tab.items>
        <x-tab.items tab="Tab 3">
            Tab 3
        </x-tab.items>
    </x-tab>
```

by using an "id" for the tab param, then you're sure to avoid any similar issue 

Also it gives more freedom to the user (eg: use an image in the tab title)

**Comment by devajmeireles** [comment]
Thanks for reporting. Fixed now in v1.25.2 release. Please, upgrade your project:

```shell
composer update && php artisan optimize:clear
```
