### ISSUE TITLE
[Bug]: x-ts-select.styled  api route in component syntax error, unexpected token "<"

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#455]
### What Happened

I am creating a generic component to have api.route but I am getting error

@props(['name' => '', 'hint' => '' , 'id' => '', 'wireModel' => '' , 'label' => '' , 'routeName' => ''] )

<x-ts-select.styled label="{{ $label }}"
                 :request="route({{ $routeName }})"
				 select="label:name|value:value"
				 wire:model.defer={{$wireModel}}
				 />
				 
syntax error, unexpected token "<"

### How to Reproduce

add a component 

@props(['name' => '', 'hint' => '' , 'id' => '', 'wireModel' => '' , 'label' => '' , 'routeName' => ''] )

<x-ts-select.styled label="{{ $label }}"
                 :request="route({{ $routeName }})"
				 select="label:name|value:value"
				 wire:model.defer={{$wireModel}}
				 />

### Laravel Version

10.48.9

### Livewire Version

3.4.11

### TallStackUI Version

1.24.5

### PHP Version

PHP 8.3.6 (cli) (built: Apr 10 2024 14:21:20) (NTS)

### Operation System

macOS

**Comment by abhideshpande** [comment]
I need to pass route name to this component

**Comment by devajmeireles** [comment]
The problem is not linked to TallStackUI, you created the component with the wrong codes. With this code, it will work:

```blade
@props(['name' => '', 'hint' => '', 'id' => '', 'wireModel' => '', 'label' => '', 'routeName' => ''])

<x-ts-select.styled label="{{ $label }}"
                    :request="route($routeName)"
                    select="label:name|value:value"
                    wire:model.defer="{{ $wireModel }}" />
```

**Comment by abhideshpande** [comment]
Thanks a lot @devajmeireles  , This really worked.
