### ISSUE TITLE
[Feature Request]: Vertical Tabs

### ISSUE THREAD

**Issue by mydnic** [tasteui/tasteui#458]
### Suggestion Theme

Tabs, but vertical

### Main Benefits

When you have too much tabs (like a form with lots of steps), it can be useful to display them vertically instead of horizontally

https://flowbite.com/docs/components/tabs/#vertical-tabs

https://tailwindui.com/components/application-ui/navigation/vertical-navigation

### Notes

The Steps component could benefit from the same thing

**Comment by devajmeireles** [comment]
Thanks! No plans for this right now. I'll tag it as a suggestion, so I can take a look into this during the build of our next major version, v2.
