### ISSUE TITLE
[Feature Request]: Allow use of html in table component

### ISSUE THREAD

**Issue by MGeurts** [tasteui/tasteui#460]
### Suggestion Theme

Table

### Main Benefits

Allowing html in the table component would make it possible to use icons (like for instance a checkmark) in **table cells**.

### Notes

Thanks.

**Comment by devajmeireles** [comment]
Where on the table?

**Comment by MGeurts** [comment]
In the table cells...

**Comment by devajmeireles** [comment]
I don't think I understand yet. I use HTML inside the table without a problem:

![CleanShot 2024-05-15 at 08 29 41](https://github.com/tallstackui/tallstackui/assets/60591772/cae2a9a7-09f4-47b2-a19b-42e26b6ae0d9)

**Comment by MGeurts** [comment]
Ok. That works. I was not familiar with that option.
I'm sorry. Thank you.
