### ISSUE TITLE
[Bug]: Problem when upload files with Google icons

### ISSUE THREAD

**Issue by thiagoalgo** [tasteui/tasteui#464]
### What Happened

When i changed my icon configuration to this below:

```php
'icons' => [
        'type' => env('TALLSTACKUI_ICON_TYPE', 'google'),
        'style' => env('TALLSTACKUI_ICON_STYLE', 'default'),
        'flush' => true,
],
```

And tried upload a PDF file, i recieved this error:

![Untitled](https://github.com/tallstackui/tallstackui/assets/488512/a4e46a2f-35c3-4836-869a-a1fe807b9556)

For images the thumbnail is correctly generated.

### How to Reproduce

Change configuration of the icons in config/tallstackui.php file to:

```php
'icons' => [
        'type' => env('TALLSTACKUI_ICON_TYPE', 'google'),
        'style' => env('TALLSTACKUI_ICON_STYLE', 'default'),
        'flush' => true,
],
```

And run:

```shell
php artisan tallstackui:setup-icon
```

Create livewire component with <x-upload> component and try upload PDF file.

### Laravel Version

v11.7.0

### Livewire Version

v3.4.12

### TallStackUI Version

v1.25.2

### PHP Version

8.3.6

### Operation System

Linux

**Comment by devajmeireles** [comment]
Thanks for reporting, @thiagoalgo !

Fixed now in our new release. Upgrade your TSUI and test it again.
