### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by R00TR41Z** [tasteui/tasteui#469]
### Suggestion Theme

# Suggestion for pin component
### Main Benefits

-  Ease of checking the pin if the user finishes typing the pin

### Source of the Suggestion

https://mary-ui.com/docs/components/pin

**Comment by joelhmetz** [comment]
Here is the component link: https://tallstackui.com/docs/form/pin

**Comment by devajmeireles** [comment]
Thanks, @R00TR41Z .

We release this feature today in v1.27.0: https://tallstackui.com/docs/form/pin#events
