### ISSUE TITLE
[Bug]: Missing table styles after updating to v1.26.1

### ISSUE THREAD

**Issue by kamilkozak** [tasteui/tasteui#472]
### What Happened

The appearance of the <x-table /> component has changed after updating from v1.25.2 to v1.26.1. Missing border and shadow.
v1.25.2
![image](https://github.com/tallstackui/tallstackui/assets/12345872/27660975-9326-43a5-ae8c-8af5ada2f276)
v1.26.1
![image](https://github.com/tallstackui/tallstackui/assets/12345872/3057b792-7700-4c71-bdb0-4cfc80f76b66)

### How to Reproduce

Install a fresh Laravel app, install TallStackUI, add a <x-table /> to a Livewire component, visit the page

### Laravel Version

11.7.0

### Livewire Version

3.4.12

### TallStackUI Version

1.26.1

### PHP Version

8.3.7

### Operation System

macOS

**Comment by devajmeireles** [comment]
I've noticed this too. Fixed on https://github.com/tallstackui/tallstackui/pull/467. Ships tomorrow!

**Comment by devajmeireles** [comment]
v1.27.0 released with the fix for this. Please, upgrade your project.

https://github.com/tallstackui/tallstackui/releases/tag/v1.27.0
