### ISSUE TITLE
[Bug]: Some button actions don't work in x-slot:footer

### ISSUE THREAD

**Issue by buenojosias** [tasteui/tasteui#482]
### What Happened

When I work with x-ts-card or x-ts-modal, buttons like submit or x-on:click="close" only work outside the x-slot:footer.
When placed inside x-slot:footer they stop working, making it necessary to change to wire:click="myMethod" and x-on:click="$modalClose('my-modal')", respectively.

### How to Reproduce

![Captura de tela 2024-05-25 000325](https://github.com/tallstackui/tallstackui/assets/66849846/cd487c49-c85d-42b7-9500-1e1bb8f50c02)
<x-ts-button text="Cancelar" x-on:click="close" />
</x-slot>

### Laravel Version

11.8

### Livewire Version

3.4

### TallStackUI Version

1.27

### PHP Version

8.1

### Operation System

Windows

**Comment by devajmeireles** [comment]
Hey, @buenojosias! Thanks for reporting. This is not a bug. Some slots are outside the main divs, so in this case, the best thing to do is to submit the form using a unique ID:

```blade
<x-modal wire title="Create Lead">
    <form id="form-lead-create" wire:submit="create" class="space-y-2">
        <div>
            <x-input label="Name"
                     x-ref="input"
                     wire:model="contact.name"
                     required />
        </div>
        <div>
            <x-input label="Phone"
                     wire:model="phone"
                     required/>
        </div>
    </form>
    <x-slot:footer>
        <x-button type="submit"
                  form="form-lead-create"
                  loading="create">
            Salvar
        </x-button>
    </x-slot:footer>
</x-modal>
```

1. In the form, add the `id`
2. In the button, add the `form` where the value should be the form id.

**Comment by buenojosias** [comment]
Thanks for answering.
The submit has been resolved. Only x-on:click="close" still doesn't work. Do you recommend using x-on:click="$modalClose('address-modal')" or is there another way?

**Comment by devajmeireles** [comment]
> Thanks for answering. The submit has been resolved. Only x-on:click="close" still doesn't work. Do you recommend using x-on:click="$modalClose('address-modal')" or is there another way?

Use whatever you want according to your strategy. Our modal can be open/close with AlpineJS or Livrwire, you just need to choose one of them. Make sure to read the docs!
