### ISSUE TITLE
[Feature Request]: RTL support

### ISSUE THREAD

**Issue by ibrahem-kamal** [tasteui/tasteui#487]
### Suggestion Theme

is there any RTL support ? i didn't find any at the docs and when i tried to just dir:rtl the input margin and padding are messed up . 

### Main Benefits

support wider variants of projects

**Comment by devajmeireles** [comment]
Hey, @ibrahem-kamal ! Thanks for your request.

Unfortunately, we do not have plans to add support to the RLS in our current major version, maybe in the future when we'll have the V2.
