### ISSUE TITLE
[Bug]: textarea

### ISSUE THREAD

**Issue by joelhmetz** [tasteui/tasteui#492]
### What Happened

When I try to leave the default 5 lines in the textarea, in the last update it was only one.

![Captura de tela 2024-06-05 222544](https://github.com/tallstackui/tallstackui/assets/8234440/9e4f675b-151c-4b5f-b555-f02c28b72254)

### How to Reproduce

`<x-textarea wire:model="testimony" label="Depoimento *" maxlength="240" count rows="5" resize-auto />`

### Laravel Version

11.10.0

### Livewire Version

3.4.9

### TallStackUI Version

1.28.0

### PHP Version

8.2

### Operation System

Windows

**Comment by devajmeireles** [comment]
When you set `resize-auto` the size of the text area will be set according to the size of the value. I'll try to adapt this to resize according to line size but automatically expand when typed.

**Comment by joelhmetz** [comment]
I removed the dimension, even without it it doesn't start with the expected number of lines.

`<x-textarea wire:model="testimony" label="Depoimento *" rows="5" />`

![Captura de tela 2024-06-06 150149](https://github.com/tallstackui/tallstackui/assets/8234440/227b7555-f7a3-4fb6-a660-264879c6083d)

I only noticed this new version, it was something that occurred during the update.

**Comment by devajmeireles** [comment]
Thinking about it, the correct thing to do is to block the use of `rows` together with `resize-auto` because we won't be able to make the textarea be displayed with the initialized rows and only do the resize-auto when reaching the number of rows.

**Comment by devajmeireles** [comment]
@joelhmetz https://github.com/tallstackui/tallstackui/releases/tag/v1.28.1
