### ISSUE TITLE
[Feature Request]: set type="button" on <x-button>

### ISSUE THREAD

**Issue by rabol** [tasteui/tasteui#495]
### Suggestion Theme

all

### Main Benefits

When you have multiple <x-button> in a form, then no matter which is pressed the form is submitted.

A <x-button> is pr. default a type="button", so that should be added as default.

Yes, I know that one can add the type="button" manually, but as Caleb say in a video set type="button" when it's button ans type="submit" when you want the button to be a submit button.

**Comment by devajmeireles** [comment]
Makes sense. I adapted our buttons and released them right now in v1.28.1. Thanks!

https://github.com/tallstackui/tallstackui/releases/tag/v1.28.1
