### ISSUE TITLE
[Bug]: Select searchable with extra query parameters

### ISSUE THREAD

**Issue by kachkolasa** [tasteui/tasteui#499]
### What Happened

When I use <x-select.styled searchable /> with a route in the :request and pass some query parameters in the route. Then it does not append the search to the parameters but instead creates a new group of parameters.

For example:
If my route in the :request attribute is:
`route('reports.attributions.search')`
Then it works just fine.

But if I use this:
`route('reports.attributions.search', ['type' => 'os', 'group' => 'agent'])`
Although when you click on the select (when the search is empty) then it works but as soon as you start typing or select an option then the request being sent is:
search?type=os&group=agent?search=windows

### How to Reproduce

Use <x-select.styled searchable /> but add some default parameters to the route of the :request attribute.

### Laravel Version

10.44

### Livewire Version

3.4

### TallStackUI Version

1.15.1

### PHP Version

8.1

### Operation System

macOS

**Comment by jeffersongoncalves** [comment]
To use custom parameters, you must use an array informing the url, method and request. As per documentation.

https://tallstackui.com/docs/form/select#styled-api-advanced-usage

```
<x-select.styled :request="[
                    'url' => route('reports.attributions.search'),
                    'method' => 'get',
                    'params' => ['type' => 'os', 'group' => 'agent'],
                 ]" />
```

**Comment by devajmeireles** [comment]
> To use custom parameters, you must use an array informing the url, method and request. As per documentation.
> 
> https://tallstackui.com/docs/form/select#styled-api-advanced-usage
> 
> ```
> <x-select.styled :request="[
>                     'url' => route('reports.attributions.search'),
>                     'method' => 'get',
>                     'params' => ['type' => 'os', 'group' => 'agent'],
>                  ]" />
> ```

I think the reason is that he is using an old version, 1.15.1, while the latest version is 1.28.1

**Comment by devajmeireles** [comment]
@kachkolasa I don't know if the reproduction steps are wrong or what because I couldn't see the same problem here. As part of my review, I recorded a simple demo video: https://www.loom.com/share/eb88d687d2a44e7a8e0ee8aff34e306f

This was my test environment:

```blade
<x-select.styled :request="[
                    'url' => route('users', ['first' => 'foo', 'second' => 'bar']),
                    'method' => 'get',
                ]" select="label:label|value:id" />
```

```php
Route::get('/users/{first}/{second}', function (Request $request) {
    $selected = json_decode($request->get('selected', ''), true);

    return User::query()
        ->when(
            $search = $request->get('search'),
            fn (Builder $query) => $query->where('name', 'like', "%{$search}%")
        )
        ->when($selected, fn (Builder $query) => $query->whereIn('id', $selected))
        ->limit($search || $selected ? 50 : 10)
        ->get()
        ->map(fn (User $user) => [
            'label' => $user->name,
            'data' => $user->id,
        ]);
})->name('users');
```

Please, try to upgrade your TSUI to the latest version and test it again. Let me know if the issue persists after that.

**Comment by kachkolasa** [comment]
Are you using the same version as mine? 

Upgrading might be an issue since the application is too large and uses TallStackUI in a lot of places, if there is a work-around then it would be great.

**Comment by devajmeireles** [comment]
My tests were done on our latest version. You can try @jeffersonsimaogoncalves  tip.

While I understand you, keeping TSUI updated will bring you many benefits. The main ones are linked to bug fixes.

**Comment by kachkolasa** [comment]
@jeffersonsimaogoncalves tip worked with my version. Thanks guys for the help!
