### ISSUE TITLE
[Bug]: wire:change does not work on date helpers 

### ISSUE THREAD

**Issue by focuslegon** [tasteui/tasteui#502]
### What Happened

I expect clicking on Today or Yesterday or Tomorrow to make a method call when i am using the wire:change action on the date component.

### How to Reproduce

when i use wire:change on date component with helpers , clicking on Today or Yesterday or Tomorrow does not work. add filters to the date component and add wire:change="methodName" , dd inside the method name to see if there will be a method call after you click on those buttons

### Laravel Version

10.4

### Livewire Version

3.5

### TallStackUI Version

1.28

### PHP Version

4.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @focuslegon ! Thanks for reporting.

I handled this as a feature request and introduced it in our latest version released right now, v1.29.0!
https://github.com/tallstackui/tallstackui/releases/tag/v1.29.0
