### ISSUE TITLE
[Feature Request]: Dialogs allow x-html instead of x-text

### ISSUE THREAD

**Issue by Tayouza** [tasteui/tasteui#505]
### Suggestion Theme

Dialogs

### Main Benefits

This will allow it to render html tags like &lt;b&gt;, &lt;i&gt;, etc... to style the description and title.

### Notes

![image](https://github.com/tallstackui/tallstackui/assets/86798160/a9ad23c0-8f31-43bf-86ab-708d40fae615)

**Comment by devajmeireles** [comment]
@Tayouza ,

The dialogs already support HTML:

![CleanShot 2024-06-12 at 23 10 25](https://github.com/tallstackui/tallstackui/assets/60591772/fbf2fbc5-0c20-461b-bfcf-7e6438dd262d)

Try this:

```php
$this->dialog()
    ->success("<b style=\"color: #ff0000\">Foo</b>bar", "<i>Bar</i>Baz")
    ->send();
```
