### ISSUE TITLE
[Bug]: getting syntax error, unexpected token "<" 

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#519]
### What Happened

My Php
 $routes = Route::getRoutes();
       $this->routeList = [];

       foreach ($routes as $route) {
        $rtName = $route->getName();

        if  ( !str_starts_with($rtName,'generated')){

            $this->routeList[] = [ 'name' => $route->getName(), 'id' => $route->getName() ];

        }
       }

My Blade
            <div class="flex px-2 mt-2 space-x-5">
                <div class="flex flex-col w-full">
                    <x-ui.forms.arrayselect :optionsList='{{ $routeList}}' label='route *'
                        wireModel="url" required />
                </div>
            </div>
 Component 
 @props(['name' => '', 'hint' => ''  , 'optionsList' => [],  'id' => '', 'wireModel' => '' , 'label' => ''] )

<x-ts-select.styled
                 label="{{$label}}"
                 :options="{{ $optionsList }}"
				 wire:model.defer={{$wireModel}}
				 />          

### How to Reproduce

This livewire component  php in code

### Laravel Version

10.48.13

### Livewire Version

3.5.1

### TallStackUI Version

1.30.2

### PHP Version

8.3.7

### Operation System

macOS

**Comment by devajmeireles** [comment]
> <x-ts-select.styled
> label="{{$label}}"
> :options="{{ $optionsList }}"
> wire:model.defer={{$wireModel}}
> />

This error is not related to TallStackUI, but yes with your component:

```blade
<x-ts-select.styled
label="{{$label}}"
:options="{{ $optionsList }}"
wire:model.defer="$wireModel"
/>
```
