### ISSUE TITLE
[Bug]: Alpine Expression Error: Cannot read properties of undefined (reading 'getModifierState')

### ISSUE THREAD

**Issue by leofranca47** [tasteui/tasteui#523]
### What Happened

When I use <x-password /> in version 1.26.1 it's ok, updated version to 1.31.1 start error
![image](https://github.com/tallstackui/tallstackui/assets/42575330/8133411e-772d-47b1-b8d5-8705ff21a5eb)

I back version to 1.26.1 it's ok.

### How to Reproduce

install version 1.31.1, use <x-password /> write in input, error in console in your browser

### Laravel Version

10.48.14

### Livewire Version

3.5.0

### TallStackUI Version

1.31.1

### PHP Version

8.2.20

### Operation System

Linux

**Comment by devajmeireles** [comment]
Thanks for reporting! Fixed in v1.31.2 released now.
