### ISSUE TITLE
[Bug]:  Input field is not getting auto focus after loading modal.

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#526]
### What Happened

When you load a simple modal with input , the focus is not getting to that input field. the modal code is as follows
<div>
    <x-ts-modal title="Search" wire="displayingModal">
        <div class="flex flex-col w-full">
            <input class="focus:outline-none" name='searchString' language='en' label='' id='searchString' wire:model.defer="searchString" x-ref="searchString" />
        </div>
    </x-ts-modal>
</div>

### How to Reproduce

The input field is not getting auto focus
<div>
    <x-ts-modal title="Search" wire="displayingModal">
        <div class="flex flex-col w-full">
            <input class="focus:outline-none" name='searchString' language='en' label='' id='searchString' wire:model.defer="searchString" x-ref="searchString" />
        </div>
    </x-ts-modal>
</div>

### Laravel Version

10.48.13

### Livewire Version

3.5.1

### TallStackUI Version

1.30.2

### PHP Version

8.3.7

### Operation System

macOS

**Comment by devajmeireles** [comment]
This is not a bug in TallStackUI. You need to focus on the input after the modal is open. The best thing to do in this case is to use Alpine. Take a look at this example:

![CleanShot 2024-06-27 at 21 14 47](https://github.com/tallstackui/tallstackui/assets/60591772/06d4e38d-18e8-4926-bb5c-a3d6013b6a38)

**Comment by abhideshpande** [comment]
Thanks a lot ! Really amazed by your knowladge.
