### ISSUE TITLE
[Bug]:  collapsable sidebar.  On close sidebar - Only icon On  Open sidebar - Icon and Text

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#537]
### What Happened

Want to keep icon only in collapsable sidebar.

On close sidebar - Only icon
On  Open sidebar - Icon and Text

### How to Reproduce

<x-link href="https://google.com.br/"
        text="TallStackUI"
        icon="link" />
 
<x-link href="https://google.com.br/"
        text="TallStackUI"
        icon="arrow-up-right"
        position="right" />

### Laravel Version

10.48.14 

### Livewire Version

3.5.1  

### TallStackUI Version

1.32.0 

### PHP Version

8.3.7

### Operation System

macOS

### Notes

Need your help in achieving the same

**Comment by abhideshpande** [comment]
<x-link href="https://google.com.br/"
        text="TallStackUI"
        icon="link" />


  const sidebar = document.getElementById('sidebar');
        const toggleButton = document.getElementById('toggle-button');
        const sidebarText = document.querySelectorAll('.sidebar-text');
        const sidebarTitle = document.getElementById('sidebar-title');
        const caretIcons = document.querySelectorAll('.caret-icon');
I used this for li
        // Toggle sidebar on hover
        sidebar.addEventListener('mouseenter', function() {
            sidebar.classList.remove('sidebar-collapsed');
            sidebar.classList.add('sidebar-expanded');
            sidebarTitle.classList.remove('hidden');
            sidebarText.forEach(text => text.classList.remove('hidden'));
            caretIcons.forEach(caret => caret.classList.remove('hidden'));
        });

        sidebar.addEventListener('mouseleave', function() {
            sidebar.classList.add('sidebar-collapsed');
            sidebar.classList.remove('sidebar-expanded');
            sidebarTitle.classList.add('hidden');
            sidebarText.forEach(text => text.classList.add('hidden'));
            caretIcons.forEach(caret => caret.classList.add('hidden'));
        });

**Comment by devajmeireles** [comment]
Sorry! I don't understand what this is related to.

**Comment by abhideshpande** [comment]
requesting a javascript to show and hide the text - so onclick of button link will hide text and only icons are visible and and on other click of button it will show text  icons will still visible.

basically toggle text show/hide on javascript
