### ISSUE TITLE
[Help Needed]  need to parse json to select styled component http://127.0.0.1:8000/jsondata/routes  output is json 

### ISSUE THREAD

**Issue by abhideshpande** [tasteui/tasteui#540]
### What Happened

Thanks a lot for such a great package, would like to explore having jsondata as input to select.styled.

http://127.0.0.1:8000/jsondata/routes output is 
[{"id":"filament.exports.download","name":"filament.exports.download"},{"id":"filament.imports.failed-rows.download","name":"filament.imports.failed-rows.download"},{"id":"filament.admin.auth.login","name":"filament.admin.auth.login"},{"id":"filament.admin.auth.logout","name":"filament.admin.auth.logout"},{"id":"filament.admin.pages.dashboard","name":"filament.admin.pages.dashboard"},{"id":"login","name":"login"},{"id":null,"name":null},{"id":"logout","name":"logout"},{"id":"password.request","name":"password.request"},{"id":"password.reset","name":"password.reset"},{"id":"password.email","name":"password.email"},{"id":"password.update","name":"password.update"}]
                    

my blade
            <div class="flex px-2 mt-2 space-x-5">
                <div class="flex flex-col w-full">
                    <x-ui.forms.jsonselect qry='routes' id="url" name="url" label='Route'
                        wireModel="url" />
                </div>
            </div>

my Component
<x-ts-select.styled label="{{ $label }}"
                    :request="route('jsondata',['qry' =>  $qry ])"
                    select="label:name|value:id"
                    wire:model.defer="{{ $wireModel }}" />

### Component

Select Styled

### How to Reproduce

create blade and component as requesteda about

### Laravel Version

10.48.14

### Livewire Version

3.5.1

### TallStackUI Version

1.32.0

### PHP Version

8.3.7

### Operation System

macOS

**Comment by devajmeireles** [comment]
I'm trying to understand. Do you want to select an option and with this assign a json to the `url` variable?

**Comment by devajmeireles** [comment]
Closed due to inactivity.
