### ISSUE TITLE
[Bug]: Trapped focus on Upload component

### ISSUE THREAD

**Issue by esfredderickmx** [tasteui/tasteui#544]
### What Happened

When using the `<x-upload/>` component in a form with other form component types after or before it and you put the focus on the upload via click or tab, **you are no more able to tab focus to next or previous components**.

### Component

Upload

### How to Reproduce

Make a fresh instance of a project using Laravel and TallsStackUI. Make a simple form with at least three form components and two different types of focusable form components in next order:

1. different to `<x-upload/>`
2. `<x-upload/>`
3. different to `<x-upload/>`

Then get the focus on the `<x-upload/>` component and try to continue tab focus. You will not be able.

### Laravel Version

11.14

### Livewire Version

3.5.2

### TallStackUI Version

1.32.0

### PHP Version

8.3.7

### Operation System

Windows

**Comment by devajmeireles** [comment]
Hey, @esfredderickmx ! Firstly, sorry for the delay in responding! Could you send a repository that demonstrates the problem happening? This way I can analyze it because, in my tests, I was unable to reproduce it.

**Comment by devajmeireles** [comment]
Closed due to inactivity.
