### ISSUE TITLE
[Bug]: Link component prints the link if the text attribute is not provided

### ISSUE THREAD

**Issue by buenojosias** [tasteui/tasteui#550]
### What Happened

Before the most recent update, when using the link component, it was possible to provide only the icon attribute (in addition to the href) so that only an icon would appear, without text.
Now it is necessary to add the text attribute with an empty value, otherwise it will assume the value of link in the text.

How it should appear:
![image](https://github.com/tallstackui/tallstackui/assets/66849846/4735dfcb-15e6-4bfa-9016-a9f53a608391)

How it appears without the text attribute
![image](https://github.com/tallstackui/tallstackui/assets/66849846/d9ad4bb9-710d-4068-950f-9751738ec8e5)

### Component

Link

### How to Reproduce

Previously accepted mode
`<x-ts-link :href="$production->url" icon="arrow-top-right-on-square" blank />`

How should it be written now
`<x-ts-link :href="$production->url" text="" icon="arrow-top-right-on-square" blank />`

### Laravel Version

11.3.1

### Livewire Version

3.5.2

### TallStackUI Version

1.32.2

### PHP Version

8.2.0

### Operation System

Windows

**Comment by devajmeireles** [comment]
Thanks for reporting. I added a new feature that prints the `href` when text or slots are not set, but I forgot to check the icon. 

It was fixed in the v1.32.3 released right now.

**Comment by buenojosias** [comment]
Obrigado pelo retorno.
