### ISSUE TITLE
[Feature Request]: Change source library for Tabler Icons integration

### ISSUE THREAD

**Issue by esfredderickmx** [tasteui/tasteui#556]
### Suggestion Theme

Icons

### Main Benefits

Idk from where are currently taken the icons for the **Tabler** library, awnyway **[Tabler Icons](https://tabler.io/changelog)** is a library which updates itself very often, and even when the official _[Blade Icons repo](https://github.com/blade-ui-kit/blade-icons)_ recommends the [ryangjchandler's one](https://github.com/ryangjchandler/blade-tabler-icons) as the most viable blade option for this library, the one I mention in the source of suggestion point has automated releases, making integration faster and more intuitive IMO.

### Source of the Suggestion

https://github.com/secondnetwork/blade-tabler-icons

### Notes

In the current integrated version of the Tabler Icons, I can't use an icon which was released 3 months ago. Using the another one as oficial at least for TallStackUi, Tabler Icons integration can updates the icons with just a difference of several hours, not months

**Comment by devajmeireles** [comment]
Hey, @esfredderickmx ! [We have an Icon repository](https://github.com/tallstackui/icons) where we host the icons that are downloaded to TallStackUI. We downloaded TablerIcons directly from the website, the outline version only. In reality, I always take care to update the icons periodically, but as I was away for a few days, this didn't happen. I'll work on it this next week!

**Comment by sneycampos** [comment]
Take a look at the bin/compile.sh in ryan's repo, maybe it could be automated too using github actions or something else

**Comment by devajmeireles** [comment]
After a long time working on v2, today I decided to work on some icon-related stuff. I decided to abandon the custom icon mode I created in v1 in favor of using [BladeUi icons](https://github.com/blade-ui-kit/blade-icons) in v2.
