### ISSUE TITLE
[Bug]: Error in console using tabs component

### ISSUE THREAD

**Issue by ghost** [tasteui/tasteui#560]
### What Happened

![image](https://github.com/user-attachments/assets/b3d284d7-a81e-4b3a-8fc9-2205430eb560)

There should be no error in the console.

### Component

Tab

### How to Reproduce

I just copied the tab component below into my Laravel app:

            <x-ts-tab selected="tab">
                <x-ts-tab.items tab="Tab 1">
                    Tab 1
                </x-ts-tab.items>
                <x-ts-tab.items tab="Tab 2">
                    Tab 2
                </x-ts-tab.items>
                <x-ts-tab.items tab="Tab 3">
                    Tab 3
                </x-ts-tab.items>
                <x-ts-tab.items tab="Tab 4">
                    Tab 4
                </x-ts-tab.items>
                <x-ts-tab.items tab="Tab 5">
                    Tab 5
                </x-ts-tab.items>
            </x-ts-tab>
            
Then an error in the console appeared. Please refer to the image.
           
Is this a bug, or do I have a mistake?

### Laravel Version

11.15.0

### Livewire Version

3.5.2

### TallStackUI Version

1.33.0

### PHP Version

8.2.4

### Operation System

Windows

**Comment by devajmeireles** [comment]
Thanks for reporting.

I didn't have the same behavior when I copied your example, but I realized you were doing something wrong.

![CleanShot 2024-07-18 at 10 01 19](https://github.com/user-attachments/assets/bb467551-f1bd-4f22-87b1-943dcedfaad2)

Your `selected` parameter is not selecting a defined tab. In this case, the correct thing is for `selected` to be any existing `tab`:

```blade
<x-ts-tab selected="Tab 1"> 
    <x-ts-tab.items tab="Tab 1">
        Tab 1
    </x-ts-tab.items>
    <x-ts-tab.items tab="Tab 2">
        Tab 2
    </x-ts-tab.items>
    <x-ts-tab.items tab="Tab 3">
        Tab 3
    </x-ts-tab.items>
    <x-ts-tab.items tab="Tab 4">
        Tab 4
    </x-ts-tab.items>
    <x-ts-tab.items tab="Tab 5">
        Tab 5
    </x-ts-tab.items>
</x-ts-tab>
```

Feel free to open a new issue whenever necessary.
