### ISSUE TITLE
[Feature Request]: Icon slot for styled selects

### ISSUE THREAD

**Issue by Alph44rchitect** [tasteui/tasteui#565]
### Suggestion Theme

It would be nice to have the icon slot also for styled selects.

### Main Benefits

Adding the icon slot would add more styling possibilities for the select component.

**Comment by devajmeireles** [comment]
Thanks for your request. I've thought about this in the past, it wouldn't be possible to do it in the current structure because the select options are inserted via JS and the icons are PHP - I would need a good workaround to make it work. I'll mark this as a suggestion for consideration in V2.
