### ISSUE TITLE
[Feature Request]: Clickable Table Rows (or even better: selectable rows)

### ISSUE THREAD

**Issue by mydnic** [tasteui/tasteui#580]
### Suggestion Theme

Table

### Main Benefits

My project requires that the users should be able to select rows in a table list. For now the only way to do that is to put a checkbox in one of the column.

However it would cool to either:
- have a click event on the table rows, so that we can trigger some custom code
- have a fully featured selectable rows with the ability to highlight the full row (change the background color or something)

### Source of the Suggestion

TailwindUI, Nuxt UI and tons of other UI libs

### Notes

https://tailwindui.com/components/application-ui/lists/tables#component-390db22a862687fe88b313692989ffaf

https://ui.nuxt.com/components/table#selectable

**Comment by devajmeireles** [comment]
This makes perfect sense, and it was a feature I promised a long time ago but couldn't do... until today! Here is the PR that adds this: https://github.com/tallstackui/tallstackui/pull/587 🥳 

On Monday I will introduce another new feature for tables and between Tue and Wed I will ship the new version, which also has a lot of new features.

**Comment by mydnic** [comment]
Wow you're the GOAT ! Thanks a lot !

**Comment by devajmeireles** [comment]
Done! Released as part of v1.34.0: https://github.com/tallstackui/tallstackui/releases/tag/v1.34.0
