### ISSUE TITLE
[Feature Request]: Upload Component Front Check

### ISSUE THREAD

**Issue by wilianmaique** [tasteui/tasteui#591]
### Suggestion Theme

Adicionar verificação tambem no frontend para evitar que seja enviado para o backend.

### Main Benefits

Ex: Meu upload aceita apenas imagens. mas eu posso carregar um .zip e dps que carregar ai sim vai ser exibido a msg do erro que aceita somente imagens..

Assim como tamanho tambem.

accept já existe.

```blade
<x-upload size="1024"> 
```
aproveitar do livewire e alpinejs para verificar antes de enviar pro backend...

**Comment by devajmeireles** [comment]
Accept is part of the common behavior of HTML in relation to file upload, while a validation system in the frontend is not. I confess that I don't know if I will go ahead with this, although it looks good we would have some problems making this happen. I'll think about it and I'll update this issue soon!

**Comment by devajmeireles** [comment]
Done. v2 only!
