### ISSUE TITLE
[Feature Request]: Make Floating Width configurable in Dropdown Component

### ISSUE THREAD

**Issue by mschni2s** [tasteui/tasteui#592]
### Suggestion Theme

Configurability of Dropdown Component

### Main Benefits

More control for clients
Opporunity to display any kind of content in the dropdown

### Notes

Floating seems to be injected as a dynamic component in the Dropdown Component with a fixed width

```php
<x-dynamic-component :component="TallStackUi::component('floating')"
                             :floating="$personalize['floating']"
                             class="w-56"
                             offset="5"
                             :$position
                             x-anchor="$refs.dropdown">
            <x-slot:transition>
                {!! $transitions() !!}
            </x-slot:transition>
            @if ($header)
                <div class="m-2">
                    {!! $header !!}
                </div>
            @endif
            <div @class($personalize['wrapper.slot'])>
                {!! $slot !!}
            </div>
        </x-dynamic-component>
```

It would be very nice to have this width as a configurable parameter (like floating) in order to display any kind of content without the need of custom overrides. Would this be a viable option?

Reference: https://github.com/tallstackui/tallstackui/blob/1.x/src/resources/views/components/dropdown/dropdown.blade.php

**Comment by devajmeireles** [comment]
Done! Released as part of v1.34.0: https://github.com/tallstackui/tallstackui/releases/tag/v1.34.0
