### ISSUE TITLE
[Bug]: Textarea when render with data in model

### ISSUE THREAD

**Issue by zaks-zaiya** [tasteui/tasteui#596]
### What Happened

When Im loading a textarea with data in model, unexpected element.style { height: 36px; } is created, to make textarea look like input.

### Component

Textarea

### How to Reproduce

Render a textarea component with a bind model data.

### Laravel Version

11

### Livewire Version

3

### TallStackUI Version

v1.34.0

### PHP Version

8.3

### Operation System

Linux

### Notes

I found if I remove this x-data="tallstackui_formTextArea(@js($personalize['count.max']))", the bug is gone

**Comment by devajmeireles** [comment]
Hey, @zaks-zaiya ! Thanks for reporting. If I understand correctly, this is actually not a problem, but a feature. When we use `resize-auto` on the textarea, the component expands by the size of the text inside it. Is that really what you meant? Please give me an example of how you are using the component.

**Comment by zaks-zaiya** [comment]
This is what I use the textarea, Im upload it to youtube.

[https://youtu.be/yKk4jCs9VH8](https://youtu.be/yKk4jCs9VH8)

**Comment by devajmeireles** [comment]
> This is what I use the textarea, Im upload it to youtube.
> 
> https://youtu.be/yKk4jCs9VH8

I was able to understand the issue with your video, so it is extremely important to mention code examples. What happens is not a bug, but rather the lack of handling cases where nothing was defined in the textarea: rows, resize, or resize-auto.
