### ISSUE TITLE
[Feature Request]: Add creatable Option to Livewire Select Component for On-the-Fly Item Creation

### ISSUE THREAD

**Issue by mchev** [tasteui/tasteui#597]
### Suggestion Theme

The proposed feature enhances the select.styled input form component by allowing users to create a new item if no results are found during a search. This functionality could be activated via an attribute like add or creatable. When the search returns no results, a small "+" icon would appear next to the search term, enabling the user to quickly add a new item.

### Main Benefits

This feature saves time, reduces workflow interruptions, and ensures more accurate data entry. Additionally, it enhances the component's flexibility, making it adaptable to various use cases while maintaining consistent design and functionality across the application.

Example :
In a project management application, a user is assigning tasks to team members using a dropdown select component. When searching for a specific team member, if no matching results are found, the creatable feature allows the user to quickly add a new team member directly from the dropdown, ensuring the task can be assigned without interrupting the workflow or navigating to a different page.

### Notes

The creatable should return an event with label and value properties on click.

**Comment by devajmeireles** [comment]
We already have something related to that, it's the slot after. You can consult the docs to check how it works. I can't see anything better than that for the proposal than you suggested. You can capture the value typed and do something with it, like direct the person to a page to start creating the resource that wasn't found. Reference: https://tallstackui.com/docs/form/select#styled-slot-after
