### ISSUE TITLE
[Bug]: Argument #1 ($array) must be of type array, string given in x-errors

### ISSUE THREAD

**Issue by buenojosias** [tasteui/tasteui#604]
### What Happened

After the most recent updates I started receiving the following error message when using the x-error component:
_reset(): Argument #1 ($array) must be of type array, string given_
![image](https://github.com/user-attachments/assets/b0995e6c-13dc-4f96-aa12-9785235353fb)

### Component

Errors

### How to Reproduce

It started on its own after last package updates

### Laravel Version

11.20.0

### Livewire Version

3.5.4

### TallStackUI Version

1.34.1

### PHP Version

8.2

### Operation System

Windows

**Comment by devajmeireles** [comment]
Hey, @buenojosias ! We don't have the `reset` term in the TSUI namespace:

![CleanShot 2024-08-13 at 12 02 47](https://github.com/user-attachments/assets/4424d6b4-04ff-4362-b1a1-95c5b50029e7)

Is this not an issue in your app? We only have `reset` functions in JS, but the error is in PHP.

**Comment by devajmeireles** [comment]
Closed due to inactivity.
