### ISSUE TITLE
[Bug]: Select Clear Button Rendered Twice

### ISSUE THREAD

**Issue by ldommer** [tasteui/tasteui#605]
### What Happened

Hi there,

I'm having a minor issue with the select styled component, because the select clear button gets rendered twice on a rare occasion.

1)
![1](https://github.com/user-attachments/assets/7c2cf3ee-f826-47fe-95d8-35152a86088a)

2)
![2](https://github.com/user-attachments/assets/129df366-b101-435f-a522-62f88395ca8e)

3)
![3](https://github.com/user-attachments/assets/9358875d-00b0-4ef6-b2e1-d031ccf51060)

### Component

Select Styled

### How to Reproduce

- prepopulate a select field in Livewire mount with a value (for example for a pre-filtered index list)
- clear the field via select clear button
- hit a button that resets the filter form to its initial state (same behaviour if called via `wire:click="resetSearchForm"` or `x-on:click="$dispatch('reset-search-form')"`
- by doing this call a method that does `$this->reset();` and `$this->selectValue = 'default-value'`

### Laravel Version

10.45.1

### Livewire Version

3.4.6

### TallStackUI Version

1.20.2

### PHP Version

8.3

### Operation System

Linux

**Comment by devajmeireles** [comment]
@ldommer , can you please check if there are any console log errors?

**Comment by ldommer** [comment]
No, no logs in the error console.

**Comment by devajmeireles** [comment]
I was able to reproduce this and already fixed it. I appreciate your report. Waiting for the next release.

**Comment by devajmeireles** [comment]
Thanks. Fixed in 1.35.0: https://github.com/tallstackui/tallstackui/releases/tag/v1.35.0
