### ISSUE TITLE
[Feature Request]: Currency locale on input

### ISSUE THREAD

**Issue by leonardoandognini** [tasteui/tasteui#611]
### Suggestion Theme

IMO, I believe it would be interesting if we could have the possibility, as in MaryUi, of having a "locale" prefix to inform what type of currency we are using in the input for the field mask.

### Main Benefits

Standardization, ensure that all monetary values ​​are formatted according to the "locale" parameter standard.
Ease of use, mask is applied automatically when typing.

### Source of the Suggestion

https://mary-ui.com/docs/components/input#currency

### Notes

<img width="833" alt="Screenshot 2024-08-14 at 17 18 40" src="https://github.com/user-attachments/assets/9ad60580-7ffe-44a5-a9b9-8bc32f15f904">

**Comment by devajmeireles** [comment]
I don't have any plans for this now because I believe it's very project-by-project and can be easily done with the native JS API. We could do something like this during the lifespan of v2.
