### ISSUE TITLE
[Bug]: Dark theme as default not working as expected.

### ISSUE THREAD

**Issue by MGeurts** [tasteui/tasteui#619]
### What Happened

```
<html ...
      x-data="tallstackui_darkTheme(null, true)" 
      ...>
    <!-- ... -->
</html>
```

There's a problem with the solution suggested above. It sets the dark theme as default, like promised.
But **after switching the theme to ligh**t with the "Theme Switch", this is not remembered by the browser state.
This means navigating to another page reverts the theme to dark again.

### Component

Theme Switch

### How to Reproduce

See [https://github.com/tallstackui/tallstackui/discussions/530](https://github.com/tallstackui/tallstackui/discussions/530)

### Public Repository

https://github.com/MGeurts/genealogy

### Laravel Version

11.20

### Livewire Version

3.5

### TallStackUI Version

1.35.2

### PHP Version

8.3.10

### Operation System

Windows

**Comment by devajmeireles** [comment]
There is no problem with this, but rather the way the component works. For now I'm not going to change that, maybe in the next version.
