### ISSUE TITLE
[Feature Request]: Dropdown component - Allow "text' property to open the dropdown on click

### ISSUE THREAD

**Issue by BoweFrankema** [tasteui/tasteui#624]
### Suggestion Theme

I think it would be nice to add a new option to the dropdown menu to make the text/label to also open the dropdown, instead of just the icon / carret. ie something like "clickable".

```
<x-dropdown text="Opened when Clicked" position="bottom-end" clickable>
    <x-dropdown.items text="Settings" />
    <x-dropdown.items text="Logout" separator />
</x-dropdown>
```

This would then open the dropdown when you click on either the label or the icon. 

### Main Benefits

I would say this is most intuitive for most use cases ie dropdown/menus, since a user has the tendency to click on text first before clicking an icon. 

### Source of the Suggestion

https://tallstackui.com/docs/ui/dropdown

**Comment by devajmeireles** [comment]
Use the action slot with a tag span and `x-on:click="show = !show"`:

https://tallstackui.com/docs/ui/dropdown#action-slot

**Comment by BoweFrankema** [comment]
Completely overlooked that, thanks!
