### ISSUE TITLE
[Bug]: Upload event no working on l

### ISSUE THREAD

**Issue by pablomadariaga** [tasteui/tasteui#625]
### What Happened

`<x-upload multiple x-on:upload="" />` no working if the component is multiple

### Component

Upload

### How to Reproduce

![image](https://github.com/user-attachments/assets/23d88e53-3e48-4f07-8328-d2ff42b9133c)

### Laravel Version

11.21

### Livewire Version

3.5.6

### TallStackUI Version

1.35.3

### PHP Version

8.3.6

### Operation System

Windows

**Comment by devajmeireles** [comment]
@mchev , could you take a look? Probably will not take much time.

**Comment by devajmeireles** [comment]
Fixed. Thanks!
