### ISSUE TITLE
[Bug]: Inconsistent behavior on tab items within a loop

### ISSUE THREAD

**Issue by esfredderickmx** [tasteui/tasteui#629]
### What Happened

Using the x-tab component in a loop and passing a specific and still unclear type of values to their tab property causes all tabs within the loop collapse their content and behave as a single tab, even when the tabs has another one which keep their normal behavior (is not within the loop).
![image](https://github.com/user-attachments/assets/6c528526-82ad-4afc-859a-90955f1641d1)

### Component

Tab

### How to Reproduce

Make an instance of a fresh Laravel project using TallStackUi. Use the tab component within a class Livewire Volt component like this:

```
@php
  $grouped_reactions = $post->reactions()->selectRaw('type, count(*) as group_count')->groupBy('type')->get();
@endphp
@foreach($grouped_reactions as $reaction_group)
  <x-tab.items wire:key="{{ $post->id }}-{{ $reaction_group->type }}" tab="({{ $reaction_group->group_count }})">
    <x-slot:right>
      <img src="{{ asset('gif/reactions/' . $reaction_group->type->value . '.gif') }}" alt="{{ $reaction_group->type->getEmojiChar() }}" class="h-6">
    </x-slot:right>
    Tab 2
  </x-tab.items>
@endforeach
```

Here we have a Post model with a hasMany relationship on the Reactions model. I want to think this error can be reproduced in any context we need to group by any column and getting and aggregation such as count.

### Laravel Version

11.20

### Livewire Version

3.5.4

### TallStackUI Version

1.35.2

### PHP Version

8.3.7

### Operation System

Windows

### Notes

The code shown in the **How to reproduce** section has to be right after of an x-tab.items component out of the loop.

**Comment by esfredderickmx** [comment]
This could be handled separating name and identifier for each tab, sometime you wanna have more control over you wanna show and how to handle it internally

**Comment by devajmeireles** [comment]
At first I would say that Tab was not designed for loops, but since I am working on V2 I will mark this as a suggestion and see if it is possible to fix this in V2.
