### ISSUE TITLE
[Bug]: Disabled state in select styled template ignored

### ISSUE THREAD

**Issue by ldommer** [tasteui/tasteui#631]
### What Happened

When I pass disabled to a select styled component, the component gets properly disabled. But if I prepopulate it with a value via Livewire or Alpine event, rerender it and so on, the clear select button will be rerendered, too and is still working.

I've published the templates and checked the code.

The `@disabled($disabled)` in line 38 for the whole select field itself is working. But the `@if (!$disabled)` in line 70 seems to be ignored. Maybe because this Blade directive is called inside a client side Alpine.js loop.

I think this is a rare use case, but somehow relevant to me: I've got a complex filter form, where the (dependent) filters talk to each other via events and update each other on certain occasions. On a certain value in one of the filters, another filter has to be "fixed" with a certain value. The filtering itself is working fine, also the disabled state of the select field. But in contrast to the disabled state of the select field, the user is able to remove the "fixed" option by clicking the clear select button, which should not be intended.

### Component

Select Styled

### How to Reproduce

Simply update a Livewire filter component containing a select styled filter component via an Alpine event. For example:
```php
#[On('order-day-form-opened')]
public function setOrderStatuses(): void
{
    $this->orderStatuses = [OrderStatus::Unedited->value];
    $this->isDisabled = true;
}
```

### Laravel Version

10.45.1

### Livewire Version

3.5.4

### TallStackUI Version

1.35.4

### PHP Version

8.2

### Operation System

Linux

**Comment by ldommer** [comment]
Edit: If I apply `@disabled('disabled')`, all other options from other select field components are disabled, too.

**Comment by devajmeireles** [comment]
Since this is not a serious issue, I'll mark this as a suggestion to get a handle on it in V2. I've been working on V2 for a few weeks, and it will be released soon. This component will receive some improvements, among them I'll keep an eye on this. Thank you very much!
