### ISSUE TITLE
[Feature Request]: Make Floating Width configurable in Styled Select component

### ISSUE THREAD

**Issue by mschni2s** [tasteui/tasteui#632]
### Suggestion Theme

Similar request as to https://github.com/tallstackui/tallstackui/issues/592#issue-2449059778

Also the styled select uses the floating component internally, which has the width set to `w-full` - Could this also be made soft personalizable?

```
<x-dynamic-component :component="TallStackUi::component('floating')"
                             :floating="$personalize['floating']"
                             class="w-full overflow-auto"
                             x-anchor="$refs.button">
[...]
```

Reference: https://github.com/tallstackui/tallstackui/blob/1.x/src/resources/views/components/select/styled.blade.php

### Main Benefits

More customized usage of the styled select

**Comment by devajmeireles** [comment]
Done. v2 only!
