### ISSUE TITLE
[Bug]: date range with wire:model.live not working

### ISSUE THREAD

**Issue by priteshqualitycode** [tasteui/tasteui#637]
### What Happened

I have used model.live with date range component  but getting error.
Component : 
<x-ts-date range wire:model.live="date" label="Date" format="DD-MM-YYYY"  />

Error:
TallStackUi\View\Components\Form\Date::TallStackUi\View\Components\Form\{closure}(): Argument #1 ($date) must be of type string, null given

### Component

Alert

### How to Reproduce

I have used [wire](wire:model.live) but getting error.
Component : 
<x-ts-date range wire:model.live="date" label="Date" format="DD-MM-YYYY"  />

Error:
TallStackUi\View\Components\Form\Date::TallStackUi\View\Components\Form\{closure}(): Argument #1 ($date) must be of type string, null given

### Laravel Version

11

### Livewire Version

3.3

### TallStackUI Version

1.35

### PHP Version

8.2

### Operation System

Windows

### Notes

I have used [wire](wire:model.live) but getting error.
Component : 
<x-ts-date range wire:model.live="date" label="Date" format="DD-MM-YYYY"  />

Error:
TallStackUi\View\Components\Form\Date::TallStackUi\View\Components\Form\{closure}(): Argument #1 ($date) must be of type string, null given

**Comment by devajmeireles** [comment]
Thanks for reporting.

The issue only happens if you set the date component with `range` mode and an array of nullable dates, like this:

```php
public array $dates = [null, null];
```

```blade
<x-date wire:model.live="$dates" range ... />
```

I fixed it in the recent tag I released now, v1.35.5.
