### ISSUE TITLE
[Bug]: Press the Enter key, the date component is set to 1.X.2024.

### ISSUE THREAD

**Issue by xX-MISSIT-Xx** [tasteui/tasteui#646]
### What Happened

If you press Enter in an input field, the date in <x-date> is strangely set to the first day of the month.

### Component

Date

### How to Reproduce

Simply set several input fields in a Livewire component and a date field

### Laravel Version

10.48.20

### Livewire Version

3.5.6

### TallStackUI Version

1.35.5

### PHP Version

8.3

### Operation System

Linux, Windows

**Comment by devajmeireles** [comment]
Hi @xX-MISSIT-Xx! I couldn't reproduce this. Since I'm working on V2, if possible please send us a step-by-step guide to reproduce your report or a public repository where we can reproduce this issue, so we can work on a fix for V2.
