### ISSUE TITLE
[Feature Request]: Adding groups to select input

### ISSUE THREAD

**Issue by abdul-alhasany** [tasteui/tasteui#647]
### Suggestion Theme

It will be great if select input had groups like the native [html select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup). 

### Main Benefits

Long lists can be grouped into logical groups making it easier to read and provided better user experience.

### Source of the Suggestion

https://github.com/vueform/multiselect?tab=readme-ov-file#multiselect-with-groups

**Comment by devajmeireles** [comment]
Closing. v2 target!
