### ISSUE TITLE
[Bug]: Select Dropdown closes automatically?

### ISSUE THREAD

**Issue by xX-MISSIT-Xx** [tasteui/tasteui#648]
### What Happened

When something is selected from the dropdown for the first time, it works perfectly. As soon as you want to change it, the dropdown opens and closes again.

Strangely enough, there is no Alpine.js error. In the Chrome Elements view, you can see that it applies the transitions but they are being reset.

![chrome_KVzjF0PxNx](https://github.com/user-attachments/assets/539f9992-64a0-474b-b0eb-e04f6cc6ae8e)

It happens with all dropdowns for whatever reason?

### Component

Select Styled

### How to Reproduce

Unfortunately, I don't know. I followed the documentation.

### Laravel Version

10.48.20

### Livewire Version

10.48.20

### TallStackUI Version

1.35.5

### PHP Version

8.3

### Operation System

Windows, Linux

**Comment by devajmeireles** [comment]
@xX-MISSIT-Xx I'm guessing there's a browser console error, right? If so, please post them all here.

**Comment by xX-MISSIT-Xx** [comment]
@devajmeireles I wish an error would appear in the console, unfortunately it does not.

**Comment by xX-MISSIT-Xx** [comment]
Hi, I have a suspicion as to why. I have about 300 entries in the dropdown. If I reduce it to about 20, it works without any problems. So I think that the parsing to JSON in the Javascript code is causing the problems, if it is actually made in the JS code.

**Comment by xX-MISSIT-Xx** [comment]
And what I forgot to mention is that when this problem occurs it also affects other dropdowns. If I select something there and then select something in another dropdown it sets the value in the first dropdown which caused this problem

**Comment by devajmeireles** [comment]
Closing it now. v2 at least will try to solve this issue, which happens according to the quantity of the options.
