### ISSUE TITLE
[Bug]: <x-slot:after> should always show when user starts typing

### ISSUE THREAD

**Issue by focuslegon** [tasteui/tasteui#649]
### What Happened

I love the select.styles 
1.
<img width="569" alt="Screenshot 2024-09-06 at 7 20 57 PM" src="https://github.com/user-attachments/assets/038e35e1-46a0-4d00-a317-c59acacac859">

2.
<img width="580" alt="Screenshot 2024-09-06 at 7 21 21 PM" src="https://github.com/user-attachments/assets/b09f0ad7-26e5-47da-98c5-87edaf7ae381">

but i think it should always show when user start typing.

Picture 1 is when even though search exist but not what user might be looking for. 

Picture 2 is when the search can not be found in any of the list, 

If you want to pass search through x-on:click="$dispatch('AddNewStatus', { name: search })" i will be forced to use Nigerr instead of Niger 

### Component

Select Styled

### How to Reproduce

The slot should always show , 

### Laravel Version

10.48

### Livewire Version

3.5.6

### TallStackUI Version

1.35.5

### PHP Version

8.1

### Operation System

macOS

**Comment by devajmeireles** [comment]
The idea of ​​the after slot is to be displayed only when there are no available options that match the search term criteria. We have no plans to change this for now. I can think of something related to this in our future v2. I'll mark it as a suggestion so I can return here afterward.
