### ISSUE TITLE
[Bug]: Scoped personalization overrides soft personalization

### ISSUE THREAD

**Issue by abdul-alhasany** [tasteui/tasteui#650]
### What Happened

When applying scoped personalization to a component, the soft personalizations are ignored.

### Component

Dropdown

### How to Reproduce

In soft personalization add this:
```php
 TallStackUi::personalize('dropdown')
        ->block('wrapper.slot')
        ->replace('overflow-hidden', 'overflow-auto soft-scrollbar')
        ->append('max-h-60');
```

then in blade component add this:
```html
<x-dropdown
	position="top-end"
	:personalize="[
		'wrapper.first' => [
			'append' => 'w-full',
		],
		'wrapper.second' => [
			'append' => 'w-full',
		],
	]"
	>
</dropdown>
```

### Laravel Version

11.9

### Livewire Version

3.5

### TallStackUI Version

1.35

### PHP Version

8.3.10

### Operation System

Windows

### Notes

I am not sure if this is a bug. My intuition is that scoped personalization should be merged with soft personalization,, which in turn should be merged with the component style. This makes sense sence one would like to apply global style, and then apply adhoc style to a specific component.

I tested only with dropdown component but I guess the same happense with other components.

**Comment by devajmeireles** [comment]
Couldn't reproduce it when reported. Focusing on v2 starting from now. Let's check if it will happen on v2 after release.
