### ISSUE TITLE
[Feature Request]: Make only body scrollable in slide

### ISSUE THREAD

**Issue by abdul-alhasany** [tasteui/tasteui#651]
### Suggestion Theme

Currently in slide component, the body and footer are both scrollable. If there is a long body then footer buttons will be hidden and user need to scroll to the very end to see it.
I think it is better to have the scroll applied only to body.
Also, footer should be fixed to the bottom (body should grow to take all the available space)

### Main Benefits

This provides a better user experince. Typically, slide is used to show forms and they tend to be long. Having the body extend and scrollable as well positioning the footer to the bottom will improve UX.

**Comment by buenojosias** [comment]
I don't think he will make this update in version 1. But I already managed to do what you suggested by creating a div with w-full and overflow-x-auto.

**Comment by devajmeireles** [comment]
I appreciate your suggestion, @abdul-alhasany. As mentioned by @buenojosias, I'm only working on V2 stuff, **so I already did this, but I only targeted V2.**
