### ISSUE TITLE
[Bug]: Date skips a month

### ISSUE THREAD

**Issue by AliasSuperman** [tasteui/tasteui#655]
### What Happened

When I use <x-ts-date /> it skips a month when you click < or > 

The demo here: https://tallstackui.com/docs/form/date does it too

### Component

Date

### How to Reproduce

The demo here: https://tallstackui.com/docs/form/date does it too

### Public Repository

none

### Laravel Version

11.22.0

### Livewire Version

3.5.6

### TallStackUI Version

1.35.6

### PHP Version

8.3.4

### Operation System

Windows

### Notes

Thanks for a great product

**Comment by devajmeireles** [comment]
This report does not have detailed descriptions and I could not reproduce it. The arrows have a behavior that allows us to navigate between months when we hold them down. This may be the reason. If you believe this is a bug, please open a new issue with more details.
