### ISSUE TITLE
[Bug]: Toast Component show message The toast [ok] message cannot be empty.

### ISSUE THREAD

**Issue by bendo01** [tasteui/tasteui#660]
### What Happened

i follow instruction on using toast on https://tallstackui.com/docs/interaction/toast

```html
<section class="min-h-screen bg-transparent">
    <x-ts-toast />
    <x-layouts.navigation/>
    <main class="p-4">
        <div class="mx-auto prose">
            {{ $slot }}
        </div>
    </main>
</section>
```

when i put in my application layout

it show an error
InvalidArgumentException

The toast [ok] message cannot be empty.

when i commented 

```html
<section class="min-h-screen bg-transparent">
    {{-- <x-ts-toast /> --}}
    <x-layouts.navigation/>
    <main class="p-4">
        <div class="mx-auto prose">
            {{ $slot }}
        </div>
    </main>
</section>
```

it run ok but it cannot show toast message

### Component

Alert

### How to Reproduce

Install fresh laravel app and add tallstackui

### Laravel Version

11.23.5

### Livewire Version

3.5.6

### TallStackUI Version

1.35.6

### PHP Version

8.3.11

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @bendo01 ! Probably you have the TSUI language file published and it is outdated. Check it again and confirm here if I'm right.

**Comment by bendo01** [comment]
yes i made some mistake on .env setting, on my env

APP_FALLBACK_LOCALE=id

the correct value is

APP_FALLBACK_LOCALE=en

Thank you for your suggestion
