### ISSUE TITLE
[Bug]: Date not work

### ISSUE THREAD

**Issue by ryanyulianto** [tasteui/tasteui#662]
### What Happened

<img width="931" alt="Tangkapan Layar 2024-09-18 pukul 09 49 30" src="https://github.com/user-attachments/assets/98d75790-7bac-48f3-973e-ab8e89eef386">

<img width="290" alt="Tangkapan Layar 2024-09-18 pukul 09 54 46" src="https://github.com/user-attachments/assets/9c425b03-5732-45f4-a08e-45671ff7f9a2">

### Component

Date

### How to Reproduce

            <x-ts-date range wire:model="test"/>

### Laravel Version

11.9

### Livewire Version

3.5

### TallStackUI Version

1.35

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
We need more information to determine if this is a bug. What does your TallStackUi installation look like? Are you loading Alpine on every page as part of the main layout?

**Comment by ryanyulianto** [comment]
`<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="apple-touch-icon" sizes="180x180"
        href="{{ $setting?->favicon_apple_touch_icon && Storage::disk('public')->exists($setting?->favicon_apple_touch_icon) ? asset('storage/' . $setting?->favicon_apple_touch_icon) : asset('assets/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32"
        href="{{ $setting?->favicon_32 && Storage::disk('public')->exists($setting?->favicon_32) ? asset('storage/' . $setting?->favicon_32) : asset('assets/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16"
        href="{{ $setting?->favicon_16 && Storage::disk('public')->exists($setting?->favicon_16) ? asset('storage/' . $setting?->favicon_16) : asset('assets/favicon/favicon-16x16.png') }}">
    <link rel="manifest"
        href="{{ $setting?->favicon_site_webmanifest && Storage::disk('public')->exists($setting?->favicon_site_webmanifest) ? asset('storage/' . $setting?->favicon_site_webmanifest) : asset('assets/favicon/site.webmanifest') }}">

    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.44.0/tabler-icons.min.css">

    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css" rel="stylesheet" />
    @stack('styles')
    <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js"></script>
    <link rel="stylesheet" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
    <link rel="stylesheet" href="{{ asset('froala/css/froala_editor.pkgd.min.css') }}">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"></script>

    @if (!request()->routeIs('absensi.map'))
        <tallstackui:script />
    @endif

    @livewireStyles
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <wireui:scripts />
    <title>{{ $setting?->website_name ?? 'Burningroom Technology' }}</title>

    
    <link rel="stylesheet" href="{{ asset('assets/components/flatpickr.min.css') }}">

</head>

<body class="bg-gray-100 font-ubuntu">
    <main>
        
        <div id="main-wrapper" class="flex">
            <x-admin.sidebar />
            <div class="w-full lg:ml-[320px] ml-0 overflow-hidden">
                <x-admin.header />
                <main class="h-full max-w-full pt-20 overflow-y-auto">
                    <div class="container w-full pt-5 overflow-hidden pb-36">
                        {{ $slot }}
                    </div>
                </main>
            </div>
        </div>
    </main>

    @php
        $fullName = Auth::user()->name;
        $firstName = explode(' ', $fullName)[0];
    @endphp

    <x-admin.modal-ultah id="alert-ultah" nama="{{ $firstName }}">

    </x-admin.modal-ultah>

    @livewireScripts
    @stack('scripts')
    @filepondScripts
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tsparticles/confetti@3.0.3/tsparticles.confetti.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ asset('vendor/livewire-alert/livewire-alert.js') }}"></script>
    <script src="https://balkan.app/js/OrgChart.js"></script>
    <x-livewire-alert::scripts />
    <x-livewire-alert::flash />

    @if (session('ultah'))
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const end = Date.now() + 15 * 1000;
                let animationRunning = true; // Variabel kontrol untuk menghentikan animasi
                const colors = ["#0D4890", "#ffffff"];

                // Fungsi animasi konfeti
                function frame() {
                    if (animationRunning) {
                        confetti({
                            particleCount: 2,
                            angle: 60,
                            spread: 55,
                            origin: {
                                x: 0
                            },
                            colors: colors,
                        });

                        confetti({
                            particleCount: 2,
                            angle: 120,
                            spread: 55,
                            origin: {
                                x: 1
                            },
                            colors: colors,
                        });
                        requestAnimationFrame(frame);
                    }
                }

                frame();
                document.getElementById('stopAnimationUltah').addEventListener('click', function() {
                    animationRunning = false;
                });

                HSOverlay.open('#alert-ultah');
            });
        </script>
    @endif
    <script data-navigate-once defer>
        Livewire.hook('element.init', ({
            component,
            el
        }) => {
            window.HSStaticMethods.autoInit();
            //
        });
        document.addEventListener('lived', function() {
            window.HSStaticMethods.autoInit();
        });
    </script>
    
    <script src="{{ asset('assets/components/flatpickr.min.js') }}"></script>
</body>

</html>
`


that from my layout

**Comment by devajmeireles** [comment]
My first thought is related to a conflict you may have due to the fact that you are using multiple libraries in your project. I strongly suggest selecting a single library and proceeding with that only.
