### ISSUE TITLE
[Feature Request]: Disabled select styled description

### ISSUE THREAD

**Issue by pablomadariaga** [tasteui/tasteui#664]
### Suggestion Theme

Select styled

### Main Benefits

Disabled select styled description Manually with attr :withDesc="false"

### Notes

I need to disable the description as it is very long in my app and I only need the name.
![image](https://github.com/user-attachments/assets/d8f5fe98-cb23-4d01-9f3f-9dd42ee84201)

**Comment by devajmeireles** [comment]
Hey! @pablomadariaga . The description is set through the multi-dimensional array: https://tallstackui.com/docs/form/select#styled-description, so you can remove the description from there. No plans for this right now.
