### ISSUE TITLE
[Feature Request]: Popover Component

### ISSUE THREAD

**Issue by andrefelipe18** [tasteui/tasteui#669]
### Suggestion Theme

A popover component, a good example:
https://primevue.org/popover/

### Main Benefits

A larger variety of components

### Source of the Suggestion

https://primevue.org/popover/

**Comment by devajmeireles** [comment]
IMHO, it's more interesting to try to adapt the current dropdown to something like this. I don't know if it would be possible, but it would extend the current dropdown. In any case, let's leave this as a V2 feature after it's released.
