### ISSUE TITLE
[Bug]: PhpStorm does not recognize tag names

### ISSUE THREAD

**Issue by VladimirBazhenov** [tasteui/tasteui#683]
### What Happened

![2bug](https://github.com/user-attachments/assets/c1cf24c9-d894-4830-8891-1f1fe4921f41)

If I set a prefix, for example ts-, when trying to use <ts-button>, the problem with the backlight disappears, but the component is not actually recognized and an error appears already on the frontend. Using the correct spelling of <x-ts-button> saves problems with the backlight.

The problem exists with all components.

### Component

Alert

### How to Reproduce

Install a fresh Laravel 11 app, install TallStackUI according to the instructions (head scripts, tailwind config, npm run build && php artisan optimize:clear).

### Laravel Version

11.9

### Livewire Version

3.5

### TallStackUI Version

1.35

### PHP Version

8.2

### Operation System

Linux

**Comment by devajmeireles** [comment]
@VladimirBazhenov , this is an issue related to PhpStorm's inability to resolve component names. We are working on a possible plugin for this in PhpStorm. The main difficulty is that the plugin is written in JAVA, I think, a language I am not familiar with. I will close this for now as a suggestion so we can address this in V2. If you know any JAVA devs, please point me to their social networks.
