### ISSUE TITLE
[Feature Request]: Make the Color Picker clearable to allow NULL values

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#684]
### Suggestion Theme

<x-color> 

### Main Benefits

Allow to have a null button for the color picker instead of using white for false values

<img width="611" alt="image" src="https://github.com/user-attachments/assets/a527727e-f63f-4b95-ab5f-b50a052fa683">

**Comment by devajmeireles** [comment]
Closed. Done. v2 target.
