### ISSUE TITLE
[Bug]: Clicking on checkbox label cheks/uncheck another label

### ISSUE THREAD

**Issue by rabol** [tasteui/tasteui#685]
### What Happened

when having multiple checkboxes grouped in one div, the cliewcking on one of the labels, check/uncheck the first checkbox

### Component

Checkbox

### How to Reproduce

In a new Laravel app with jetstream as a starterkit, make a simple livewire component
NOTE: the TSUI prefix.

Component:
```
class TsuiTest extends Component
{
    public array $permissions;

    public function mount(): void
    {
        $this->permissions = ['read', 'write', 'update', 'delete'];
    }

    public function render(): View
    {
        return view('livewire.tsui-test');
    }
}
```

view
```
<div>
    <div class="col-span-6">
        <x-label value="{{ __('Permissions') }}"/>
        <div class="mt-2 grid grid-cols-1 md:grid-cols-2 gap-4">
            @foreach ($permissions as $permission)
                <x-tsui-checkbox wire:model="permissions" label="{{$permission}}" :value="$permission"/>
            @endforeach
        </div>
    </div>
</div>
```

When the component is rendered, and you click on any of the labels, the first (read) will get checkked. or unchecked

### Laravel Version

11.25.0

### Livewire Version

3.5.4

### TallStackUI Version

1.36.7

### PHP Version

8.3.12

### Operation System

macOS

**Comment by devajmeireles** [comment]
```blade
<x-tsui-checkbox wire:model="permissions" label="{{$permission}}" :value="$permission"/>
```

@rabol, since you're using the same property for all the checkboxes, you have two alternative ways:

1. Using a different unique property for each component in the loop: `wire:model="permissions.{{ $key }}"`
2. Trying to use an unique id for each component: ` ... id="{{ uniqid() }}"`

**Comment by rabol** [comment]
well, it works with normal checkboxes, but not TSUI checkboxes

**Comment by devajmeireles** [comment]
> well, it works with normal checkboxes, but not TSUI checkboxes

I don't think so, if you turn the TSUI checkbox into a normal checkbox, the problem will still occur. Here's an example:

![CleanShot 2024-09-29 at 10 24 19](https://github.com/user-attachments/assets/01694fd1-be92-41ba-b9ea-4deae010d256)

To make it work properly as you want, you need to use a unique id, for example:

![CleanShot 2024-09-29 at 10 25 23](https://github.com/user-attachments/assets/56fb3cae-455f-4f63-8aff-1db346454318)

**Comment by rabol** [comment]
this is from Jetstream - resources/views/api/api-token-manager.blade.php

```
 <div class="mt-2 grid grid-cols-1 md:grid-cols-2 gap-4">
                        @foreach (Laravel\Jetstream\Jetstream::$permissions as $permission)
                            <label class="flex items-center">
                                <x-checkbox wire:model="createApiTokenForm.permissions" :value="$permission"/>
                                <span class="ms-2 text-sm text-gray-600 dark:text-gray-400">{{ $permission }}</span>
                            </label>
                        @endforeach
                    </div>
```

and that works

**Comment by devajmeireles** [comment]
> this is from Jetstream - resources/views/api/api-token-manager.blade.php
> 
> ```
>  <div class="mt-2 grid grid-cols-1 md:grid-cols-2 gap-4">
>                         @foreach (Laravel\Jetstream\Jetstream::$permissions as $permission)
>                             <label class="flex items-center">
>                                 <x-checkbox wire:model="createApiTokenForm.permissions" :value="$permission"/>
>                                 <span class="ms-2 text-sm text-gray-600 dark:text-gray-400">{{ $permission }}</span>
>                             </label>
>                         @endforeach
>                     </div>
> ```
> 
> and that works

In the TSUI checkbox, if you use `wire:model` the engine will understand that you are using Livewire and therefore will use the value of `wire:model` as `value`, the solution, in this case, is to use a different `id` for each checkbox:

```
:id="$permission"
```

or:

```
:id="uniqid()"
```

Note that if you remove `wire:model`, it will work as you expect.

**Comment by rabol** [comment]
hmm.. ok, I still feel like it is a little strange that TSUI components/input controls behaves different from what standard input do in livewire
