### ISSUE TITLE
[Bug]: Toast not shown after redirect if `navigate: true`

### ISSUE THREAD

**Issue by abedcodes** [tasteui/tasteui#692]
### What Happened

here you will not see toast unless navigate:false ! i want to use livewire navigation so what to do?

```
$this->toast()->success('message')->flash()->send();
return $this->redirectRoute('route.name', navigate: true);
```

### Component

Toast

### How to Reproduce

follow the steps in tallstackui documentation.

### Laravel Version

11

### Livewire Version

3

### TallStackUI Version

1.35

### PHP Version

8.3

### Operation System

Linux

**Comment by devajmeireles** [comment]
Fixed in v1.35.8.
