### ISSUE TITLE
[Bug]: Form date component (range mode)

### ISSUE THREAD

**Issue by Samu-14** [tasteui/tasteui#706]
### What Happened

When i use x-date with "wire:model.blur="range" range" i keep getting this error "The date [value] must be an array when using the [range] or [multiple]" i think is because livewire keep sending that range is updating to null

### Component

Date

### How to Reproduce

```
<?php
use Livewire\Volt\Component;

new class extends Component {
  public $range = [];
}
?>

<div class="h-dvh flex items-center justify-center gap-6">
  <x-date label="Date" hint="Insert your date" wire:model.blur="range" range format="DD/MM/YYYY" />
</div>
```

this is the code

### Laravel Version

11.26.0

### Livewire Version

3.5.9

### TallStackUI Version

1.35.9

### PHP Version

8.3.12

### Operation System

Windows

**Comment by devajmeireles** [comment]
Thanks, @Samu-14 ! Fixed in the release shipped now, v1.35.10
