### ISSUE TITLE
Extract JS Files in Components as Modular ES Modules for Improved Performance

### ISSUE THREAD

**Issue by nastoychev** [tasteui/tasteui#711]
### Suggestion Theme

all

### Main Benefits

Lazy Loading and Chunked Modules: Vite enables lazy loading and automatic chunking of modules, ensuring that only the necessary components are loaded on demand. This optimizes performance by reducing the initial bundle size and improving load times for both development and production environments.

### Notes

Hey TallStackUI team, thanks for the awesome library!
With this issue, I’d like to propose an idea for improving the core package by extracting the JS components as modular ES modules. 
This enhancement can help bring the library up to modern standards, improving maintainability, performance, and overall developer experience. 
This approach can also unlock better build optimizations and faster load times, helping everyone get the most out of the library.
Looking forward to hearing your thoughts!

**Comment by devajmeireles** [comment]
Hey, @nastoychev ! This sounds like a good idea and I really need help improving our assets. Can you open a PR for v2 addressing this improvement? I would love to see your help on this. I will close this issue by marking it as a suggestion for v2. If you don't send us the PR then I will work on it a week before we release v2.

**Comment by nastoychev** [comment]
@devajmeireles I will try on the weekend for the solution. I already have it in some of my projects. Let's see if it easy to implement it here.
