### ISSUE TITLE
The input is not the same distance at the top and bottom

### ISSUE THREAD

**Issue by thiagotrancoso** [tasteui/tasteui#713]
### What Happened

When I use an `<x-input />` without the label, the input is not aligned with the same distance at the top and bottom. This happens because the `mt-1` class is applied to the input.

### Component

Input

### How to Reproduce

Just use the `<x-input />` directive inside a `<x-card />` and you will see the behavior.

![Screenshot_1](https://github.com/user-attachments/assets/6dfdfdfb-58fc-4a9e-a02b-14508fa26e0a)

![Screenshot_2](https://github.com/user-attachments/assets/4979bbef-c9a0-48f8-9121-71b83de49537)

It would be interesting to remove `mt-1` from the input and place `mb-1` in the label.

### Laravel Version

10.48.20

### Livewire Version

3.5.6

### TallStackUI Version

1.35.9

### PHP Version

8.2.8

### Operation System

Windows

**Comment by devajmeireles** [comment]
Hi @thiagotrancoso! First of all, sorry for the delay in responding. Yeah, I get it! I'm not going to fix this in v1, I'll address the fix for this in v2. Thanks!
