### ISSUE TITLE
[Bug]: Radio and checkbox colors for dark theme

### ISSUE THREAD

**Issue by iamroockie** [tasteui/tasteui#732]
### What Happened

Was it initially intended for the color to be exclusively dark in the dark theme? 

If not, you could add the rule 'dark:checked:bg-{color}' for each color in the TallStackUi\Foundation\Colors\Radio\RadioColors::background method.

![light](https://github.com/user-attachments/assets/88aa71e2-0075-4abb-a1fc-be9890085df8)
![dark](https://github.com/user-attachments/assets/d15cae8d-2a17-4b16-9e69-fe3000157a4c)

### Component

Checkbox

### How to Reproduce

Set dark theme and add `<x-checkbox color="blue"/>` or enable the dark theme on the product page: https://tallstackui.com/docs/form/checkbox#color-variations.

### Laravel Version

11.32

### Livewire Version

3.5.12

### TallStackUI Version

1.35.10

### PHP Version

8.3

### Operation System

Windows, Linux

**Comment by devajmeireles** [comment]
Yes! When dark mode is enabled, colors are displayed only when the mouse hovers over the checkbox, also checking it.
