### ISSUE TITLE
[Bug]: "Unable to locate a class or view for component" for any component using TALLSTACKUI_PREFIX=ts

### ISSUE THREAD

**Issue by jayenne** [tasteui/tasteui#737]
### What Happened

When I use TALLSTACKUI_PREFIX I cant get any component to be found.
I have follwed the documentation's instructions for Laravel ^11.9, livewire ^3.0 and tailwindCSS ^3.4.0
Note: this project include Laravel Jetstream and as such, I understand should use <x-ts ... /> to avoid css conficts.
my .env include the following var..
`TALLSTACKUI_PREFIX="ts"`

my app.blade.php include the following snippet...
```
<head>
...
        <!-- TALLSTACKUI scripts -->
        <tallstackui:script />
        <!-- Styles -->
        @vite('resources/css/app.css') @livewireStyles
        <!-- Scripts -->
        @vite('resources/js/head.js') @vite('resources/js/app.js')
</head>
```

My tailwind.config includes the following...
```
const defaultTheme = require("tailwindcss/defaultTheme");
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";

module.exports = {
    mode: "jit",
    darkMode: "class",
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./vendor/laravel/jetstream/**/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./vendor/tallstackui/tallstackui/src/**/*.php",
    ],
    presets: [require("./vendor/tallstackui/tallstackui/tailwind.config.js")],
    plugins: [forms, typography],
};
```

### Component

None (N/A)

### How to Reproduce

Add any componnent to any blade. In my case I have inlcuded the following...
```
        <div class="">
            <x-ts-step selected="1" helpers>
                <x-ts-step.items step="1"
                    title="Starting"
                    description="Step One">
                        @include('components.form.profile.step1')
                </x-ts-step.items>
                <x-ts-step.items step="2"
                    title="Advancing"
                    description="Step Two">
                        @include('components.form.profile.step2')
                </x-ts-step.items>
                <x-ts-step.items step="3"
                    title="Finishing"
                    description="Step Three">
                        @include('components.form.profile.step3')
                </x-ts-step.items>
            </x-ts-step>
        </div>
```

### Laravel Version

11.9

### Livewire Version

3.0

### TallStackUI Version

1.35

### PHP Version

8.3

### Operation System

macOS

### Notes

I would imagine this is only an intallation / setup / usage issue

**Comment by devajmeireles** [comment]
You must use the prefix "ts-" to be able to use the components in format like "x-ts-step".

**Comment by jayenne** [comment]
Hiya, thanks for the feedback, as you can see from my question I have used `<x-ts-step ... >` so should that be enough to work? as it isn't ...I don't think, but I should also be renaming the component folders within the `/resources/vendor/tallstack-ui/components` folder to `ts-step`?
