### ISSUE TITLE
[Bug]:  wire:model.live/lazy/blur="model.value" breaks steps.

### ISSUE THREAD

**Issue by jayenne** [tasteui/tasteui#738]
### What Happened

When I add wire:model.live/lazy/blur to <x-input /> breaks the steps. Only the first step is shown, the next button is missing but the <x-slot:finish> is shown.

### Component

Step

### How to Reproduce

add the follwing snippet to a blade file:
```
<div>
    <x-step selected="1" panels helpers>
        <x-step.items step="1"
                    title="Starting"
                    description="Step One">
            <x-input
                wire:model.blur="user.name"
                type="text"
                name="user.name"
                :value="$user['name']"
            />
        </x-step.items>
        <x-step.items step="2"
                    title="Advancing"
                    description="Step Two">
            STEP 2
        </x-step.items>
        <x-step.items step="3"
                    title="Finishing"
                    description="Step Three">
            STEP 3
        </x-step.items>
        <x-slot:finish>
            TallStackUI 🚀
        </x-slot:finish>
    </x-step>
</div>
```

### Laravel Version

11.9

### Livewire Version

3.4

### TallStackUI Version

1.35

### PHP Version

8.3

### Operation System

macOS

**Comment by devajmeireles** [comment]
I couldn't reproduce the issue mentioned:

![CleanShot 2024-11-20 at 00 43 57](https://github.com/user-attachments/assets/c6d1315b-49d6-460d-bd34-c25f0050bf0e)

**Comment by jayenne** [comment]
hmm, thank you for taking the time to check. I must have something quite wrong happening. I've created a clean repo of laravel, sail, jetstream (with livewire & teams) and TailwindUI with a simple form to demonstrate the issue I am having.
I hope you or somepne wouldn't mind taking a look for me please.
https://github.com/jayenne/twui
