### ISSUE TITLE
[Feature Request]: Please make alerts accept special characters (html escaped) when using the title or text attribute.

### ISSUE THREAD

**Issue by MGeurts** [tasteui/tasteui#740]
### Suggestion Theme

Alerts

### Main Benefits

When translation strings are shown inside an **alert** by using the **title** or the **text** attribute, escaped characters are not shown as they should.

`
 <x-ts-alert title="{{ __('team.transfer_ownership') }}" text="{{ __('team.can_not_transfer') }}" color="cyan" />
`

![TallStackUi - Alerts](https://github.com/user-attachments/assets/6d641fef-4fa5-4bc7-a4e0-40bced07f6fa)

When using the slot, all is fine.

`
<x-ts-alert>
    <x-slot:title>
        {{ __('team.transfer_ownership') }}
    </x-slot:title>
    {{ __('team.can_not_transfer') }}
</x-ts-alert>
`

Please make both ways consistent.

Thank you.

**Comment by devajmeireles** [comment]
Done. Available for v2 only.
