### ISSUE TITLE
[Bug]: The $placeholders argument of the Table component is overwritten in the constructor

### ISSUE THREAD

**Issue by rabol** [tasteui/tasteui#750]
### What Happened

```
<x-ts-table
   :headers="$tableHeaders"
   :rows="$tableRows"
   placeholders="['quantity' => 'Some text']"
   id="userTradingSymbols"
   filter
   paginate
   striped
/>
```

Then I would expect the text above the 'quantity' select to be 'Some text'

looking at the constructor of the component you can see that the first line simply overwrite the passed in argument

### Component

Table

### How to Reproduce

Just copy the code above into a blade file

### Laravel Version

11.34.2

### Livewire Version

v3.5.17 

### TallStackUI Version

1.36.1

### PHP Version

8.3.13

### Operation System

macOS

### Notes

Suggestion: change the code in the constructor from
```
$this->placeholders = trans('tallstack-ui::messages.table');

```

to
```
$this->placeholders = array_merge(trans('tallstack-ui::messages.table'), $this->placeholders ?? []);
```

**Comment by devajmeireles** [comment]
This is not a problem. The Table component is not defined to be able to use custom placeholders like other components. I just submitted a PR to adapt it for this purpose. The new version will be released in a few minutes.
