### ISSUE TITLE
Dark mode does not work if any  livewire component is sactive

### ISSUE THREAD

**Issue by mai1237** [tasteui/tasteui#95]
I put in the
resources\views\layouts\navigation.blade.php
             
             <div class="hidden sm:flex sm:items-center sm:ms-6">
                 <button x-on:click="darkTheme = !darkTheme" class="dark:text-white" >
                     {{-- Light / Dark Mode --}}
                     <div x-show="darkTheme">
                     <x-heroicon-s-sun class="h-5 w-5 " />
                     </div>
                     <div x-show="!darkTheme">
                         <x-heroicon-s-moon class="h-5 w-5 " />
                     </div>
I made a livewire component Tester
when i placed it in the
resources\views\dashboard.blade.php
<livewire:tester />
Light / Dark Mode was not working

**Comment by devajmeireles** [comment]
Hey, @mai1237 ! Thanks for your report.

According to my analysis, the problems happen due to the new Livewire approach that only delivers AlpineJS when we have Livewire components on the page.

To use the Dark Theme helper without Livewire components on the page, we need to load AlpineJS using the `@livewireScripts` directive as mentioned in the Livewire documentation.

I will update our documents now. Thanks again!

**Comment by mai1237** [comment]
I'm afraid I wasn't clear enough, resulting in a misunderstanding
So I will describe all my movements for the DarkModeToggler toy control
After installing Laravel the following followed

composer requires laravel/breeze --dev

php artisan breeze:install

   Which Breeze stack would you like to install?
   Blade with Alpine .............................................. .blade
   Livewire (Volt Class API) with Alpine ......................... livewire
   Livewire (Volt Functional API) with Alpine ......... livewire-functional
   React with Inertia .............................................. react
   Vue with Inertia .............................................. .... vue
   API only ................................................ ........... api
? blade

   Would you like dark mode support? (yes/no) [no]
? yes

   Which testing framework do you prefer? [PHPUnit]
   PHPUnit ................................................ ............. 0
   Pest ................................................ ................ 1
?

in the tailwind.config.js file
export default {
     darkMode: 'class',

in the resources\css\app.css file

[x-cloak] { display: none !important; }

then I ran
composer requires tallstackui/tallstackui

in the resources\views\layouts\app.blade.php file

         
         @tallStackUiScript
         @tallStackUiStyle
         
         @vite(['resources/css/app.css', 'resources/js/app.js'])
     </head>
     <body class="font-sans text-gray-900 antialiased">

in the tailwind.config.js file

     presets: [
         require('./vendor/tallstackui/tallstackui/tailwind.config.js')
     ],
...
     content: [
...
         './vendor/tallstackui/tallstackui/src/**/*.php',
     ],

I executed
npm run build && php artisan optimize:clear

in the resources\views\layouts\app.blade.php file

<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"
     x-data="tallstackui_darkTheme()"
     x-bind:class="{ 'dark bg-gray-700': darkTheme, 'bg-white': !darkTheme }"
>

I ran it below

composer requires blade-ui-kit/blade-heroicons

php artisan vendor:publish --tag=tallstackui.config

php artisan vendor:publish --tag=tallstackui.lang

php artisan livewire:make Tester

in the resources\views\layouts\navigation.blade.php file

  
             <div class="hidden sm:flex sm:items-center sm:ms-6">
                 <button x-on:click="darkTheme = !darkTheme" class="dark:text-white" >
                     {{-- Light / Dark Mode --}}
                     <div x-show="darkTheme">
                     <x-heroicon-s-sun class="h-5 w-5 " />
                     </div>

                     <div x-show="!darkTheme">
                         <x-heroicon-s-moon class="h-5 w-5 " />
                     </div>
                    </button>

routes\web.php

Route::get('/pages/p1', function () {
     return view('pages.p1');
})->middleware(['auth', 'verified'])->name('pages.p1');

in the resources\views\pages\p1.blade.php file
<x-app-layout>
     <x-slot name="header">
         <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
             {{ __('Dashboard') }}
         </h2>
     </x-slot>

     <div class="py-12">
         <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
             <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                 <div class="p-6 text-gray-900 dark:text-gray-100">
              


<livewire:tester />


             </div>
         </div>
     </div>
</div>
</x-app-layout>

when the url was http://m33.test/dashboard
the dark mode switcher worked normally as a navbar

when the url was http://m33.test/pages/p1
to dark mode switch was not responding

sorry for the trouble and inconvenience

**Comment by hitaloramon** [comment]
Hi, @mai1237

The livewire inserts its scripts whenever it finds a livewire component on your page. Your page "p1" does not have any livewire components and therefore no script is injected. To resolve this and work on all pages even if it doesn't have a livewire component on it, you need to insert the ``@livewireScripts`` directive in your app.blade.php above the tallstackui directives.

Another detail that apparently you didn't follow was step ``2 - Add the helper on the html tag of your layout`` of the doc https://tallstackui.com/docs/dark-theme

**Comment by devajmeireles** [comment]
Hey, @mai1237 .

The @hitaloramon is correct. The Livewire v3 has a new approach. As Livewire 3 brings the AlpineJS in its core, the Livewire and AlpineJS is only available when you have Livewire components in the page.

If you need to use the AlpineJS without need a Livewire component in the page, so you need to follow the @hitaloramon recommendation and use the livewire tag. This is part of the Livewire documentation.

I updated our docs with this instruction.

Thanks! 👍🏻

**Comment by mai1237** [comment]
I solved the problem in the following way
in the config\livewire.php file
I raised
     'inject_assets' => false,
and now it works, but I don't know what side effects I will have from this change

**Comment by devajmeireles** [comment]
> I solved the problem in the following way in the config\livewire.php file I raised 'inject_assets' => false, and now it works, but I don't know what side effects I will have from this change

If I'm not wrong this options is what control the default behavior of injecting assets, including AlpineJS. Althought it can work, I always prefer to add the livewire tag into the layout when I need the AlpineJS without need Livewire.
